RustCrypto/traits

block-cipher-trait/src/lib.rs
crypto-mac/src/lib.rs
digest/src/lib.rs

Change std handling

---

digest/src/dyn_digest.rs

Closes #38 
Strictly speaking it's a backward incompatible change, but I highly doubt it will cause any breakage.

Add box_clone to DynDigest

---

aead/src/lib.rs

As it seems like most commonly used AEAD algorithms can be implemented as what was previously called `StatelessAead`, this commit renames it to give it the shorter, more convenient name (`Aead`).
Additionally, it renames the prior `Aead` trait to `AeadMut`, as suggested by @burdges in #46.
This seems to follow the general Rust convention of making the immutable version of something shorter and easier to use, and explicitly calling out `Mut` where it exists.

aead: Rename StatelessAead -> Aead; Aead -> AeadMut (closes #46)

---

universal-hash/CHANGELOG.md
universal-hash/Cargo.toml

universal-hash v0.1.0

---

signature/CHANGES.md
signature/Cargo.toml
signature/src/lib.rs

- [docs.rs](https://docs.rs) rendering ([#76])
[#76]: https://github.com/RustCrypto/traits/pull/76

signature v1.0.0-pre.3

---

signature/src/lib.rs
signature/tests/signature_derive.rs

These apparently aren't running in CI(!)

signature: fix derive tests

---

.github/workflows/block-cipher-trait.yml
.github/workflows/crypto-mac.yml
.github/workflows/digest.yml
.github/workflows/signature.yml
.github/workflows/stream-cipher.yml

These ensure crates build in no_std environments

.github: add no_std build jobs

---

.github/workflows/universal-hash.yml
universal-hash/LICENSE-MIT

.github: add universal-hash configuration

---

aead/README.md
block-cipher-trait/Cargo.toml
block-cipher-trait/README.md
crypto-mac/Cargo.toml
crypto-mac/README.md
digest/Cargo.toml
digest/README.md
signature/README.md
signature/signature_derive/README.md
stream-cipher/Cargo.toml
stream-cipher/README.md
universal-hash/Cargo.toml
universal-hash/README.md

...and configure Cargo.toml(s) to render them on https://crates.io

Add basic README.md files to all crates

---

digest/README.md

Copypasta from: https://github.com/RustCrypto/hashes

digest: add more content to README.md

---

block-cipher-trait/src/lib.rs

As requested on #43, this splits out a `NewBlockCipher` trait from the original `BlockCipher` trait.

block-cipher-trait: split out NewBlockCipher trait

---

Cargo.lock
crypto-mac/Cargo.toml

crypto-mac: bump generic-array to v0.14

---

crypto-mac/src/dev.rs

These weren't properly updated before

crypto-mac: use NewMac in test macros

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

cryptography v0.1.1

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

- `RandomizedDigestSigner` ([#235])
[#235]: https://github.com/RustCrypto/traits/pull/235

signature v1.2.2

---

elliptic-curve/src/sec1.rs

I'd eventually like to get rid of this method, replacing it with a proper public key (associated?) type which supports a `ToEncodedPoint` conversion.
That said, until we have that, keeping it around for now makes upgrading the existing RustCrypto/elliptic-curve crates easier.

elliptic-curve: add back sec1::EncodedPoint::from_secret_key

---

elliptic-curve/src/sec1.rs

Adds a method for returning a `GenericArray` of the encoded point without a leading tag byte.

elliptic-curve: add `sec1::EncodedPoint::to_untagged_bytes()`

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- `std` feature ([#317])
[#317]: https://github.com/RustCrypto/traits/pull/317

cryptography v0.4.1

---

README.md
aead/README.md
block-cipher/README.md
crypto-mac/README.md
cryptography/README.md
digest/README.md
elliptic-curve/README.md
signature/README.md
stream-cipher/README.md
universal-hash/README.md

~~Should add these to each individual crate too, but I figured we could start here~~
Badges have been added to all README.mds

README.md(s): add Zulip badges

---

Cargo.lock
signature/async/CHANGELOG.md
signature/async/Cargo.toml
signature/async/src/lib.rs

async-signature v0.0.1

---

stream-cipher/src/lib.rs

Support for initializing a stream cipher from a [`BlockCipherMut`](https://docs.rs/block-cipher/0.8.0/block_cipher/trait.BlockCipherMut.html).
This is a corollary to [`FromBlockCipher`](https://docs.rs/stream-cipher/0.7.1/stream_cipher/trait.FromBlockCipher.html), but for cases where `&mut` access is needed to the inner block cipher instance (e.g. cryptographic accelerator hardware peripherals).
Using chained blanket impls, it's possible to allow a blanket impl of `NewStreamCipher` for types which impl either `FromBlockCipherMut` or `FromBlockCipher`.

stream-cipher: add FromBlockCipherMut trait

---

elliptic-curve/src/public_key.rs
elliptic-curve/src/sec1.rs

From a practical perspective, `sec1::EncodedPoint` is always used with public values.
The previous use of `CtOption` was almost exclusively for error handling, and in every case immediately wrapped in an `Option` or `Result` to avoid end users dealing with public keys from having to deal with `subtle`.
Removing the usage of `subtle` in these cases dramatically simplifies the code and required trait bounds.

elliptic-curve: remove `subtle` usage on sec1::EncodedPoint

---

.github/workflows/elliptic-curve.yml
Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/secret_key.rs

Support for decoding PEM-encoded PKCS#8 `SecretKey`s

elliptic-curve: PKCS#8 PEM support

---

Cargo.lock
elliptic-curve/src/secret_key.rs

Added in this `pkcs8` PR:
https://github.com/RustCrypto/utils/pull/96

elliptic-curve: impl FromPkcs8 trait on SecretKey

---

elliptic-curve/src/sec1.rs

Obtain the `Tag` needed to encode a given set of `sec1::Coordinates`

elliptic-curve: add `sec1::Coordinates::tag` method

---

elliptic-curve/src/sec1.rs

Support for conditionally selecting an `EncodedPoint` in constant time leveraging the `ConditionallySelectable` trait from the `subtle` crate.

elliptic-curve: impl `ConditionallySelectable` for `EncodedPoint`

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs
elliptic-curve/tests/pkcs8.rs

Adds support for serializing `SecretKey` as PKCS#8.

elliptic-curve: impl `pkcs8::ToPrivateKey` for `SecretKey`

---

elliptic-curve/src/lib.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Adds support for serializing `PublicKey` as ASN.1 DER and PEM.

elliptic-curve: impl `pkcs8::ToPublicKey` for `PublicKey`

---

password-hash/src/lib.rs

Closes #450
Implements a minimal trait for upgrading raw MCF hash strings to `PasswordHash` (PHC string format).
Also provides a default `verify_mcf_hash` method which computes a `PasswordHash` on the fly and verifies it using the `PasswordHasher` trait.

password-hash: Modular Crypt Format (MCF) support

---

password-hash/src/output.rs

Handles checking the output length against the allowed min/max lengths as well as allocating and slicing the array which `Output` wraps.

password-hash: add `Output::init_with` method

---

password-hash/src/lib.rs

password-hash: have McfHasher::upgrade_mcf_hash take &self

---

elliptic-curve/src/ecdh.rs

Closes #417
Removes all SEC1 encoding-related concerns from the ECDH API, which are a legacy from when there wasn't a `PublicKey` type.
Replaces them with a `SharedSecret<C>: From<&AffinePoint<C>>` bound which is intended to be satisfied by a curve-specific conversion.

elliptic-curve: simplify ECDH trait bounds

---

Cargo.lock
Cargo.toml
elliptic-curve/src/jwk.rs
elliptic-curve/src/secret_key/pkcs8.rs

elliptic-curve: leverage `der` crate's uint support

---

password-hash/src/errors.rs

Add an error variant for reporting invalid versions

password-hash: add HasherError::Version

---

Cargo.lock
digest/Cargo.toml
digest/src/core_api.rs
digest/src/dev.rs
digest/src/lib.rs

Also implement `Reset` in terms of `Default`.

digest: fix test macro

---

Cargo.lock
README.md
crypto/Cargo.toml
crypto/src/lib.rs
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs
password-hash/src/output.rs
password-hash/src/salt.rs

password-hash v0.1.0

---

password-hash/tests/encoding.rs

It was gated under a removed cargo feature

password-hash: fix encoding test

---

aead/src/stream.rs

aead: add STREAM diagram to rustdoc

---

elliptic-curve/src/error.rs
elliptic-curve/src/jwk.rs

Adds more rustdoc to the `JwkEcKey` type.

elliptic-curve: documentation improvements

---

elliptic-curve/src/scalar/bytes.rs

Adds impls of `ConditionallySelectable` and `ConstantTimeEq`

elliptic-curve: impl `subtle` traits for `ScalarBytes<C>`

---

Cargo.lock
cipher/Cargo.toml
crypto-common/Cargo.toml
crypto-mac/Cargo.toml
digest/Cargo.toml

crypto-common v0.1.0-pre

---

Cargo.lock
crypto/CHANGELOG.md
crypto/Cargo.toml
crypto/src/lib.rs

Initial (re-)release of the `cryptography` crate as `crypto`

crypto v0.2.0

---

Cargo.lock
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Use helper methods added in https://github.com/RustCrypto/utils/pull/481

elliptic-curve: use value error helpers

---

aead/src/lib.rs
aead/src/stream.rs

Allows AEAD-related results to be abbreviated as `aead::Result<T>`.

aead: add `Result` type alias

---

password-hash/src/lib.rs

Adds an owned form of the `PasswordHash` type containing a serialized password hash string, gated on the `alloc` feature.
Closes #735

password-hash: add `PasswordHashString`

---

signature/LICENSE-APACHE
signature/LICENSE-MIT

signature: add LICENSE-APACHE and LICENSE-MIT

---

elliptic-curve/src/scalar/non_zero.rs

The previous impl wrote `0`, which violates `NonZeroScalar`'s invariant that the inner scalar value must be non-zero.
This commit changes the impl to write `1` instead.

elliptic-curve: fix `Zeroize` impl on `NonZeroScalar`

---

crypto/Cargo.lock
elliptic-curve/src/scalar/non_zero.rs

Add support for determining if a given non-zero scalar is in the upper or lower half of the order.

elliptic-curve: impl `IsHigh` for `NonZeroScalar<C>`

---

digest/src/mac.rs

Fix doc cfg for CtOutput and MacError

---

digest/CHANGELOG.md
digest/src/digest.rs
digest/src/lib.rs

Add Update::chain and Digest::new_with_prefix

---

kem/CHANGELOG.md
kem/Cargo.lock
kem/Cargo.toml
kem/LICENSE-MIT
kem/README.md

kem v0.1.0

---

README.md

README.md: add `kem` crate

---

signature/derive/CHANGELOG.md
signature/derive/LICENSE-APACHE
signature/derive/LICENSE-MIT
signature/derive/src/lib.rs

- Support for new `digest` v0.10 API ([#850])
[#850]: https://github.com/RustCrypto/traits/pull/850

signature-derive v1.0.0-pre.4

---

Cargo.lock
signature/async/CHANGELOG.md
signature/async/Cargo.toml
signature/async/LICENSE-APACHE
signature/async/LICENSE-MIT
signature/async/src/lib.rs

- Bump `signature` crate dependency to v1.5 ([#850], [#867])
[#850]: https://github.com/RustCrypto/traits/pull/850
[#867]: https://github.com/RustCrypto/traits/pull/867

async-signature v0.1.0

---

elliptic-curve/src/hash2curve/group_digest.rs

These docs aren't ideal to begin with. In any case, I hope this clarifies some things.

Fix `GroupDigest` docs

---

elliptic-curve/src/hash2field/expand_msg.rs
elliptic-curve/src/hash2field/expand_msg/xmd.rs
elliptic-curve/src/hash2field/expand_msg/xof.rs

Handle empty `dst`

---

.github/dependabot.yml
.github/workflows/security-audit.yml
.github/workflows/workspace.yml

See RustCrypto/signatures#440 and RustCrypto/signatures#441.
I could move Clippy and Rustftm to each workflow instead of a common workspace workflow?

Add missing jobs to excluded workspace crates

---

.github/workflows/aead.yml
.github/workflows/async-signature.yml
.github/workflows/cipher.yml
.github/workflows/crypto-common.yml
.github/workflows/crypto.yml
.github/workflows/digest.yml
.github/workflows/elliptic-curve.yml
.github/workflows/kem.yml
.github/workflows/password-hash.yml
.github/workflows/signature.yml
.github/workflows/universal-hash.yml
Cargo.lock
crypto/Cargo.lock
elliptic-curve/Cargo.lock
kem/Cargo.lock
password-hash/Cargo.lock

Test min versions build

---

.github/workflows/async-signature.yml
.github/workflows/signature.yml
signature/Cargo.toml
signature/async/Cargo.toml
signature/derive/Cargo.toml

signature: fix min versions build

---

cipher/src/stream.rs

Fix typo in comment

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/README.md
password-hash/src/lib.rs

- `authentication` category to Cargo.toml ([#976])
[#976]: https://github.com/RustCrypto/traits/pull/976

password-hash v0.4.1

---

digest/CHANGELOG.md

digest: yank v0.10.0 and v0.10.1

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/README.md

- docs.rs metadata ([#1031])
[#1031]: https://github.com/RustCrypto/traits/pull/1031

password-hash v0.4.2

---

Cargo.lock
crypto-common/CHANGELOG.md
crypto-common/Cargo.toml
crypto-common/src/lib.rs

- `getrandom` feature ([#1034])
[#1034]: https://github.com/RustCrypto/traits/pull/1034

crypto-common v0.1.4

---

.github/workflows/elliptic-curve.yml
elliptic-curve/Cargo.toml
elliptic-curve/src/public_key.rs

It previously resulted in a compile error

elliptic-curve: fix `arithmetic` + `serde` feature combo

---

signature/async/src/lib.rs

Adds a trait which provides an async equivalent of `Keypair` with requests to the signer sent async.
Like `Signer`/`AsyncSigner`, also provides a blanket impl for the non-async `Keypair` trait.

async-signature: add `AsyncKeypair`

---

Cargo.lock
kem/Cargo.toml
kem/tests/hpke.rs

HPKE causes compilation issues in the current form after `cargo update`

Update Cargo.lock and disable HPKE tests in kem

---

Cargo.lock
crypto/Cargo.toml
signature/Cargo.toml
signature/async/Cargo.toml
signature/derive/Cargo.toml

signature v2.0.0-pre.0

---

Cargo.lock
digest/CHANGELOG.md
digest/Cargo.toml
digest/src/mac.rs

digest: add Mac::verify_reset and Mac::verify_slice_reset methods

---

elliptic-curve/src/secret_key.rs

elliptic-curve: improve `SecretKey` impl for `Debug`

---

elliptic-curve/src/scalar/nonzero.rs

They were still coupled to `FieldBytes` rather than forwarding to `<Scalar<C> as Reduce<I>>::Bytes` properly.
Also, this commit reverses the relationship so `Reduce` has the non-zero reduction implementation (forwarding to `Scalar`'s `ReduceNonZero` impl) and the `ReduceNonZero` impl for `NonZeroScalar<C>` calls `Reduce`.
This is needed because `Reduce` defines the `Bytes` type and `ReduceNonZero` is bounded on it (in the trait definition).

elliptic-curve: fix `Reduce` impls for `NonZeroScalar<C>`

---

password-hash/src/lib.rs
password-hash/src/salt.rs

Automatically generate feature-specific documentation

password-hash: use `doc_auto_cfg`

---

elliptic-curve/src/public_key.rs

Adds the following conversion impls to `PublicKey`
- `TryFrom`: `sec1::{CompressedPoint`, `EncodedPoint}`
- `Into` (via `From`): `sec1::{CompressedPoint`, `EncodedPoint}`

elliptic-curve: `PublicKey` <-> SEC1 conversions

---

cipher/src/stream_wrapper.rs

Fix unsoundness with block size equal to zero

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml
aead/src/lib.rs

- `arrayvec` feature ([#1219])
[#1219]: https://github.com/RustCrypto/traits/pull/1219

aead v0.5.2

---

password-hash/src/salt.rs

Fix Documentation for `struct Salt`

---

digest/src/lib.rs

digest: explicitly state that size is measured in bytes

---

elliptic-curve/src/secret_key.rs

Instead of defining a separate constant for this, it can be obtained from the `EcPrivateKey` type, which impls the `PemLabel` trait.

elliptic-curve: use `sec1::EcPrivateKey::PEM_LABEL`

---

crypto/CHANGELOG.md
crypto/Cargo.lock
crypto/Cargo.toml

Unchanged from v0.5.0, but published to trigger a new docs.rs build

crypto v0.5.1

---

cipher/src/stream_wrapper.rs

cipher: mark set_pos_unchecked private method as unsafe

---

digest/src/digest.rs
digest/src/lib.rs

digest: add `DynDigestWithOid` wrapper trait

---

Cargo.lock
aead/Cargo.toml

Not sure why dependabot closed #1374 🤔

Bump `heapless` dependency to v0.8

---

cipher/src/dev/block.rs
digest/src/dev.rs

These are breaking the build on the latest `stable`

Remove unused imports

---

Cargo.lock
async-signature/Cargo.toml

async-signature v0.5.0-pre.0

---

password-hash/src/errors.rs

Fix typo in `password-hash/src/errors.rs`

---

elliptic-curve/src/jwk.rs

Recent nightlies started picking up on these

elliptic-curve: fix unknown qualifications

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/error.rs
elliptic-curve/src/point/non_identity.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar/nonzero.rs
elliptic-curve/src/scalar/primitive.rs
elliptic-curve/src/secret_key.rs

This was added in `subtle` v2.6.0.

elliptic-curve: leverage `CtOption::into_option`

---

digest/README.md

digest: fix types in README

---

Cargo.lock
Cargo.toml
elliptic-curve/src/secret_key/pkcs8.rs

see https://github.com/RustCrypto/formats/pull/1483

elliptic-curve: pkcs8 API changes

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/hash2curve/hash2field/expand_msg.rs
elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs
elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
elliptic-curve/src/hash2curve/isogeny.rs
elliptic-curve/src/hash2curve/osswu.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point/non_identity.rs
elliptic-curve/src/scalar/blinded.rs
elliptic-curve/src/scalar/nonzero.rs

elliptic-curve: add missing `Debug` impls

---

elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

The OID identifies the particular elliptic curve the key is for.
Without it, OpenSSL can't parse these keys. See #1706.

elliptic-curve: include curve OID in SEC1 private keys

---

cipher/Cargo.toml
crypto-common/Cargo.toml

Example use: 
https://github.com/RustCrypto/block-ciphers/pull/467

cipher: propagate the zeroize to hybrid-array

---

signature/src/hazmat.rs
signature/src/signer.rs

signature: async `rand_core` v0.9 updates

---

Cargo.lock
Cargo.toml

https://github.com/RustCrypto/MACs/pull/178 merged

Move back git pin to master branch

---

.github/workflows/cipher.yml
.github/workflows/crypto.yml
.github/workflows/password-hash.yml
Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml
signature/Cargo.toml

see https://github.com/zkcrypto/ff/pull/130

move ff back to release branch

---

aead/Cargo.toml
async-signature/Cargo.toml
cipher/Cargo.toml
crypto-common/Cargo.toml
crypto/Cargo.toml
digest/Cargo.toml
elliptic-curve/Cargo.toml
kem/Cargo.toml
password-hash/Cargo.toml
signature/Cargo.toml
signature_derive/Cargo.toml
universal-hash/Cargo.toml

See https://github.com/RustCrypto/meta/issues/22

Use the standard order of the `[package]` section fields

---

elliptic-curve/src/ops.rs

This PR does a couple of things:
- Changes the implementation to require two write stores instead of 3 write stores and one read.
- Add a `BatchInvert::batch_invert_mut()` methods that allows users to pass one of the two stores themselves. With this a single store can be allocated instead of 3.
- Reduce the bounds from `Invert + Mul + Copy + Default + ConditionallySelectable` to `Field`.
This was largely inspired by [`curve25519-dalek`s implementation](https://github.com/dalek-cryptography/curve25519-dalek/blob/dd5bd108d6985491acb3de25497fb082a29c9fb7/curve25519-dalek/src/scalar.rs#L788-L837). I adjusted it a bit to save two unnecessary multiplications by one.
Companion PR: https://github.com/RustCrypto/elliptic-curves/pull/1205.

Improve `BatchInvert`

---

Cargo.lock
signature/Cargo.toml

Includes `MultipartSigner`/`MultipartVerifier`

signature 3.0.0-rc.1

---

signature/README.md

Breaks out a more extensive list of supported crates

signature: update README.md
