RustCrypto/traits

block-cipher-trait/src/dev.rs
block-cipher-trait/src/lib.rs
crypto-mac/Cargo.toml
crypto-mac/src/dev.rs
crypto-mac/src/lib.rs
digest/Cargo.toml
digest/src/dev.rs
digest/src/digest.rs
digest/src/lib.rs

It adds [reset functionality](https://github.com/RustCrypto/traits/issues/6) to tratis from `digest` and `crypto-mac` traits. Additionally it changes `Mac` and `BlockCipher` initialization methods.

New traits version

---

block-cipher-trait/Cargo.toml
block-cipher-trait/src/lib.rs
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs
digest/src/lib.rs

Add Error and Display impls for error types, while still ensuring no_std compatibility.

Add Error and Display impls for error types

---

crypto-mac/Cargo.toml

Hi, we released version `2.0.0` of `subtle`.
There are no changes to the parts used by `crypto-mac`, but the `ConditionallySelectable` trait was redesigned to fix some design issues that made it difficult to customize the implementation (this had no security content, just ergonomics / interaction with orphan rules). Unfortunately this meant bumping the semver major version.
Changing to version 2 should have no impact on any of the uses inside of `crypto-mac`, or any of the users of `crypto-mac`, so the practical impact should be small, but since it is part of the public API I believe that this is a breaking change and would require a version bump for `crypto-mac`.

Use subtle v2

---

.travis.yml
build_std.sh

Updates travis.yml and build_std to ignore aead in build_std and fix the xargo command.

Build fixes

---

aead/rustfmt.toml
aead/src/lib.rs

I just noticed that in #49 I swapped the `Aead`/`AeadMut` names, but didn't update the comments accordingly, so `Aead` is documented as saying "Refer to the `Aead::encrypt`/`decrypt` docs. Oops.
This commit swaps the comments to match.

aead: Fix comments on Aead::encrypt/decrypt

---

.travis.yml
Cargo.toml
build_std.sh
universal-hash/CHANGELOG.md
universal-hash/Cargo.toml
universal-hash/LICENSE-APACHE
universal-hash/LICENSE-MIT
universal-hash/src/lib.rs

This crate contains a generic trait for [universal hash functions] (e.g. GHASH, POLYVAL, Poly1305) whose API is shaped by my experiences implementing both [Poly1305] and [POLYVAL] and trying to build a common abstraction with the things I want, which are the following:
- `Block` as the unified abstraction for all input and output values: performance implementations will immediately want to load these values into an XMM register on x86 architectures. For this reason this implementation enforces that all `Block` types impl `Copy`, which (empirically, by my own measurements) provides better performance than using references.
- Built-in `subtle` comparison support ala `crypto-mac`: let's not beat around the bush here, while a UHF is not a "MAC" in and of itself, we're really always going to …

universal-hash: Initial crate implementation

---

universal-hash/CHANGELOG.md
universal-hash/Cargo.toml
universal-hash/src/lib.rs

Of course the minute I go to actually impl `UniversalHash` on `poly1305` I discovered it uses a 32-bit key size and a 16-bit output size...
This splits the `BlockSize` associated type  accordingly into `KeySize` and `OutputSize`.

universal-hash: Split KeySize/OutputSize

---

universal-hash/src/lib.rs

In #55 I split the `UniversalHash::BlockSize` associated type into:
- [`UniversalHash::KeySize`](https://docs.rs/universal-hash/0.2.0/universal_hash/trait.UniversalHash.html#associatedtype.KeySize)
- [`UniversalHash::OutputSize`](https://docs.rs/universal-hash/0.2.0/universal_hash/trait.UniversalHash.html#associatedtype.OutputSize)
However, "OutputSize" is also used as the size of inputs by the `update_block` method:
https://docs.rs/universal-hash/0.2.0/universal_hash/trait.UniversalHash.html#tymethod.update_block
```rust
fn update_block(&mut self, block: &GenericArray<u8, Self::OutputSize>)
```
Since it's used for both inputs and outputs, I think `BlockSize` probably makes more sense (there and back again).
Obviously a semver breaking change.

universal-hash: OutputSize -> BlockSize

---

aead/Cargo.toml
aead/src/lib.rs

This commit adds `encrypt_in_place_detached()` and `decrypt_in_place_detached()` methods to `Aead` and `AeadMut`, along with default implementations of `encrypt()` and `decrypt()` which assume a postfix authentication tag.
Presently all of the AEAD implementations in `RustCrypto/AEADs` use this pattern. This PR exposes the detached interface as a public API:
https://github.com/RustCrypto/AEADs/pull/21
Note that this need not be the only in-place API (hence the long name with `_detached` on the end. I plan on doing a follow-up PR for adding an in-place API which does not depend on `alloc` but also handles ciphertext message assembly/parsing, which would be more useful for end
users.
That said, this API isn't just useful for AEAD implementers: there are genuine use cases for a detached API …

aead: Add detached in-place encrypt/decrypt API; make alloc optional

---

aead/Cargo.toml
aead/src/lib.rs

NOTE: This PR includes the commit which adds the detached API from #58. It might make sense to review that first.
This PR adds a `Buffer` trait for `Vec`-like types which impl `AsRef<[u8]>`, `AsMut<[u8]>`, `extend_from_slice()`, and `truncate()`, and optionally impls it for `Vec<u8>` (when the `alloc` feature is enabled), along with the option to use `heapless::Vec` (when the `heapless` feature is enabled), providing a true `#![no_std]`-friendly option.
Uses `impl Buffer` as the argument for `encrypt_in_place` and `decrypt_in_place`, with default implementations that assume a postfix authentication tag. This allows these methods to handle ciphertext assembly and parsing, after which they can invoke the `_detached` APIs.

aead: Add in-place API based on `Buffer` trait

---

.travis.yml
README.md
crypto-mac/src/errors.rs

It’s been deprecated since Rust 1.41, and we already have a Display implementation anyway.

Remove deprecated std::error::Error::description() and bump MSRV from 1.21 to 1.31

---

aead/Cargo.toml
block-cipher-trait/Cargo.toml
crypto-mac/Cargo.toml
digest/Cargo.toml
stream-cipher/Cargo.toml
universal-hash/Cargo.toml

> One of my projects has a bunch of duplicate versions of generic-array, through block-buffer (from sha-2), crypto-mac (through hmac) and digest (through hmac and sha2) -- all of them through usage in postgres-protocol. Here's a start at fixing this up.
I'm using chacha20poly1305 and sha2 directly and end up with *six* dependencies on the old generic-array.
c.f. https://github.com/RustCrypto/utils/pull/39

chore: no-change generic-array 0.12 -> 0.13

---

README.md
signature/README.md
signature/src/error.rs
signature/src/lib.rs
signature/src/signature.rs
signature/src/signer.rs
signature/src/verifier.rs

This commit adds high-level descriptions of how the `signature` crate is designed, including alternatives considered, and hopefully details why it is the way it is.
These notes also include a rough sketch of potential additional future traits which could better optimize for implementers of signature traits, rather than consumers (with a blanket impl to link the two).

signature: design documentation

---

signature/Cargo.toml
signature/src/lib.rs
signature/src/signer.rs
signature/src/verifier.rs

Adds a trait which allows passing a `rand_core::CryptoRng` to the signing operation, which is useful for signature algorithms which rely on a source of randomness, e.g. RSASSA-PSS and traditional ECDSA (with a random `k` value)
Presently gated under the `rand-preview` feature (since `rand_core` is presently pre-1.0).

signature: add RandomizedSigner trait

---

aead/Cargo.toml
aead/src/lib.rs

...with `std::error::Error` impl for `aead::Error`.
This is the least-common-bound for `std` users using a type erasure strategy for error handling, so it's helpful for error types to impl this trait when users want that.

aead: Add optional `std` feature

---

signature/src/error.rs
signature/src/lib.rs

- Don't print `Error::source` in the `Display` impl for `Error`   as this information is available as `Error::source`'s `Display`
- Adds a `From` impl for creating an `Error` from a `BoxError`.

signature: Error cleanups

---

signature/CHANGES.md
signature/Cargo.toml
signature/src/lib.rs

- `RandomizedSigner` trait ([#73])
- Design documentation ([#72])
- Error cleanups ([#74])
- Crate moved to `RustCrypto/traits` ([#71])
[#74]: https://github.com/RustCrypto/traits/pull/74
[#73]: https://github.com/RustCrypto/traits/pull/73
[#72]: https://github.com/RustCrypto/traits/pull/72
[#71]: https://github.com/RustCrypto/traits/pull/71

signature 1.0.0-pre.2

---

signature/Cargo.toml
signature/src/error.rs
signature/src/lib.rs

Fixes rendering of `doc(cfg(...))` on docs.rs by passing the proper `cfg` attribute in that environment and enabling the `doc_cfg` (nightly-only) feature.

signature: fix docs.rs rendering

---

README.md
signature/signature_derive/src/lib.rs

Adds a description of each of the derive macros

signature: improve docs for `signature_derive`

---

signature/src/error.rs

We can revisit adding this back after 1.0, but it seems possible such a type may eventually be stabilized in `std`.
It's better to "wait and see" if that happens and add `BoxError` back in the event there's a desire for more ergonomic boxed errors for `std` users rather than prematurely stabilizing it if it turns out to be
unnecessary.

signature: remove BoxError type alias

---

signature/Cargo.toml

I (and I'm sure a few others) often look at the Cargo.toml to find out what a crate's features are. It might be a good idea to explicitly point out there that the preview features are unstable.

Mark preview feature as unstable in Cargo.toml

---

signature/src/error.rs

Prevents usage of `Error {}` in `no_std` contexts.

signature: ensure `Error::new()` is mandatory

---

signature/src/signature.rs

...rather than `impl AsRef<[u8]>`, which both breaks object safety, and in many cases is less convenient (e.g. when deref coercion would allow types that don't `impl AsRef` to work)

signature: have Signature::from_bytes take a byte slice

---

signature/CHANGES.md
signature/Cargo.toml

- Mark preview features as unstable in `Cargo.toml` ([#82])
- Have `Signature::from_bytes` take a byte slice ([#84])
- Ensure `Error::new()` is mandatory ([#83])
- `BoxError` type alias ([#81])
[#84]: https://github.com/RustCrypto/traits/pull/84
[#83]: https://github.com/RustCrypto/traits/pull/83
[#82]: https://github.com/RustCrypto/traits/pull/82
[#81]: https://github.com/RustCrypto/traits/pull/81

signature 1.0.0-pre.4

---

signature/src/signature.rs

For consistency with `Signature::from_bytes`, as suggested here:
https://github.com/RustCrypto/traits/issues/78#issuecomment-599285828

signature: rename Signature::as_slice -> Signature::as_bytes

---

signature/src/error.rs

In the event errors have a source, this `Debug` impl invokes the `Display` impl on the source (required by the bounds of `std::error::Error`) to make it easier to inspect.

signature: improve Debug impl on Error

---

signature/CHANGES.md
signature/Cargo.toml
signature/src/lib.rs

- Improve `Debug` impl on `Error` ([#89])
- Rename `Signature::as_slice` -> `as_bytes` ([#87])
[#89]: https://github.com/RustCrypto/traits/pull/89
[#87]: https://github.com/RustCrypto/traits/pull/87

signature v1.0.0-pre.5

---

signature/signature_derive/src/lib.rs
signature/src/lib.rs
signature/src/signature.rs
signature/tests/signature_derive.rs

The previous name poorly described what these signature types are: ones capable of producing a signature of a message which was hashed in advance.
The phrase "pre-hash" is a relatively common one and better describes this property.

signature: rename DigestSignature => PrehashSignature

---

signature/CHANGES.md
signature/Cargo.toml
signature/src/lib.rs

Initial 1.0 release! 🎉
- Rename `DigestSignature` => `PrehashSignature` ([#96])
[#96]: https://github.com/RustCrypto/traits/pull/96

signature v1.0.0

---

signature/Cargo.toml
signature/signature_derive/CHANGES.md
signature/signature_derive/Cargo.toml

- Rename `DigestSignature` => `PrehashSignature` ([#96])
[#96]: https://github.com/RustCrypto/traits/pull/96

signature_derive v1.0.0-pre.2

---

signature/CHANGES.md
signature/Cargo.toml
signature/src/lib.rs

- Upgrade `signature_derive` to v1.0.0-pre.2 ([#98])
[#98]: https://github.com/RustCrypto/traits/pull/98

signature v1.0.1

---

aead/src/lib.rs
block-cipher-trait/src/lib.rs
crypto-mac/src/lib.rs
digest/src/lib.rs
stream-cipher/src/lib.rs
universal-hash/src/lib.rs

`#![forbid(unsafe_code)]` attributes make rustc abort compilation if
there are any unsafe blocks in the crate, and exceptions cannot be made
with allow/warn attributes.
Didn't add badges to the readme because signature already has this attribute and no badge had been added.

Forbid unsafe code in all crates

---

.travis.yml
README.md
aead/Cargo.toml
block-cipher-trait/Cargo.toml
digest/Cargo.toml
stream-cipher/Cargo.toml
universal-hash/Cargo.toml

In 0.14 they added a pretty nice feature, which is that you can
now split not just arrays that you hold by value, but you can
split references to generic arrays, into a pair of references to
generic arrays corresponding to the subslices, where the size
calculations are done correctly at compile-time and the buffer
size information is all preserved.
https://docs.rs/generic-array/0.14.1/src/generic_array/sequence.rs.html#302-320
I have some ECIES code that looks like this, that builds on `aead` trait:
```
fn decrypt_in_place_detached(
&self,
key: &RistrettoPrivate,
footer: &GenericArray<u8, Self::FooterSize>,
buffer: &mut [u8],
) -> Result<(), Error> {
let (footer, version_data): (_, &GenericArray<u8, U2>) = footer.split();
```
Alternate version is like
```
fn decrypt_in_place_detached( …
```

Uprev generic array to version 0.14

---

crypto-mac/src/lib.rs
digest/src/dev.rs
digest/src/digest.rs
digest/src/dyn_digest.rs
digest/src/lib.rs

As discussed in #43, following "Initialize-Update-Finalize" (IUF) nomenclature, this renames the `input` methods in `crypto-mac` and `digest` to be `update` instead, and also renames the `digest::Input` trait to `digest::Update`.

crypto-mac/digest: rename `input` to `update`

---

digest/src/digest.rs
digest/src/lib.rs

Replaces generic parameters on methods which take an `AsRef<[u8]>` bound with `impl AsRef<[u8]>`.
This syntax is semantically equivalent but eliminates a generic parameter, which (IMO) makes the method signature easier to read, and in general seems to be preferred after the introduction of `impl Trait`.

digest: use impl Trait notation for AsRef<[u8]>

---

block-cipher-trait/src/errors.rs
crypto-mac/src/errors.rs
digest/src/errors.rs
stream-cipher/src/errors.rs

This method has been "soft-deprecated" since 1.27.0 and officially deprecated as of Rust 1.42.0.

Remove deprecated `Error::description` methods

---

crypto-mac/src/lib.rs

...and `code` to `into_bytes`, as discussed in #43.
This is consistent with the API in the `universal-hash` trait.

crypto-mac: rename `MacResult` to `Output`

---

digest/src/digest.rs
digest/src/lib.rs

Adds a `digest::Output<D>` type alias for a `GenericArray<u8; N>`, which is less unwieldy to remember/type.

digest: add `Output` type alias

---

digest/Cargo.toml
digest/src/dev.rs
digest/src/digest.rs
digest/src/lib.rs

Adds a `--cfg docsrs` option enabled in `package.metadata.docs.rs` which toggles on `doc_cfg` support.
This can be used for tagging what cargo features must be enabled to use certain API features.
Example output:

digest: docs.rs documentation improvements + doc_cfg

---

aead/Cargo.toml
aead/README.md
aead/src/lib.rs
signature/README.md

Improves the README.md documentation and adds `doc_cfg` support for flagging which API features require `alloc` support.

aead: documentation improvements + doc_cfg

---

aead/Cargo.toml

Adds a `readme` key to `Cargo.toml`

aead: render README.md on crates.io

---

aead/src/lib.rs
block-cipher-trait/src/lib.rs
crypto-mac/src/lib.rs
digest/src/lib.rs
stream-cipher/src/lib.rs
universal-hash/src/lib.rs

Inspired by the `heapless` crate:
https://github.com/RustCrypto/traits/issues/43#issuecomment-633109800
This re-export provides convenient access to the type-level numeric constants provided by `typenum`, which should make using `generic-array` less annoying.

Re-export `typenum::consts` as `consts`

---

aead/src/lib.rs

In many AEAD implementations we pass the key directly onto `NewBlockCipher`, e.g. in the `aes-gcm` crate:
https://github.com/RustCrypto/AEADs/blob/af9926e/aes-gcm/src/lib.rs#L183
This makes an unnecessary copy of the key which therefore necessitates zeroing it out.
If we borrow the key at the time the cipher is initialized, we can avoid making this copy.

aead: have NewAead borrow the key

---

aead/src/lib.rs

It's syntactically annoying to have to use `GenericArray<u8, N>` for these types.
This commit introduces a set of `GenericArray` type aliases for them instead.
Notably, `Key` might benefit from having a proper struct which handles things like zeroization on drop and prevents accidental exposure in debug output, however this PR uses a simple `GenericArray` type alias for now.

aead: type aliases for `Key`, `Nonce`, and `Tag`

---

universal-hash/src/lib.rs

Updating (in the IUF sense) the UHF state by a block is the core "update" primitive, so it makes sense to make it first-class.

universal-hash: rename `update_block` => `update`

---

block-cipher-trait/README.md
crypto-mac/README.md
digest/README.md
signature/README.md
stream-cipher/README.md
universal-hash/README.md

Adds links to the Wikipedia definitions of various algorithms, as well as the RustCrypto repositories where various algorithm-specific implementations of the traits are located.

README.md(s): add supplemental links

---

aead/src/lib.rs

Splits the `Aead` and `AeadMut` trait into the following:
- `Aead` and `AeadMut`:gated on the `alloc` feature
- `AeadInPlace` and `AeadMutInPlace`: object-safe, always available
This further has the benefit that implementors who don't want to provide or abstract over the in-place APIs no longer have to. See `ursa` as a [real world example of where this split is useful](https://github.com/hyperledger/ursa/pull/91/files#diff-49cadd47a44ba93f412f87ba4cc2427fR105-R124).
To make the `*InPlace` traits object safe, the one generic parameter they previously used (`impl Buffer`) was switched to `dyn Buffer`. This adds some vtable dispatch overhead for manipulating the buffer, but hopefully it is still cheap compared to the overhead of cryptographic operations on the underlying data. That said, no …

aead: split Aead(Mut) from Aead(Mut)InPlace (fixes #70)

---

crypto-mac/src/lib.rs
digest/src/lib.rs

As discussed on #43, similar to the one in `digest`.

crypto-mac: add `impl_write!` macro

---

Cargo.lock
aead/Cargo.toml
block-cipher-trait/Cargo.toml
crypto-mac/Cargo.toml
digest/Cargo.toml
signature/Cargo.toml
signature/src/lib.rs
stream-cipher/Cargo.toml
universal-hash/Cargo.toml

This commit does an across-the-board version bump of all traits, since they've all been migrated (vicariously) to `generic-array` v0.14.
There's no intention of releasing them yet, and if I do release preleases they'll be as `-pre.0` and so forth. This just makes it clear what's presently on HEAD is very much SemVer incompatible with the current releases.
After this, I'll try updating the various repos which consume these traits to use the latest git versions of these crates before cutting a final release.

Bump all crates to `-pre` versions

---

block-cipher/src/dev.rs

These didn't get properly updated when the crate was renamed

block-cipher: fix test macros

---

block-cipher/src/dev.rs
block-cipher/src/lib.rs
stream-cipher/src/dev.rs

Re-exports blobby under the `dev` module in each crate, and updates the macros to use that.

block-cipher/stream-cipher: more dev fixes

---

Cargo.lock
crypto-mac/Cargo.toml

It seems it was previously bumped to v0.8.0:
https://github.com/RustCrypto/traits/commit/128e557120632b623f55356a539b1c9c991d6626
...but never released, so this bumps it back with the intent of releasing a v0.8.0.

crypto-mac: bump version to v0.8.0-pre

---

digest/src/dev.rs

This was broken in the 2018 edition upgrade.

digest: fix dev blobby re-export

---

crypto-mac/src/dev.rs

This was broken in the 2018 edition upgrade.

crypto-mac: fix dev blobby re-export

---

.github/workflows/aead.yml
.github/workflows/block-cipher.yml
.github/workflows/crypto-mac.yml
.github/workflows/digest.yml
.github/workflows/signature.yml
.github/workflows/stream-cipher.yml
.github/workflows/universal-hash.yml
Cargo.lock

This should eliminate redundantly specifying it on a per-job basis.

.github: use `defaults` to set `working-directory`

---

aead/src/lib.rs

They were using `*::NonceSize` instead of `*::TagSize`.

aead: fix `Tag` return values

---

stream-cipher/src/dev.rs

Uses `$crate::bench_sync` and `$crate::bench_async` to invoke them.

stream-cipher: use 2018 edition module syntax for `bench` macros

---

crypto-mac/src/dev.rs
crypto-mac/src/lib.rs
digest/README.md
digest/src/dev.rs
digest/src/digest.rs
digest/src/dyn_digest.rs
digest/src/lib.rs
signature/tests/signature_derive.rs
universal-hash/src/lib.rs

As discussed in #43, this adopts `finalize` naming, following the "Initialize-Update-Finalize" (IUF) interface naming scheme pervasive throughout cryptography and cryptographic API design.

Rename `*result*` methods to finalize (ala IUF)

---

.github/workflows/digest.yml
digest/Cargo.toml
digest/src/dyn_digest.rs
digest/src/lib.rs

Allows `DynDigest` and `*_vec` methods to function in `no_std` + `alloc` environments.

digest: add `alloc` feature

---

.github/workflows/stream-cipher.yml
Cargo.lock
stream-cipher/Cargo.toml
stream-cipher/src/dev.rs
stream-cipher/src/lib.rs

Support for instantiating a stream cipher from a block cipher

stream-cipher: add FromBlockCipher trait (fixes #32)

---

block-cipher/Cargo.toml
block-cipher/src/dev.rs
block-cipher/src/lib.rs
crypto-mac/Cargo.toml
crypto-mac/src/dev.rs
crypto-mac/src/lib.rs

Configures the `block-cipher` and `crypto-mac` crates to have `doc_cfg` about their cargo features.
Adds some additional comments.

block-cipher/crypto-mac: add doc_cfg + comments

---

Cargo.lock
block-cipher/CHANGELOG.md
block-cipher/Cargo.toml
stream-cipher/Cargo.toml

- Crate renamed from `block-cipher-trait` to `block-cipher` ([#139])
- Split `BlockCipher` initialization into  `NewBlockCipher` trait ([#132])
- Update to Rust 2018 edition ([#107])
- Bump `generic-array` dependency to v0.14 ([#95])
[#139]: https://github.com/RustCrypto/traits/issues/139
[#132]: https://github.com/RustCrypto/traits/issues/132
[#107]: https://github.com/RustCrypto/traits/issues/107
[#95]: https://github.com/RustCrypto/traits/pull/95

block-cipher v0.7.0

---

Cargo.lock
block-cipher/CHANGELOG.md
crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml

- `impl_write!` macro ([#134])
- Bump `generic-array` dependency to v0.14 ([#144])
- Split `Mac` initialization into `NewMac` trait ([#133])
- Rename `MacResult` => `Output`, `code` => `into_bytes` ([#114])
- Rename `Input::input` to `Update::update` ([#111])
- Update to 2018 edition ([#108])
- Bump `subtle` dependency from v1.0 to v2.0 ([#33])
[#144]: https://github.com/RustCrypto/traits/pull/95
[#134]: https://github.com/RustCrypto/traits/pull/134
[#133]: https://github.com/RustCrypto/traits/pull/133
[#114]: https://github.com/RustCrypto/traits/pull/114
[#111]: https://github.com/RustCrypto/traits/pull/111
[#108]: https://github.com/RustCrypto/traits/pull/108
[#33]: https://github.com/RustCrypto/traits/pull/33

crypto-mac v0.8.0

---

Cargo.lock
stream-cipher/CHANGELOG.md
stream-cipher/Cargo.toml

- `FromBlockCipher` trait ([#164])
- Update to 2018 edition ([#110])
- Bump `generic-array` dependency to v0.14 ([#95])
[#164]: https://github.com/RustCrypto/traits/issues/164
[#110]: https://github.com/RustCrypto/traits/issues/110
[#95]: https://github.com/RustCrypto/traits/pull/95

stream-cipher v0.4.0

---

Cargo.lock
universal-hash/CHANGELOG.md
universal-hash/Cargo.toml

- `Key` and `Block` type aliases ([#128])
- Split `UniversalHash` initialization into `NewUniversalHash` trait ([#135])
- Rename `update_block` => `update` ([#129])
- Bump `generic-array` dependency to v0.14 ([#95])
[#135]: https://github.com/RustCrypto/traits/pull/135
[#129]: https://github.com/RustCrypto/traits/pull/129
[#128]: https://github.com/RustCrypto/traits/pull/128
[#95]: https://github.com/RustCrypto/traits/pull/95

universal-hash v0.4.0

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml

- Type aliases for `Key`, `Nonce`, and `Tag` ([#125])
- Optional `std` feature ([#63])
- `NewAead` now borrows the key ([#124])
- Split `Aead`/`AeadMut` into `AeadInPlace`/`AeadMutInPlace` ([#120])
- Bump `generic-array` dependency to v0.14 ([#95])
[#125]: https://github.com/RustCrypto/traits/pull/125
[#124]: https://github.com/RustCrypto/traits/pull/124
[#120]: https://github.com/RustCrypto/traits/pull/120
[#95]: https://github.com/RustCrypto/traits/pull/95
[#63]: https://github.com/RustCrypto/traits/pull/63

aead v0.3.0

---

digest/src/lib.rs

...gated under the `alloc` feature.
Allocates a `Vec<u8>` to return an individual `XofReader::read` invocation into.
Unlike `ExtensibleOutput::finalize_vec`, it doesn't consume the reader and can be called an unlimited number of times.

digest: add XofReader::read_vec method

---

block-cipher/src/lib.rs

Adds a stateful equivalent to `BlockCipher` that permits `&mut self` access to the underlying type.
The main use case for this trait is hardware cryptographic accelerators which need to e.g. communitate with a peripheral device via an underlying `&mut` reference.
While it's possible to use some underlying logic to use the existing `BlockCipher` trait in such a scenario, the solutions are somewhat ugly. Here is a real-world example:
https://github.com/iqlusioninc/usbarmory.rs/blob/develop/firmware/usbarmory/src/dcp/aes128.rs#L198-L236
The idea with `BlockCipherMut` would be to alternatively provide `AeadMut`/`AeadMutInPlace` for AEAD modes with an underlying `BlockCipherMut` (when possible).

block-cipher: add BlockCipherMut

---

digest/src/dyn_digest.rs
digest/src/lib.rs

Closes https://github.com/RustCrypto/hashes/issues/86
~~Replaces the `Reset` trait with a set of `_reset` methods on all of the various traits, and uses these as the default impl for the methods which consume hashers.~~
~~Also adds a set of methods to `FixedOutput` (`finalize_fixed_into*`) which eliminate copies by accepting an existing buffer as an argument.~~
Adds a `FixedOutputDirty` trait which writes the digest output to a provided byte array, but does not reset the internal state. This is intended for implementations to use in order to ensure that they are not reset in the event the instance is consumed.
Also adds a set of `finalize_into` and `finalize_into_reset` methods to `FixedOutput` whhich also write their input into a provided byte array, and changes the existing …

digest: add `FixedOutputDirty` trait + `finalize_into*`

---

digest/src/lib.rs

For consistency with the `DynDigest` trait.

Use boxed slices instead of vectors

---

digest/src/lib.rs

Adds traits which provide an implementation-focused low-level API similar to the `FixedOutputDirty` trait introduced in #180, but for the `ExtendableOutput` and `VariableOutput` traits.
Like `FixedOutputDirty`, these traits have blanket impls when the same type also impls the `Reset` trait.
Also adds corresponding `*_reset` methods to the respective `finalize*` methods of these traits.

digest: add `ExtendableOutputDirty` and `VariableOutputDirty` traits

---

digest/src/fixed.rs
digest/src/lib.rs
digest/src/variable.rs
digest/src/xof.rs

The new `*Dirty` traits add another level of organization to the crate's design. This commit updates the documentation to reflect that.
Rendered:

digest: document three levels of organization

---

Cargo.lock
digest/CHANGELOG.md
digest/Cargo.toml
signature/Cargo.toml

- `ExtendableOutputDirty` and `VariableOutputDirty` traits ([#183])
- `FixedOutputDirty` trait + `finalize_into*` ([#180])
- `XofReader::read_boxed` method ([#178], [#181], [#182])
- `alloc` feature ([#163])
- Re-export `typenum::consts` as `consts` ([#123])
- `Output` type alias ([#115])
- Rename `*result*` methods to `finalize` ala IUF ([#161])
- Use `impl AsRef<[u8]>` instead of generic params on methods ([#112])
- Rename `Input::input` to `Update::update` ala IUF ([#111])
- Upgrade to Rust 2018 edition ([#109])
- Bump `generic-array` to v0.14 ([#95])
[#183]: https://github.com/RustCrypto/traits/pull/183
[#181]: https://github.com/RustCrypto/traits/pull/181
[#182]: https://github.com/RustCrypto/traits/pull/182
[#180]: https://github.com/RustCrypto/traits/pull/180
[#178]: …

digest v0.9.0

---

.github/workflows/signature.yml
Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs
signature/tests/signature_derive.rs

- Upgrade `digest` to v0.9; MSRV 1.41+ ([#186])
[#186]: https://github.com/RustCrypto/traits/pull/186

signature v1.1.0

---

Cargo.lock
block-cipher/CHANGELOG.md
block-cipher/Cargo.toml

- `BlockCipherMut` trait ([#179])
[#179]: https://github.com/RustCrypto/traits/issues/179

block-cipher v0.7.1

---

Cargo.lock
stream-cipher/CHANGELOG.md
stream-cipher/Cargo.toml

- `Key` and `Nonce` type aliases ([#188])
[#188]: https://github.com/RustCrypto/traits/issues/188

stream-cipher v0.4.1

---

aead/src/lib.rs

Adds a method which accepts a slice for a key, similar to the methods in the `block-cipher` and `stream-cipher` crates.

aead: add `NewAead::new_varkey` method

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml

- `NewAead::new_varkey` method ([#191])
[#191]: https://github.com/RustCrypto/traits/pull/191

aead v0.3.1

---

.github/workflows/cryptography.yml
Cargo.lock
Cargo.toml
README.md
cryptography/Cargo.toml
cryptography/LICENSE-APACHE
cryptography/LICENSE-MIT
cryptography/README.md
cryptography/src/lib.rs

I've been given ownership of the [`cryptography`](https://crates.io/crates/cryptography) crate! 🎉 
This PR contains my suggested usage of it. If this sounds useful, I'll add @RustCrypto/traits as an owner.
---
Adds a `cryptography` crate which re-exports compatible versions of the other trait crates as a facade.
This should simplify cases where it's necessary to combine several cryptographic algorithms, by ensuring you have a single import to get compatible versions.

`cryptography` facade crate

---

cryptography/src/lib.rs

For whatever reason https://docs.rs did not render the links to the various trait crates (despite `cargo +nightly doc` rendering them fine for me).
https://docs.rs/cryptography/0.1.1/cryptography/
Even stranger still, there was one exception: it was happy with the `signature` crate (possibly because it's post-1.0?)
Regardless, this commit adds direct links for the various crates to https://docs.rs so users can easily find the relevant documentation.

cryptography: add explicit rustdoc links

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- Rustdoc link rendering for https://docs.rs ([#200]) 
[#200]: https://github.com/RustCrypto/traits/pull/200

cryptography v0.1.2

---

cryptography/src/lib.rs

Unfortunately even after #200 the links to the documentation for the various trait crates is still broken in the exact same way:
https://docs.rs/cryptography/0.1.2/cryptography/
I suspect this might be some kind of rustdoc/docs.rs bug around re-exports.
This commit explicitly links to https://docs.rs for each of the crates rather than using *any* kind of indirection, in hopes that corrects the issue.

cryptography: fix rustdoc by linking directly to https://docs.rs

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- Link rendering on https://docs.rs ([#202]) 
[#202]: https://github.com/RustCrypto/traits/pull/202

cryptography v0.1.3

---

.github/workflows/cryptography.yml
cryptography/Cargo.toml
cryptography/src/lib.rs

Imports `crypto-mac` as `mac` via a `package` directive in Cargo.toml rather than re-exporting it under another name.
Reorganizes the rustdoc into a table which shows both the module name and associated Cargo feature.

cryptography: add `mac` feature; put docs in table

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- rustdoc improvements ([#205])
- `mac` feature ([#204])
[#205]: https://github.com/RustCrypto/traits/pull/205
[#204]: https://github.com/RustCrypto/traits/pull/204

cryptography v0.1.4

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml
aead/src/dev.rs
aead/src/lib.rs

I plan to use it for [`ccm`](RustCrypto/AEADs#174) and maybe later migrate `aes-gcm` tests as well (170 KB for a file with test code does not look great :smile: ).
I also could add a benchmark macro based on your Criterion-based benches.

Add dev module to the aead crate

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml
stream-cipher/CHANGELOG.md
stream-cipher/Cargo.toml
stream-cipher/src/lib.rs

This change is needed for RustCrypto/block-ciphers#134. GOST modes are somewhat peculiar  as they allow additional flexibility, thus breaking the assumption used in the `FromBlockCipher` trait. Additionally this PR improves the blanket impl by overwriting the `new_var` method.
Unfortunately it's a breaking change, so a minor release will be needed.

Add NonceSize to FromBlockCipher

---

Cargo.lock
block-cipher/Cargo.toml
block-cipher/src/dev.rs
block-cipher/src/lib.rs
cryptography/Cargo.toml
stream-cipher/Cargo.toml
stream-cipher/src/dev.rs
stream-cipher/src/lib.rs

Closes RustCrypto/MACs#47
IIUC strictly speaking these changes are not backwards compatible, since downstream crates may define their own trait implementations for references. I wonder if we can overlook it and release these changes under patch releases.
Unfortunately it's not possible to write `impl<Alg: BlockCipherMut> BlockCipherMut for &mut Alg { .. }`, since it potentially conflicts with `impl<Alg: BlockCipher> BlockCipherMut for Alg { .. }`. Same goes for `StreamCipher`, which conflicts with the `SyncStreamCipher` impl. I think it's impossible to solve this problem without negative trait bounds, which are not even on horizon. Specialization may help, but I failed to make it work.

Add blanket trait impls for references

---

.github/workflows/elliptic-curve.yml
Cargo.lock
Cargo.toml
README.md
cryptography/Cargo.toml
cryptography/src/lib.rs
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/LICENSE-APACHE
elliptic-curve/LICENSE-MIT
elliptic-curve/README.md
elliptic-curve/src/error.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/curve.rs
elliptic-curve/src/weierstrass/point.rs
elliptic-curve/src/weierstrass/public_key.rs

As proposed in https://github.com/RustCrypto/elliptic-curves/issues/71, this PR imports the code for the `elliptic-curve` crate previously located at:
https://github.com/RustCrypto/elliptic-curves/tree/359f16dc9479bd27ef4d506aaf44b16f5945f718/elliptic-curve-crate
Latest release is `v0.4.0`

elliptic-curve: import from RustCrypto/elliptic-curves (359f16d)

---

Cargo.lock
elliptic-curve/Cargo.toml

elliptic-curve: remove dev-dependency on `hex`

---

Cargo.lock
cryptography/Cargo.toml
elliptic-curve/Cargo.toml

This commit isn't intended to be a release, but just bumps the version number in Cargo.toml to a `-pre` to distinguish it from the currently released v0.4.0.
Several backwards incompatible / semver breaking changes have been introduced since the release.

elliptic-curve: bump version to v0.5.0-pre

---

elliptic-curve/src/weierstrass/curve.rs

Several potentially useful traits (including the ECDSA ones) need access to these types, so it's helpful to have a single trait that defines them as associated types.
Some additional bounds would really be helpful, but we can add those as they come up in practice.

elliptic-curve: add `Arithmetic` trait

---

elliptic-curve/src/lib.rs

Trait for randomly generating types using a `rand_core::CryptoRng`.
Potentially useful in trait bounds that need to generate e.g. `Scalar` types.

elliptic-curve: add `Generate` trait

---

elliptic-curve/src/weierstrass.rs

Removes the reference requirement on the argument, since the `rand_core` traits are impl'd for reference types

elliptic-curve: simplify GenerateSecretKey signature

---

elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass.rs

Replaces the `GenerateSecretKey` trait with a conditionally implemented `SecretKey::generate` method, which leverages the new `Curve`, `Arithmetic`, and `Generate` traits.

elliptic-curve: add conditional `SecretKey::generate` method

---

elliptic-curve/src/weierstrass.rs

Fixes some unused import warnings overlooked in #224

elliptic-curve: fix warnings

---

elliptic-curve/src/secret_key.rs

This method fits the existing `Generate` trait.
This allows bounds to simply specify `where SecretKey<C>: Generate` to write code that needs to handle generic generation of secret keys, as opposed to trying to encode the full bounds for the impl.

elliptic-curve: impl Generate for SecretKey

---

elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/public_key.rs

Most of the previous bounds are now irrelevant, and it can now also leverage the `Arithmetic` trait for the `AffinePoint` definition.

elliptic-curve: simplify `FixedBaseScalarMul` trait

---

elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs

Add a trait for performing scalar/field inversions.
The main motivation for this is to allow for things like `BlindedScalar` type which use random blinding for either efficiency reasons (to allow a vartime inversion) and/or as a side-channel defense.

elliptic-curve: add `Invert` trait

---

elliptic-curve/src/lib.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/public_key.rs

These traits allow converting:
- SecretKey => Scalar
- PublicKey => AffinePoint
...in a curve-agnostic way.

elliptic-curve: add FromPublicKey/FromSecretKey traits

---

elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/public_key.rs

`FixedBaseScalarMul` was a hack around the lack of an associated `Scalar` type on a curve and generic way of converting a `SecretKey` to a `Scalar`.
We have both of those things, so this commit replaces it with an `ops::MulBase` trait intended to be impl'd on `Scalar` types.
Further, it bounds the `Arithmetic::Scalar` associated type on this, which allows it to be used for generic `SecretKey` -> `PublicKey` conversions.
It also means the `Arithmetic` trait now has a(n implicit) way of representing the generator point, making it genuinely useful for generic arithmetic operations. This would also be useful for e.g. a generic implementation of Diffie-Hellman.

elliptic-curve: replace FixedBaseScalarMul with ops::MulBase

---

signature/src/signer.rs

...replacing it with `impl CryptoRng + RngCore` parameter.
This is a SemVer breaking change, however per our policy around `*-preview` features, it will receive a minor version bump as these features are not part of the SemVer guarantees of this crate.
The rationale for this change is the exact RNG method doesn't matter, especially to the point it needs to be a generic parameter of the trait signature.

signature: remove RNG generic parameter from RandomizedSigner

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

- RNG generic parameter `R` from `RandomizedSigner` ([#231])
[#231]: https://github.com/RustCrypto/traits/pull/231

signature v1.2.0

---

elliptic-curve/src/lib.rs

Useful for conditionally zeroizing long-lived secret `Scalar` values

elliptic-curve: re-export `zeroize`

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

#232 did not properly include the changes from #231. Looks like Squash + Merge incorporated them, but I published off the branch (which I tend to do in case the branch contains something that would be rejected by the crates.io API).
This republishes it with the changes correctly included, after which I'll yank v1.2.0.

signature v1.2.1

---

signature/src/signer.rs

Combination of `DigestSigner` and `RandomizedSigner` which computes a signature over a message digest while incorporating additional entropy.

signature: add RandomizedDigestSigner

---

elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/weierstrass/public_key.rs

This makes the `MulBase` trait a static method for point types, which takes an associated scalar type as an associated parameter.
This allows multiple impls on both `AffinePoint` and `ProjectivePoint`.

elliptic-curve: change MulBase trait to be impl'd on point types

---

elliptic-curve/src/lib.rs
elliptic-curve/src/oid.rs

Adds a (very simple, const-and-no_std-friendly) `ObjectIdentifier` type and an `Identifier` trait for attaching an OID to a curve.
No validation of the nodes is presently performed (and since it's impl'd as a `const fn`, it'd require a MSRV bump to do so). Also requires the OID be specified as an array literal: no parsing is supported for either string or binary-encoded OIDs.
Only string serialization is supported for now (via `Display`). A `no_std`-friendly binary serializer will be somewhat tricky.

elliptic-curve: basic OID support

---

elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/point.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/weierstrass/public_key.rs

Adds a `NonZeroScalar` type generic over curves along with a `Generator` trait which together with the `Mul` trait from `core` can replace the `MulBase` trait.
`NonZeroScalar` is able to use the bounds on `Arithmetic::Scalar` and therefore usable anywhere a `Scalar` otherwise would, but with the guarantee that multiplication by an `AffinePoint` will not result in the point at infinity, for which no `AffinePoint` representation is possible given current trait bounds/implementations.
cc @fjarri

elliptic-curve: NonZeroScalar + Generator (replaces MulBase)

---

elliptic-curve/src/weierstrass/point.rs
elliptic-curve/src/weierstrass/public_key.rs

Generic point compression support for SEC-1 encoded public keys

elliptic-curve: add weierstrass::PublicKey::compress

---

elliptic-curve/src/secret_key.rs

SecretKey is auto-zeroizing. While cloning it isn't ideal, we have a strategy for automatically cleaning up afterward.
Cloning SecretKey came up in practice in the `k256` crate (PR forthcoming).

elliptic-curve: derive Clone on SecretKey

---

elliptic-curve/src/lib.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass/point.rs

This type alias is being used for things that aren't elements of the scalar field, like serialized affine coordinates.
This commit renames it into something more general which applies to these cases. It's also more consistent with the `Curve::ElementSize` associated type name.

elliptic-curve: rename `ScalarBytes` => `ElementBytes`

---

elliptic-curve/src/encoding.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/public_key.rs

Replaces the previous `FromPublicKey` and `FromSecretKey` traits with a more general `FromBytes` and `ToBytes` traits.
These match the function signatures presently used in the existing crates, and are useful in cases where e.g. a scalar doesn't necessarily represent a secret (such as in ECDSA).

elliptic-curve: add `encoding` module

---

elliptic-curve/src/weierstrass/public_key.rs

It seems this was a bit too hastily removed in #247. It's worth keeping around for now as it handles the variable sizes of SEC-1 keys.

elliptic-curve: add back FromPublicKey trait

---

elliptic-curve/src/lib.rs

Supports generic scalar serialization

elliptic-curve: add Into<ElementBytes> bound to Arithmetic::Scalar

---

elliptic-curve/Cargo.toml
elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass.rs
elliptic-curve/src/weierstrass/point.rs
elliptic-curve/src/weierstrass/public_key.rs

Adds an `ecdh` module gated under an `ecdh` Cargo feature containing a generic high-level interface for performing ephemeral Elliptic Curve Diffie-Hellman key exchanges.
The API is inspired by the one in `x25519-dalek`.

elliptic-curve: Elliptic Curve Diffie-Hellman support

---

Cargo.lock
cryptography/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `Arithmetic` trait ([#219])
- `Generate` trait ([#220], [#226])
- Toplevel `Curve` trait ([#223])
- `Invert` trait ([#228])
- `FromPublicKey` trait ([#229], [#248])
- Re-export `zeroize` ([#233])
- OID support ([#240], [#245])
- `NonZeroScalar` type ([#241])
- `Generator` trait ([#241])
- `weierstrass::PublicKey::compress` method ([#243])
- Derive `Clone` on `SecretKey` ([#244])
- Generic Elliptic Curve Diffie-Hellman support ([#251])
- Moved repo to https://github.com/RustCrypto/traits ([#213])
- Rename `ScalarBytes` to `ElementBytes` ([#246])
- Rename `CompressedCurvePoint`/`UncompressedCurvePoint` to `CompressedPoint`/`UncompressedPoint`
[#213]: https://github.com/RustCrypto/traits/pull/213
[#219]: https://github.com/RustCrypto/traits/pull/219
[#220]: …

elliptic-curve v0.5.0

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- `elliptic-curve` feature ([#213])
- Bump `crypto-mac` to v0.9 ([#217])
[#213]: https://github.com/RustCrypto/traits/pull/213
[#217]: https://github.com/RustCrypto/traits/pull/217

cryptography v0.3.0

---

cryptography/src/lib.rs

Previously used a hyphen instead of an underscore

cryptography: fix rustdoc for `elliptic_curve` re-export

---

Cargo.lock
crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs

This will allow us to remove explicit dependency on `block-cipher` from `cmac`, `daa` and `pmac` crates, thus making version synchronization a bit easier.

crypto-mac: re-export block-cipher

---

.github/workflows/elliptic-curve.yml
elliptic-curve/src/sec1.rs

This was causing compile errors when only the `weierstrass` feature was enabled.

elliptic-curve: don't conditionally define `EncodedPoint::x`

---

Cargo.lock
cryptography/Cargo.toml
stream-cipher/CHANGELOG.md
stream-cipher/Cargo.toml
stream-cipher/src/dev.rs
stream-cipher/src/errors.rs
stream-cipher/src/lib.rs

Closes: RustCrypto/stream-ciphers#9
Unfortunately I forgot about this issue during the work on `stream-cipher` v0.6.
I wonder if it'll be worth to go even further and introduce something like this:
```rust
pub trait SyncStreamCipherSeek<T: num_traits::Unsigned = u64> {
fn get_pos(&self) -> T {
self.try_get_pos().unwrap()
}
fn try_get_pos(&self) -> Result<T, OverflowError>;
fn seek(&mut self, pos: T) {
self.try_seek(pos).unwrap()
}
fn try_seek(&mut self, pos: T) -> Result<(), LoopError>;
}
```
cc @kazcw

stream-cipher: add SyncStreamCipherSeek::try_seek method

---

Cargo.lock
stream-cipher/CHANGELOG.md
stream-cipher/Cargo.toml
stream-cipher/src/lib.rs

The method was written in assumption that `bs` (block size) is power of two, but unfortunately I forgot that some modes in `gost-modes` have parameter `S`, which allows to change effective block size at will.

Fix SeekNum::to_block_byte computation

---

elliptic-curve/src/weierstrass/point.rs

Replaces boolean flag for y-coordinate even/odd with subtle::Choice

elliptic-curve: make weierstrass::point::Decode constant time

---

elliptic-curve/src/sec1.rs

These are helpful when implementing SEC1 point decoding

elliptic-curve: expose SEC1 Tag and coordinates

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/scalar.rs

Provides a more direct path from serialized bytes to a NonZeroScalar.

elliptic-curve: impl FromBytes on NonZeroScalar

---

elliptic-curve/src/sec1.rs

Generic support for decompressing SEC1-encoded points

elliptic-curve: add EncodedPoint::decompress

---

elliptic-curve/src/scalar.rs

...and a `From` conversion to `ElementBytes<C>`

elliptic-curve: add NonZeroScalar::to_bytes

---

elliptic-curve/src/scalar.rs

...if the underlying scalar type it wraps also impls `Invert`

elliptic-curve: conditionally impl Invert for NonZeroScalar

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

This is needed in a generic implementation of RFC 6979, but is also potentially useful for things like hash-to-curve.

elliptic-curve: add `digest` feature and FromDigest trait

---

Cargo.lock
elliptic-curve/Cargo.toml

This makes it incompatible with `signature` when fetched via git, which does not have such a declaration (and cannot, as it'd break the dev-dependency on `sha2`).

elliptic-curve: remove `digest` crate path directive

---

elliptic-curve/src/lib.rs
elliptic-curve/src/util.rs

These are helper functions for performing arithmetic on field element "limbs", e.g. implementing carry chains.
The particular versions in this file come from the `k256`, which started as a fork of the `p256` crate, and notably provide 32-bit and 64-bit versions of the same functions.
These are potentially helpful to have in the `elliptic-curve` crate for several reasons, most notably for testing things which are generic across elliptic curves without having to provide a full curve arithmetic implementation.
Also having things in one place is nice, and potentially we can use these to provide a generic baseline implementation of certain types of curve arithmetic for curves that don't provide their own arithmetic.
cc @str4d who I had talked to about this at one point.

elliptic-curve: import arithmetic helper functions

---

elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs

This is hopefully a more apt description of this particular size.

Rename C::ElementSize => FieldSize

---

elliptic-curve/src/point.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/weierstrass.rs

Move point compression defaults onto their own trait

elliptic-curve: extract point::Compression trait

---

elliptic-curve/src/lib.rs

Ensures that the output of a scalar multiplication with an affine point is also an affine point.

elliptic-curve: ensure C::AffinePoint Mul<Output=Self::AffinePoint>

---

.github/workflows/elliptic-curve.yml
Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/secret_key.rs

Adds the `ff` and `group` crates as dependencies, with the goal of replacing some of the existing traits and trait relationships in `elliptic-curve` with ones from `ff`/`group`.
This PR also removes the `rand` and `weierstrass` features from the `elliptic-curve` crate, making `rand_core` a hard requirement, since it seems at least `rand_core` will probably be a hard requirement for `group`, and requiring an RNG as a hard dependency makes sense.

elliptic-curve: add `ff` and `group` crate dependencies

---

Cargo.lock
elliptic-curve/Cargo.toml

This version has the following extremely useful impls:
- `From<CtOption> for Option`
- `ConstantTimeEq` for `Choice`
There is a bunch of code in `RustCrypto/elliptic-curve` that can be cleaned up/simplified assuming these are available.

elliptic-curve: bump minimum subtle version to 2.3

---

elliptic-curve/src/lib.rs

Adds the following:
- `Arithmetic::ProjectivePoint` associated type with `group::Curve` and `group::Group` bounds
- `Arithmetic::Scalar` is now bounded by `ff::PrimeField`

elliptic-curve: add `ff` and `group` bounds on Arithmetic trait

---

.github/workflows/elliptic-curve.yml
Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs

This crate now has a large(r) number of dependencies via the `ff` and `group` crates (notably the recently introduced `bitvec` and its transitive dependencies).
This commit adds an `arithmetic` feature and gates related functionality under it, along with the `ff` and `group` crate dependencies.
This ensures these dependencies (and their transitive dependencies) can be excluded when the `arithmetic` features of elliptic curve implementations are non-existent or an associated feature disabled.

elliptic-curve: add `arithmetic` feature

---

elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs

This is a property of the scalar field specifically and importantly retains layout/properties of the internal scalar field representation.

elliptic-curve: rename FieldBits to ScalarBits

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/secret_key.rs

The functionality it previously provided as a trait is now available via methods like `Field::random` and `Group::random`.
The other places where it was being used have been converted to inherent methods on concrete types, which is easier to use because there's no need to import a trait.

elliptic-curve: remove `Generate` trait

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass/point.rs

Makes it clearer this refers to a field element.
Alternative to #288.

elliptic-curve: rename ElementBytes => FieldBytes

---

.github/workflows/elliptic-curve.yml
elliptic-curve/src/lib.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs

Makes `SecretKey<C>` a generic wrapper for an inner zeroizable type, with a blanket impl for curves with an arithmetic backend which uses `NonZeroScalar<C>`.

elliptic-curve: make SecretKey<C> inner type generic

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/weierstrass/point.rs

Renames the `Arithmetic` trait to `ProjectiveArithmetic` and changes it to have only a single associated type: `ProjectivePoint`.
Adds `AffinePoint<C>` and `Scalar<C>` type aliases which are able to look up the corresponding associated type chain (along with `ProjectivePoint<C>` for consistency, although this is available as `<C as ProjectiveArithmetic>::ProjectivePoint`).

elliptic-curve: refactor ProjectiveArithmetic trait

---

Cargo.lock
cryptography/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `arithmetic` feature ([#293])
- Generic curve/field arithmetic using the `ff` and `group` crates ([#287], [#291], [#292])
- `sec1::Coordinates` ([#286])
- `weierstrass::point::Compression` trait ([#283], [#300])
- Arithmetic helper functions ([#281])
- `digest` feature and `FromDigest` trait ([#279])
- impl `Deref` for `NonZeroScalar` ([#278])
- Conditionally impl `Invert` for `NonZeroScalar` ([#277])
- `NonZeroScalar::to_bytes` ([#276])
- `EncodedPoint::decompress` ([#275])
- `sec1::Tag` ([#270])
- `weierstrass::point::Decompress` trait ([#266])
- `alloc` feature + `EncodedPoint::to_bytes()` ([#265])
- Renamed `Arithmetic` trait to `point::ProjectiveArithmetic` ([#300])
- Replaced `Arithmetic::Scalar` and `Arithmetic::AffinePoint` with `Scalar<C>` and `AffinePoint<C>` ([#300])
- Made …

elliptic-curve v0.6.0

---

Cargo.lock
elliptic-curve/Cargo.toml

This reverts commit b541170e97553891833a4359ea1c27576e0a2b4d.
This needs to be upgraded in coordination with the `ff` and `group` crates, so this reverts it back to what the current releases of those crates are presently using.

Revert "build(deps): bump bitvec from 0.18.3 to 0.19.0 (#301)"

---

elliptic-curve/src/sec1.rs

This method was previously expecting `Decompress` and `ToEncodedPoint` impls on `Scalar`, rather than `AffinePoint`.
This updates it to use the correct types.

elliptic-curve: fix `sec1::EncodedPoint::decompress`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `sec1::EncodedPoint::decompress` ([#309])
[#309]: https://github.com/RustCrypto/traits/pull/309

elliptic-curve v0.6.1

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `sec1::EncodedPoint::to_untagged_bytes()` method ([#312])
[#312]: https://github.com/RustCrypto/traits/pull/312

elliptic-curve v0.6.2

---

Cargo.lock
cryptography/CHANGELOG.md
cryptography/Cargo.toml

- Bump `signature` dependency to 1.2.0 ([#314])
- Bump `elliptic-curve` dependency to 0.6 ([#302])
- Bump `stream-cipher` dependency to 0.7 ([#260])
[#314]: https://github.com/RustCrypto/traits/pull/314
[#302]: https://github.com/RustCrypto/traits/pull/302
[#260]: https://github.com/RustCrypto/traits/pull/260

cryptography v0.4

---

.github/workflows/cryptography.yml
cryptography/Cargo.toml

Adds an off-by-default `std` feature which activates the `std` features of all of the other dependencies.
This is a somewhat lousy way of doing this, and I wish that there were a better approach, so much that I posted a Pre-Pre-RFC about it:
https://internals.rust-lang.org/t/pre-pre-rfc-weak-cargo-feature-activation/13141
Edit: seems there's an open issue about this already:
https://github.com/rust-lang/cargo/issues/3494
For now though, this is immediately useful to me.

cryptography: add `std` feature

---

.github/workflows/async-signature.yml
Cargo.lock
Cargo.toml
README.md
signature/async/CHANGELOG.md
signature/async/Cargo.toml
signature/async/README.md
signature/async/src/lib.rs
signature/src/lib.rs
signature/src/signer.rs
signature/src/verifier.rs

Adds an `async-signature` crate with `AsyncSigner` and `AsyncDigestSigner` traits, based on the `async-trait` crate.
Though we'd discussed not using an `async-trait`-based approach (#304), there are some immediate needs for these traits for `std` users, namely providing a common `async` API to things like Cloud KMS services and NetHSMs.
I think we can still pursue nightly-only versions of these traits in the `signature` crate itself (ones which will work in `no_std` environments).
In the meantime, these traits are self-contained within their own, relatively small crate to unblock making some initial progress with things like Cloud KMS abstractions.

async-signature: initial crate

---

elliptic-curve/src/secret_key.rs

The `SecretValue` trait was supposed to allow curve crates with an `arithmetic` feature to use a `NonZeroScalar` as their secret value, and crates which don't to use `FieldBytes`.
Unfortunately `zeroize` has no `generic-array` integration, and therefore `GenericArray` (which is what `FieldBytes` is a type alias for) cannot directly be used as `SecretValue::Secret`.
This commit adds a thin `SecretBytes` newtype which wraps `FieldBytes` and impls `Zeroize` so it can be used as `SecretValue::Secret`.

elliptic-curve: add SecretBytes newtype

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `SecretBytes` newtype ([#324])
[#324]: https://github.com/RustCrypto/traits/pull/324

elliptic-curve v0.6.3

---

elliptic-curve/src/secret_key.rs

This is needed to fulfill the trait bounds for `SecretValue`

elliptic-curve: impl From<SecretBytes> for FieldBytes

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Impl `From<SecretBytes<C>>` for `FieldBytes<C>` ([#326])
[#326]: https://github.com/RustCrypto/traits/pull/326

elliptic-curve v0.6.4

---

elliptic-curve/src/ecdh.rs

The `elliptic-curve` crate no longer builds on `nightly`.
Possible cause:
https://github.com/rust-lang/rust/issues/77638
Unfortunately this means rustdoc builds on https://docs.rs fail!
This commit works around the issue.

elliptic-curve: work around nightly-2020-10-06 breakage

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Work around `nightly-2020-10-06` breakage ([#328])
[#328]: https://github.com/RustCrypto/traits/pull/328

elliptic-curve v0.6.5

---

elliptic-curve/src/secret_key.rs

This is needed by the `elliptic_curve::SecretKey::to_bytes` method.

elliptic-curve: derive `Clone` on `SecretBytes`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Derive `Clone` on `SecretBytes` ([#330])
[#300]: https://github.com/RustCrypto/traits/pull/300

elliptic-curve v0.6.6

---

Cargo.lock
cryptography/Cargo.toml
stream-cipher/Cargo.toml
stream-cipher/src/lib.rs

Note: breaking change.
As far as I can tell this was an oversight: `FromBlockCipher` never needs to instantiate a new block cipher (isn't that the point?), making this bound needlessly limiting.
The rationale for it in the first place appears to be for the blanket impl of `NewStreamCipher` for `C: FromBlockCipher` which needs it, but we can add the bound to the blanket impl, rather than (needlessly) sticking it on the trait.

stream-cipher: remove NewBlockCipher bound on FromBlockCipher

---

stream-cipher/CHANGELOG.md

Cutting a prerelease to simplify https://github.com/RustCrypto/stream-ciphers/pull/170 and its transitive integration into `aes-gcm` and `aes-gcm-siv`.
- `FromBlockCipherMut` trait ([#334])
- `NewBlockCipher` bound on `FromBlockCipher` ([#333])
[#334]: https://github.com/RustCrypto/traits/pull/334
[#333]: https://github.com/RustCrypto/traits/pull/333

stream-cipher v0.8.0-pre

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml
crypto-mac/Cargo.toml
cryptography/Cargo.toml

- Unify `block-cipher` and `stream-cipher` into `cipher` ([#337])
[#337]: https://github.com/RustCrypto/traits/pull/337

cipher v0.2.0

---

Cargo.lock
crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml
cryptography/Cargo.toml

- Replace `block-cipher` crate with new `cipher` crate ([#337], [#338])
[#338]: https://github.com/RustCrypto/traits/pull/338
[#337]: https://github.com/RustCrypto/traits/pull/337

crypto-mac v0.10.0

---

cryptography/CHANGELOG.md

- Bump `crypto-mac` to v0.10 ([#339])
- Unify `block-cipher`/`stream-cipher` into `cipher` ([#337], [#338])
[#339]: https://github.com/RustCrypto/traits/pull/339
[#338]: https://github.com/RustCrypto/traits/pull/338
[#337]: https://github.com/RustCrypto/traits/pull/337

cryptography v0.5.0

---

cipher/src/block.rs
cipher/src/lib.rs
cipher/src/stream.rs

...along with `typenum::consts`
Failure to do this was an oversight: it doesn't really make sense to re-export these twice from both the `block` and `stream` modules.
That said, `cipher` v0.2 is already shipped, and it does ease a sed-based migration to keep these re-exports for now.
This commit adds a third re-export from the toplevel, and comments to remove the re-exports from the `block` and `stream` crates. This should happen before `cipher` v0.3 is released.

cipher: re-export `generic_array` from toplevel

---

cipher/src/block/dev.rs
cipher/src/stream/dev.rs

They were previously referring to the old `block_cipher` and `stream_cipher` names.

cipher: fix dev macro imports

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml

- Re-export `generic_array` from toplevel ([#343])
- `dev` macro imports ([#345])
[#343]: https://github.com/RustCrypto/traits/pull/343
[#345]: https://github.com/RustCrypto/traits/pull/345

cipher v0.2.1

---

cipher/README.md
cipher/src/block/dev.rs
cipher/src/lib.rs
cipher/src/stream/dev.rs

The old macro names come from the `block-cipher` and `stream-cipher` crates, where the crate names disambiguated them.
However, now that they've been merged into the same crate, and being re-exported from the toplevel as macros are, it's now unclear whether a macro is for a block cipher or a stream cipher.
This commit adds `block_cipher*` and `stream_cipher*` to the start of each macro name to disambiguate them.
It also maintains the existing macros as wrappers for the new names for backwards compatibility, but with a `#[deprecated]` attribute added.

cipher: revamp macro names

---

cipher/src/block.rs

Partially addresses #332.
Adds methods which work over an arbitrarily sized slice of blocks to encrypt/decrypt.
Provides a default implementation, but can be potentially further optimized by individual implementations.

cipher: add BlockCipher::{encrypt_slice, decrypt_slice}

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml

- `BlockCipher::{encrypt_slice, decrypt_slice}` methods ([#351])
- Add `block_cipher_*` and `stream_cipher_*` prefixed macros ([#350])
- Deprecate non-prefixed macros ([#350])
[#351]: https://github.com/RustCrypto/traits/pull/351
[#350]: https://github.com/RustCrypto/traits/pull/350

cipher v0.2.2

---

cipher/src/block/dev.rs
cipher/src/stream/dev.rs

They weren't using `$crate::*`, and therefore the resulting code doesn't compile.

cipher: fix legacy macro wrappers

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml

- Legacy macro wrappers ([#356])
[#356]: https://github.com/RustCrypto/traits/pull/356

cipher v0.2.3

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml

- Macro expansion error ([#358])
[#358]: https://github.com/RustCrypto/traits/pull/358

cipher v0.2.4

---

cipher/src/stream/dev.rs

The new macro names were still invoking the old deprecated ones

cipher: fix nested macro usage

---

Cargo.lock
cipher/CHANGELOG.md
cipher/Cargo.toml

- Nested macros used old deprecated names ([#360])
[#360]: https://github.com/RustCrypto/traits/pull/360

cipher v0.2.5

---

elliptic-curve/src/ecdh.rs

It was using the wrong quote (normal apostrophe instead of backtick).

elliptic-curve: fix `ecdh` rustdoc

---

.github/workflows/elliptic-curve.yml
Cargo.lock
cryptography/Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/README.md
elliptic-curve/src/lib.rs

As MSRV bump is considered a breaking change; this also bumps the Cargo.toml version to v0.7.0-pre.
This version of `const-oid` uses the new `const fn` features to provide some basic OID validation.
While this alone may be a silly reason to bump MSRV to 1.46+, many of the elliptic curve crates could also benefit from using `const fn` in a similar manner, so bumping MSRV is generally useful.

Bump `const-oid` to v0.2; MSRV 1.46+

---

elliptic-curve/src/ecdh.rs

This change, coupled with some changes in the `elliptic_curve` trait, should fix https://github.com/RustCrypto/elliptic-curves/issues/236
I know it's kinda messy, but this was the minimal solution I could come up with. It resembles `ecdsa::VerifyKey`

Made PublicKey a newtype that does point validation upon deserialization

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs

This PR refactors the `ecdh::PublicKey` type introduced in #363 into a toplevel `public_key::PublicKey` type which is generally useful anywhere a public key is required.
It additionally adds a number of additional impls including `AsRef`, `Deref`, and various `From`/`TryFrom` conversions.
It also promotes the `from_encoded_point` method into a proper impl of the `FromEncodedPoint` trait, leveraging a `TryFrom` impl instead as a more convenient API.
cc @rozbb

elliptic-curve: extract toplevel PublicKey; add functionality

---

Cargo.lock
cipher/Cargo.toml
cipher/src/block.rs
cipher/src/lib.rs
cipher/src/stream.rs
crypto-mac/Cargo.toml
crypto/Cargo.toml

Closes #349
Adds `BlockEncrypt` and `BlockDecrypt` traits which can be used in cases where e.g. only the encryption portion of a block cipher is used, as in CTR mode.
This PR does not otherwise attempt to add things like a blanket impl.

cipher: add encrypt/decrypt-only block cipher traits

---

elliptic-curve/src/public_key.rs
elliptic-curve/src/sec1.rs

Types with `Deref` impls shouldn't have inherent methods, however `PublicKey` has several.
This makes `PublicKey` more than a "smart pointer" type which `Deref` is intended to be used with: it handles encoding and conversions in a way that can be shared across curves.
It already provided an `AsRef` impl for obtaining the `AffinePoint`, however this PR also adds a new inherent `as_affine` method as well for convenience.

elliptic-curve: remove Deref impl from PublicKey; add ::as_affine()

---

elliptic-curve/src/secret_key.rs

Method for exposing the inner (generic) secret value for a SecretKey

elliptic-curve: add SecretKey::secret_value method

---

elliptic-curve/src/public_key.rs

This has better symmetry with `SecretKey::from_bytes`, and also leaves room to add additional public key encodings (e.g. SubjectPublicKeyInfo)

elliptic-curve: rename PublicKey::from_sec1_bytes

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs

Decouples `PublicKey` from SEC1 encoding-related concerns, which allows the trait bounds for anything which interacts with `PublicKey`s to be dramatically simplified.

elliptic-curve: simplify PublicKey trait bounds

---

elliptic-curve/src/public_key.rs

The derived impl appears to have the incorrect bounds

elliptic-curve: add explicit Copy impl for PublicKey

---

Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/ecdh.rs
elliptic-curve/src/error.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/secret_key.rs

Adds initial support for parsing PKCS#8-encoded ECC secret keys.
This is presently somewhat difficult to test within this crate (which should be addressed regardless) as it relies on generic parameters of a curve implementation, however this has been tested concretely against the `p256` crate which has tests that exercise it in this PR:
https://github.com/RustCrypto/elliptic-curves/pull/243

elliptic-curve: PKCS#8 support for `SecretKey`

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml

- Impl `pkcs8::FromPublicKey` for `PublicKey<C>` ([#385])
- Impl `pkcs8::FromPrivateKey` trait for `SecretKey<C>` ([#381], [#383])
- PKCS#8 PEM support ([#382])
- `SecretKey::secret_value()` method ([#375])
- `PublicKey<C>` type ([#363], [#366])
- Rename `PublicKey::from_bytes()` to `::from_sec1_bytes()` ([#376])
- `sec1::EncodedPoint` uses `Option` instead of `subtle::CtOption` ([#367])
- Bump `const-oid` to v0.3; MSRV 1.46+ ([#365], [#381])
- `ecdh` rustdoc ([#364])
[#385]: https://github.com/RustCrypto/traits/pull/385
[#383]: https://github.com/RustCrypto/traits/pull/383
[#382]: https://github.com/RustCrypto/traits/pull/382
[#381]: https://github.com/RustCrypto/traits/pull/381
[#376]: https://github.com/RustCrypto/traits/pull/376
[#375]: https://github.com/RustCrypto/traits/pull/375 …

elliptic-curve v0.7.0

---

elliptic-curve/src/secret_key.rs

...to only return `NonZeroScalar<C>` when the `arithmetic` feature is enabled and the curve impl's `ProjectiveArithmetic`.
Otherwise the `SecretValue::Secret` type is not intended to be part of the public API.

elliptic-curve: constrain `SecretKey::secret_value` exposure

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml

- Have `SecretKey::secret_value` always return `NonZeroScalar` ([#390])
[#390]: https://github.com/RustCrypto/traits/pull/390

elliptic-curve v0.7.1

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/sec1.rs

Closes #399.
The `ToEncodedPoint` trait is infallible. We can either make it fallible (as attempted in #400) or add support for the SEC1 encoding for the identity point.
This commit adds SEC1 support for identity, allowing `ToEncodedPoint` to remain infallible.
Unfortunately breaking as it requires adding new enum variants and some method signature changes.
However, that said, this should make the SEC1 implementation "complete" in that it implements the full `Elliptic-Curve-Point-to-Octet-String` encoding (and decoding).
cc @rozbb

elliptic-curve: add support for SEC1 identity encoding

---

elliptic-curve/src/secret_key.rs

The `NonZeroScalar` type upholds an invariant and makes it useful in more places than a `Scalar`.

elliptic-curve: have `SecretKey::secret_scalar` return `NonZeroScalar`

---

elliptic-curve/src/secret_key.rs

After #402, it duplicates `secret_scalar` and can therefore be removed.

elliptic-curve: remove `SecretKey::secret_value`

---

elliptic-curve/src/ecdh.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs

Adds an invariant to the `AffinePoint` wrapped by a `PublicKey` which ensures it is not the identity point.
This is notable now that we support SEC1 encoding of identity points (#401), as it might be unexpected to end users to receive public keys which encode the identity element.

elliptic-curve: ensure PublicKey is not the identity point

---

elliptic-curve/src/sec1.rs

Adds a convenience method for obtaining a SEC1-encoded identity point

elliptic-curve: add `sec1::EncodedPoint::identity()`

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Impl `subtle::ConditionallySelectable` for `sec1::EncodedPoint` ([#409])
- `sec1::EncodedPoint::identity()` method ([#408])
- `sec1::Coordinates::tag` method ([#407])
- Support for SEC1 identity encoding ([#401])
- Bump `pkcs8` crate dependency to v0.3 ([#405])
- Ensure `PublicKey<C>` is not the identity point ([#404])
- Have `SecretKey::secret_scalar` return `NonZeroScalar` ([#402])
- `SecretKey::secret_value` ([#403])
[#409]: https://github.com/RustCrypto/traits/pull/409
[#408]: https://github.com/RustCrypto/traits/pull/408
[#407]: https://github.com/RustCrypto/traits/pull/407
[#405]: https://github.com/RustCrypto/traits/pull/405
[#404]: https://github.com/RustCrypto/traits/pull/404
[#403]: https://github.com/RustCrypto/traits/pull/403
[#402]: …

elliptic-curve v0.8.0

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Builds on Rust `nightly` compiler ([#412])
[#412]: https://github.com/RustCrypto/traits/pull/412

elliptic-curve v0.8.1

---

elliptic-curve/src/public_key.rs

Make PublicKey::from_encoded_point go through PublicKey::from_affine

---

elliptic-curve/src/ecdh.rs

Adds an `elliptic_curve::ecdh::diffie_hellman()` function which operates on types which can be coerced to `NonZeroScalar` and `AffinePoint` for a particular elliptic curve, returning a `SharedSecret`
This function is an extraction of and used to implement ECDHE.
This function makes it possible to perform static ECDH exchanges, although the documentation recommends using ECDHE whenever possible.

elliptic-curve: low-level ECDH API

---

.github/workflows/elliptic-curve.yml
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs

There is presently no good way to test traits and types in this crate which depend on a concrete curve implementation.
This commit adds a `dev` module gated on an eponymous crate feature which provides a `MockCurve` type. This type does not provide a full curve arithmetic implementation (most methods are stubbed out using `unimplemented!`), but rather implements the full set of traits used in the bounds of traits defined in the `elliptic-curve` crate.
This type is actually an extraction from the `ecdsa` trait, where similar testing problems were previously encountered. However, now that there's a `dev` module, the `ecdsa` crate can now use it!

elliptic-curve: `dev` module with `MockCurve` type

---

elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/public_key.rs

The invariant of `PublicKey` is that the inner affine point is *NOT* the identity, however there was a bug in the `FromEncodedPoint` implementation which was fixed in #416.
However, at the time we couldn't add a regression test because there was no concrete curve type to use for writing such a test.
A `MockCurve` was added in #419, so this commit uses it to write such a regression test.

elliptic-curve: regression test for PublicKey::from_encoded_point

---

Cargo.lock
Cargo.toml
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key.rs

Replaces the previous handrolled ASN.1 DER parsing code with a parser based on the `der` crate.

elliptic-curve: use `der` crate to parse `SecretKey`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Low-level ECDH API ([#418])
- `dev` module ([#419])
- Impl `pkcs8::ToPrivateKey` for `SecretKey<C>` ([#423])
- Impl `pkcs8::ToPublicKey` for `PublicKey<C>` ([#427])
- Bump `subtle` dependency to 2.4.0 ([#414])
- Bump `pkcs8` dependency to v0.3.3 ([#425])
- Use `der` crate to parse `SecretKey` ([#422])
- Make `PublicKey::from_encoded_point` go through `PublicKey::from_affine` ([#416])
[#414]: https://github.com/RustCrypto/traits/pull/414
[#416]: https://github.com/RustCrypto/traits/pull/416
[#418]: https://github.com/RustCrypto/traits/pull/418
[#419]: https://github.com/RustCrypto/traits/pull/419
[#422]: https://github.com/RustCrypto/traits/pull/422
[#423]: https://github.com/RustCrypto/traits/pull/423
[#425]: https://github.com/RustCrypto/traits/pull/425
[#427]: …

elliptic-curve v0.8.2

---

.github/workflows/elliptic-curve.yml
elliptic-curve/src/secret_key/pkcs8.rs

...in the case when the `arithmetic` feature is disabled, as used by the `p384` crate (which does support PKCS#8, but does not provide an arithmetic backend)
Also adds tests for this combination in CI to prevent further regressions.

elliptic-curve: fix regression for `pem`+`zeroize` features

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Regression in combination of `pem`+`zeroize` features ([#429])
[#429]: https://github.com/RustCrypto/traits/pull/429

elliptic-curve v0.8.3

---

.github/workflows/elliptic-curve.yml
elliptic-curve/src/ecdh.rs

Closes #431.
This is the second such regression we've had recently (see also #412).
It seems to be some sort of trait resolution change/breakage, although beyond that I'm not sure what the problem is.

elliptic-curve: fix nightly regression (and add nightly CI)

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Rust `nightly` regression ([#432])
[#432]: https://github.com/RustCrypto/traits/pull/432

elliptic-curve v0.8.4

---

cipher/src/stream.rs

This reverts the implementation of `SeekNum::from_block_byte` which was merged as part of #435.
I'm not exactly sure what the issue is and it's somewhat difficult to debug in that it's code that involves both generics and macros causing an error as part of any failure in a long chain of checked arithmetic, which I'm trying to debug from the context of a concrete stream cipher impl (both `chacha20` and `salsa20`) where it's operating over a generic type.
The error manifests as `OverflowError`:
https://github.com/RustCrypto/stream-ciphers/pull/205#issuecomment-752314229
This commit reverts to the previous implementation, which is at least much simpler.

cipher: revert SeekNum::from_block_byte change

---

cipher/src/block.rs

Previously `cipher` contained blanket impls of block cipher traits for reference types, which was leveraged in e.g. `aes-gcm` and `aes-gcm-siv`. However, somewhere in the course of refactoring they were removed.
This commit adds them back.

cipher: block cipher trait blanket impls for refs

---

cipher/src/block.rs
cipher/src/common.rs
cipher/src/dev/block.rs
cipher/src/dev/stream.rs
crypto-mac/src/dev.rs
crypto-mac/src/lib.rs

Renames `new_var(key)` methods to use `new_from_slice(s)` as discussed earlier here:
https://github.com/RustCrypto/traits/pull/435#discussion_r550227781

cipher + crypto-mac: use `new_from_slice(s)` naming convention

---

Cargo.lock
cipher/Cargo.toml
crypto-mac/Cargo.toml
crypto/Cargo.toml

I'm trying to get the `AEADs` repo updated, and it's pretty unmanageable with multiple transitive `[patch.crates-io]` directives between `AEADs`, `block-cipher`, `stream-cipher`, and `MACs` (including some circular dependencies).
Cutting prereleases for this is annoying but at least more manageable (and in many ways easier to understand).

cipher v0.3.0-pre.4

---

.github/workflows/aead.yml
aead/Cargo.toml
aead/src/lib.rs
aead/src/stream.rs

Implementation of the STREAM construction as described in the paper "Online Authenticated-Encryption and its Nonce-Reuse Misuse-Resistance":
https://eprint.iacr.org/2015/189.pdf
The implementation is generic over AEAD ciphers and is factored into a low-level `StreamPrimitive` trait (permitting different "flavors" of STREAM) as well as higher-level stateful `Encryptor` and `Decryptor` objects which are generic over `StreamPrimitive` types.
Includes one concrete implementation of STREAM: `StreamLE31`, which uses a 31-bit counter and 1-bit last block flag. Note that this implementation differs slightly from the one described in the paper, which uses a 1-byte last block flag.
Using little endian provides better performance on commonly used CPU architectures, and using a 1-bit last block flag …

aead: `stream` module

---

aead/src/stream.rs

Support for instantiating STREAM primitives

aead: impl NewStream for StreamBE32/StreamLE31

---

aead/src/stream.rs

Adds a corresponding set of allocating APIs to `StreamPrimitive`, `Decryptor`, and `Encryptor`.

aead: add `alloc`-based APIs to `stream` module

---

.github/workflows/password-hash.yml
Cargo.lock
password-hash/Cargo.toml
password-hash/src/errors.rs
password-hash/src/lib.rs
password-hash/src/salt.rs
password-hash/tests/b64.rs
password-hash/tests/hashing.rs

Per [this comment](https://github.com/RustCrypto/traits/issues/450#issuecomment-754750427), changes the `Salt` type to be a simple newtype of `ValueStr`.
Since the `Salt` value is now borrowed, this unfortunately removes the ability to generate a random salt into a buffer, so this PR also removes the `rand_core` dependency.
We can potentially revisit adding a type like `SaltBuf` to use for an owned salt value.

password-hash: remove B64 restrictions on Salt

---

password-hash/src/errors.rs
password-hash/src/ident.rs
password-hash/src/lib.rs
password-hash/src/params.rs
password-hash/src/params/value.rs
password-hash/src/salt.rs

Consolidates ParseError and SaltError into a single enum

password-hash: simplify error types

---

password-hash/src/lib.rs
password-hash/tests/hashing.rs
password-hash/tests/test_vectors.rs

Support for PHC string variant with an additional version field:
https://github.com/P-H-C/phc-string-format/pull/4
This is used by Argon2.

password-hash: add `version` field

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Also bumps `rand_core` to v0.6 (for the `elliptic-curve` crate only).
This is a breaking change, so the `elliptic-curve` crate version is also bumped to v0.9.0-pre.

elliptic-curve: bump `ff` and `group` crates to v0.9.0

---

signature/derive/src/lib.rs

Links were previously busted.
Not sure if there's better way to link to types in an external crate which will render correctly on https://docs.rs but this should at least fix the immediate problem.

signature/derive: fix rustdoc links

---

Cargo.lock
signature/Cargo.toml
signature/derive/CHANGELOG.md
signature/derive/Cargo.toml

- rustdoc links ([#458])
[#458]: https://github.com/RustCrypto/traits/pull/458

signature-derive v1.0.0-pre.3

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

- Bump `rand_core` to v0.6 ([#457])
- Bump `signature-derive` v1.0.0-pre.3 ([#459])
[#457]: https://github.com/RustCrypto/traits/pull/457
[#459]: https://github.com/RustCrypto/traits/pull/459

signature v1.3.0

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

This prerelease includes this change which handles decoding/encoding the leading octet of ASN.1 BIT STRINGs:
https://github.com/RustCrypto/utils/pull/193

elliptic-curve: bump pkcs8 to v0.4.0-pre

---

password-hash/src/errors.rs
password-hash/src/lib.rs
password-hash/tests/hashing.rs

The previous name is a holdover from the old trait name (`PasswordHashingFunction`)

password-hash: rename `PhfError` => `HasherError`

---

password-hash/src/params.rs
password-hash/src/value.rs
password-hash/tests/encoding.rs

Changes the `Decimal` type alias from `i32` to `u32`.
If a particular algorithm actually needs to parse a negative value, it's still possible to parse it directly from a `ValueStr` (which this commit notes in the documentation).

password-hash: remove negative decimal support

---

password-hash/src/output.rs

The `Output` type now has some inherent methods, at which point a `Deref` impl generally stops making sense.
This commit replaces it with an `as_bytes()` inherent method, as well as the previously existing `AsRef<[u8]>` impl.

password-hash: remove `Deref` impl on `Output`

---

password-hash/src/errors.rs

Useful for reporting "B64" decoding errors, e.g. with salts

password-hash: add HasherError::B64 variant

---

password-hash/src/lib.rs
password-hash/tests/hashing.rs

Makes `password` the first argument, and have the others follow the order they appear in a password hash.

password-hash: reorder PasswordHasher::hash_password args

---

password-hash/src/lib.rs

Allows the returned `PasswordHash<'a>` to reference data from the original MCF password hash.

password-hash: add lifetime to McfHasher::upgrade_mcf_hash

---

password-hash/src/lib.rs
password-hash/src/params.rs
password-hash/tests/encoding.rs
password-hash/tests/hashing.rs

Adds an associated type for algorithm parameters, then handles automatically converting to them when using higher-level APIs.

password-hash: add associated Params type to PasswordHasher

---

password-hash/src/errors.rs
password-hash/src/lib.rs
password-hash/src/params.rs
password-hash/src/salt.rs
password-hash/src/value.rs
password-hash/tests/encoding.rs
password-hash/tests/hashing.rs
password-hash/tests/test_vectors.rs

Replaces a structured type with a builder for params strings which can also parse the in-place via an iterator.
The previous implementation had a size of 320(!) bytes despite the fact all of the string data was borrowed. It's considerably more efficient to have a buffer type that can build the parameter string which is internally stored as a byte array.
The new implementation uses a 127-byte array with a 1-byte length for a struct which is a total of 128-bytes.
This length was picked in part by adding headroom to a maximally long Argon2 params string, which looks roughly like this:
```
m=4294967296,t=4294967296,keyid=XXXXXXXXXXX,data=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
This string contains all Argon2 parameters at maximum length which comes to a total of 92-bytes, which means …

password-hash: ParamsString refactor

---

Cargo.lock
digest/Cargo.toml
digest/src/core_api.rs
digest/src/lib.rs

digest: v0.10.0 improvements

---

.github/workflows/elliptic-curve.yml
Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/error.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/ops.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/secret_key.rs

Closes #446.
Generic implementation of JSON Web Keys (JWK) for the `"kty":"EC"` case as described in RFC 7518 Section 6: Cryptographic Algorithms for Keys.
Uses `serde_json` for serialization with non-derived/minified implementations of serde's `Deserialize` and `Serialize` traits.
The implementation is `no_std`-friendly, but requires `alloc`.

elliptic-curve: JWK support

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/scalar.rs

Now that zkcrypto/ff#40 is merged, the `ff` crate re-exports the types from `bitvec` that we previously needed to import directly.
This means that `elliptic-curve` no-longer needs to depend on the `bitvec` crate directly, but instead we can use it only transitively via the `ff` crate.

elliptic-curve: remove direct `bitvec` dependency

---

elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs
elliptic-curve/tests/pkcs8.rs

Adds a trait for validating that a given encoded point is correct for a given secret value.
This allows the PKCS#8 and JWK key format parsers to validate that the public key contained in a given keypair matches the corresponding private key.

elliptic-curve: add sec1::ValidatePublicKey trait

---

.github/workflows/elliptic-curve.yml
elliptic-curve/Cargo.toml
elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs

Flattens out the API, hiding nested modules except in places where they provide actual value.
Moves some of the more problematic/confusing traits under a `hazmat` feature intended for use by curve implementations only.

elliptic-curve: factor out `hazmat`; flatten API

---

Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/jwk.rs
password-hash/Cargo.toml
password-hash/src/errors.rs
password-hash/src/lib.rs
password-hash/src/output.rs
password-hash/src/salt.rs
password-hash/src/value.rs

Includes Base64url support (needed by `elliptic-curve` for JWK)

Use `base64ct` v0.1.0 release

---

password-hash/src/lib.rs
password-hash/tests/hashing.rs

Adds a "simple" API which requires only a password and salt string as inputs, using default algorithm, version, and parameters.
Also passes through version field, which is needed to implement Argon2.

password-hash: add "simple" APIs; parameterize version

---

.github/workflows/password-hash.yml
Cargo.lock
password-hash/Cargo.toml
password-hash/src/lib.rs
password-hash/src/salt.rs

Add an owned stack-allocated string type for salts, which supports B64 encoding/decoding as well as random generation using rand_core's `CryptoRng`+`RngCore`.

password-hash: add SaltString type

---

aead/src/lib.rs
aead/src/stream.rs

Closes https://github.com/RustCrypto/traits/issues/489 (potentially, cc @theory).
Extracts a single trait for defining nonce, tag, and overhead sizes instead of repetitively defining those associated types on every other trait.
This allows for fully generic `Nonce<A>` and `Tag<A>` type aliases.

aead: extract AeadCore trait

---

aead/src/lib.rs

Following the convention introduced in #442, renames the `NewAead::new_varkey` method to `::new_from_slice`.

aead: use `new_from_slice` naming convention

---

.github/workflows/aead.yml
aead/Cargo.toml

The `alloc` feature used to be a mandatory part of the `aead` API, but in the time since we've introduced in-place traits that allow for fully heapless usage.
This commit removes it as a default feature.

aead: disable alloc by default (closes #273)

---

Cargo.lock
password-hash/Cargo.toml
password-hash/src/encoding.rs
password-hash/src/lib.rs
password-hash/src/output.rs

Support for encoding `Output` using the following Base64 variants:
- B64: for PHC hashes
- bcrypt
- `crypt(3)`: for SHA-crypt

password-hash: add basic encoding support

---

.github/workflows/aead.yml
.github/workflows/cipher.yml
.github/workflows/crypto-mac.yml
Cargo.lock
aead/Cargo.toml
aead/src/lib.rs
cipher/Cargo.toml
cipher/src/block.rs
cipher/src/common.rs
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs

Adds an optional `generate_key` method feature-gated on `rand_core` which uses a provided `CryptoRng` to generate a random key of an appropriate size for a given algorithm.

aead+cipher+crypto_mac: add `generate_key` method to `New*` traits

---

password-hash/src/lib.rs
password-hash/src/output.rs

More work towards being able to use `PasswordHash` with SHA-crypt, which uses a PHC-like hash/params, but with `crypt(3)` encoding.
This change is also trying to be purely additive to avoid having to cut new minor releases of everything.

password-hash: add encoding support to PasswordHash

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- `Encoding` enum with bcrypt and `crypt(3)` Base64 support ([#515])
- Support for using `PasswordHash` with an alternate `Encoding` ([#518])
- Bump `base64ct` dependency to v0.2 ([#519])
[#515]: https://github.com/RustCrypto/traits/pull/515
[#518]: https://github.com/RustCrypto/traits/pull/518
[#519]: https://github.com/RustCrypto/traits/pull/519

password-hash v0.1.1

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml
aead/src/lib.rs
crypto/Cargo.toml

- `stream` module ([#436], [#445], [#447])
- `NewAead::generate_key` method gated under `rand_core` feature ([#513])
- Extract `AeadCore` trait ([#508])
- Rename `NewAead::new_var` to `::new_from_slice` ([#512])
- Disable alloc by default ([#514])
- Bump `heapless` dependency to v0.6 ([#522])
[#436]: https://github.com/RustCrypto/traits/pull/436
[#445]: https://github.com/RustCrypto/traits/pull/445
[#447]: https://github.com/RustCrypto/traits/pull/447
[#508]: https://github.com/RustCrypto/traits/pull/508
[#512]: https://github.com/RustCrypto/traits/pull/512
[#513]: https://github.com/RustCrypto/traits/pull/513
[#514]: https://github.com/RustCrypto/traits/pull/514
[#522]: https://github.com/RustCrypto/traits/pull/522

aead v0.4.0

---

digest/src/core_api.rs
digest/src/core_api/ct_variable.rs
digest/src/core_api/rt_variable.rs
digest/src/core_api/update.rs
digest/src/core_api/xof_reader.rs
digest/src/digest.rs
digest/src/lib.rs

The mid-level `VariableOutput` trait is the same as in `digest v0.9`, but on lower-level it's based on the `VariableOutputCore`. Types which implement this core trait can be used in two ways:
- By specifying output size at compile time via `CtVariableCoreWrapper`. This wrapper implements the fixed core traits, so for example `Groestl384` will be defined as `UpdateCoreWrapper<CtVariableCoreWrapperGroestlBigCore, U48>>`.
- By selecting output size at run time via `RtVariableCoreWrapper`. This wrapper implements the `VariableOutput` trait.
This approach could be seen as a bit of generalization overkill, but I think it neatly describes structure of variable hash functions and allows all the flexibility we could want.
Also I have restructured the code a bit. Now the core traits and wrappers …

digest: variable output traits

---

password-hash/Cargo.toml

Based on the following `#[cfg_attr]` it looks like this was the intention but the required lines in Cargo.toml were omitted: https://github.com/RustCrypto/traits/blob/073edacf50e04c257053b6c2ef2fea8276a241e1/password-hash/src/salt.rs#L185

password-hash: add docs.rs metadata to Cargo.toml

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs

As discussed in #481, this removes the `FromDigest` trait, and with it any dependency on the `digest` crate (at least for now).
The reasoning is `FromDigest` in its current form exists to solve a single concern: hash-to-scalar for the specific purposes of ECDSA, which is implemented in the `k256` and `p256` crates as a "narrow" reduction per the requirements of ECDSA.
Given that, this trait is best moved to the `ecdsa` crate, clearing the way for a move generally useful, well-considered, and well-specified and standardized hash-to-curve construction as requested in #481.
The plan after this is to provide an identical trait, but in the `ecdsa` crate instead of the `elliptic-curve` crate.

elliptic-curve: remove FromDigest trait

---

elliptic-curve/src/dev.rs

Adds support needed to move the `FromDigest` trait to the `ecdsa` crate:
- Make `MODULUS` public
- Add a `TryFrom` impl to instantiate a `Scalar` from limbs

elliptic-curve: add `dev` support for moving FromDigest to `ecdsa`

---

elliptic-curve/src/dev.rs
elliptic-curve/src/error.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

As this crate has only one (opaque/unit) `Error` type, adds a `Result` type alias for simplifying errors returned using the `Error` type.

elliptic-curve: add `Result` alias

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- JWK support ([#483])
- `sec1::ValidatePublicKey` trait ([#485])
- `hazmat` crate feature ([#487])
- `Result` alias ([#534])
- Bump `ff` and `group` crates to v0.9 ([#452])
- Simplify ECDH trait bounds ([#475])
- Flatten API ([#487])
- Bump `pkcs8` crate dependency to v0.4 ([#493])
- Direct `bitvec` dependency ([#484])
- `FromDigest` trait ([#532])
[#452]: https://github.com/RustCrypto/traits/pull/452
[#475]: https://github.com/RustCrypto/traits/pull/475
[#483]: https://github.com/RustCrypto/traits/pull/483
[#484]: https://github.com/RustCrypto/traits/pull/484
[#485]: https://github.com/RustCrypto/traits/pull/485
[#487]: https://github.com/RustCrypto/traits/pull/487
[#493]: https://github.com/RustCrypto/traits/pull/493
[#432]: https://github.com/RustCrypto/traits/pull/432
[#532]: …

elliptic-curve v0.9.0

---

elliptic-curve/src/lib.rs

Removes the re-export of `ff::BitView`, as the `ff` crate itself is already re-exported, so it's available as `elliptic_curve::ff::BitView`.
Note that this is technically a breaking change, however the plan is to release a v0.9.1 and yank the v0.9.0 release. This is acceptable largely because the previous release is not being widely used (released 18 hours ago with 189 downloads) and therefore this change is unlikely to cause problems in practice, especially considering its relatively minor nature.

elliptic-curve: remove BitView re-export

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `BitView` re-export ([#540])
[#540]: https://github.com/RustCrypto/traits/pull/540

elliptic-curve v0.9.1

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Flatten `weierstrass` module ([#542])
[#542]: https://github.com/RustCrypto/traits/pull/542

elliptic-curve v0.9.2

---

Cargo.lock
elliptic-curve/Cargo.toml

Workaround for https://github.com/bitvecto-rs/bitvec/issues/105

elliptic-curve: pin `funty` to `=1.1.0`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Bump `pkcs8` dependency to v0.5.0 ([#549])
- Workaround for bitvecto-rs/bitvec#105 ([#550])
[#549]: https://github.com/RustCrypto/traits/pull/549
[#550]: https://github.com/RustCrypto/traits/pull/550

elliptic-curve v0.9.3

---

.github/workflows/workspace.yml

We intended to run clippy at lowest MSRV, but this directive was accidentally omitted leading to unintended breakages when new `stable` releases added new lints:
https://github.com/RustCrypto/traits/pull/554/checks?check_run_id=1922987991

ci: add `override: true` to clippy and rustfmt

---

elliptic-curve/CHANGELOG.md

Note: this commit only adds release notes. The real release is tagged here:
https://github.com/RustCrypto/traits/tree/elliptic-curve-v0.8.5
- Workaround for bitvecto-rs/bitvec#105 ([#553])
[#553]: https://github.com/RustCrypto/traits/pull/553

elliptic-curve v0.8.5

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Breakage related to the `pkcs8` v0.5.1 crate ([#556]) 
[#556]: https://github.com/RustCrypto/traits/pull/556

elliptic-curve v0.9.4

---

Cargo.lock
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs

Uses the new const-friendly OID string parser added in:
https://github.com/RustCrypto/utils/pull/312

elliptic-curve: use string-based OID constants

---

elliptic-curve/src/dev.rs

This seems like it's the most direct path to getting some other stuff upstream, and I figure it's probably pretty unobjectionable.

Implement {to,char}_le_bits for MockCurve

---

digest/src/digest.rs
digest/src/dyn_digest.rs
digest/src/lib.rs

Moves `alloc`-based gating for `DynDigest` to just the methods that use `Box`, which enables usage of the trait in "heapless" environments.
Closes #545 (cc @rvolgers)

digest: allow DynDigest usage without `alloc` enabled

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Bump `base64ct` dependency to v1.0 ([#579])
[#579]: https://github.com/RustCrypto/traits/pull/579

password-hash v0.1.2

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Implement `{to,char}_le_bits` for `MockCurve` ([#565])
- Implement `one()` for mock `Scalar` ([#566])
- Use string-based OID constants ([#561])
- Bump `base64ct` dependency to v1.0 ([#581])
[#561]: https://github.com/RustCrypto/traits/pull/561
[#565]: https://github.com/RustCrypto/traits/pull/565
[#566]: https://github.com/RustCrypto/traits/pull/566
[#581]: https://github.com/RustCrypto/traits/pull/581

elliptic-curve v0.9.5

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Bump `pkcs8` dependency to v0.6 ([#585])
[#585]: https://github.com/RustCrypto/traits/pull/585

elliptic-curve v0.9.6

---

aead/src/stream.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/tests/secret_key.rs

Closes #588
`SecretKey::from_bytes` was previously attempting to use `TryFrom<&[u8]>` on `GenericArray`, however `GenericArray` actually has a panicking `From` impl, and was therefore receiving panicking `TryFrom` via the blanket impl of `TryFrom` for `From`.
This commit adds a regression test which captures the bug, and fixes the implementation to test that the slice is correctly sized.

elliptic-curve: fix `SecretKey::from_bytes` slice parsing

---

password-hash/src/lib.rs

The upstream PR to add this to the spec was merged:
https://github.com/P-H-C/phc-string-format/pull/4

password-hash: update docs for PHC string <version> field

---

password-hash/src/output.rs
password-hash/src/salt.rs
password-hash/src/value.rs

This module no-longer exists as it was replaced by the `base64ct` crate

password-hash: fix broken `b64` links

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Update docs for PHC string <version> field ([#593])
- Broken `b64` links in rustdoc ([#594])
[#593]: https://github.com/RustCrypto/traits/pull/593
[#594]: https://github.com/RustCrypto/traits/pull/594

password-hash v0.1.3

---

aead/Cargo.toml

This is mostly to clear the https://deps.rs "insecure" warning from the repo.

aead: require `heapless` v0.6.1

---

Cargo.lock
elliptic-curve/Cargo.toml

With this `bitvec` patch, we no longer need to pin `funty`:
https://github.com/bitvecto-rs/bitvec/issues/105

elliptic-curve: pin to patched bitvec

---

password-hash/src/ident.rs
password-hash/src/output.rs
password-hash/src/salt.rs
password-hash/src/value.rs

Replaces functions with namespaced constant values.
Deprecates the old functions, i.e. non-breaking change.

password-hash: replace length `const fn`s with constants

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Length constants ([#600])
- Deprecate functions for obtaining length constants ([#600])
[#600]: https://github.com/RustCrypto/traits/pull/600

password-hash v0.1.4

---

elliptic-curve/src/lib.rs
elliptic-curve/src/order.rs

Adds a trait which notably does *not* depend on the `arithmetic` feature which allows associating a constant for the curve's order with a particular curve type.
Since it stores the curve type as a constant, it's not possible to use `GenericArray`, so instead it has each curve specify a `Limbs` type which is used as the type for an `ORDER` constant.
The longer-term goal will be to merge this with the `Curve` trait, ensuring that every curve implementation has a known order regardless of whether it provides an arithmetic backend or not.
This can be used as the foundation for making certain functionality generic across curve implementations at a baseline, such as checking if scalars are in-range, and as such can simplify things which are presently conditionally defined based on the presence …

elliptic-curve: add Order trait

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `Order` trait ([#603])
- Warnings from `pkcs8` imports ([#604])
[#603]: https://github.com/RustCrypto/traits/pull/603
[#604]: https://github.com/RustCrypto/traits/pull/604

elliptic-curve v0.9.7

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Define `Order` for `MockCurve` ([#606])
[#606]: https://github.com/RustCrypto/traits/pull/606

elliptic-curve v0.9.8

---

elliptic-curve/src/order.rs

Adds a method for checking if `FieldBytes<C>` is in range of `C::ORDER` when interpreted as a big endian integer.
This is a generic implementation which does not require an arithmetic backend for a given curve.

elliptic-curve: add `Order::is_scalar_repr_in_range`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `Order::is_scalar_repr_in_range` ([#608])
[#608]: https://github.com/RustCrypto/traits/pull/608

elliptic-curve v0.9.9

---

elliptic-curve/src/dev.rs
elliptic-curve/src/ecdh.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/order.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/secret_key.rs

Adds a type for representing `FieldBytes` which is always in range of the curve's `Order`.
Does not require the `arithmetic` feature or a `ProjectiveArithmetic` implementation, however when those are enabled it supports infallible conversions to/from `Scalar<C>`.

elliptic-curve: add `ScalarBytes` type

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `ScalarBytes` type ([#610])
[#610]: https://github.com/RustCrypto/traits/pull/610

elliptic-curve v0.9.10

---

elliptic-curve/src/lib.rs

It was previously needlessly conditionally gated on the `arithmetic` feature by accident.

elliptic-curve: always re-export ScalarBytes

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Impl `subtle` traits on `ScalarBytes<C>` ([#612])
- Always re-export ScalarBytes ([#613])
[#612]: https://github.com/RustCrypto/traits/pull/612
[#613]: https://github.com/RustCrypto/traits/pull/613

elliptic-curve v0.9.11

---

Cargo.lock
crypto/Cargo.toml
password-hash/Cargo.toml
password-hash/src/errors.rs
password-hash/src/ident.rs
password-hash/src/lib.rs
password-hash/src/output.rs
password-hash/src/params.rs
password-hash/src/salt.rs
password-hash/src/value.rs
password-hash/tests/hashing.rs

This commit contains a set of breaking changes intended to be released as part of `password-hash` v0.2, addressing a number of currently open issues about the crate discovered when integrating it into the crates in the https://github.com/RustCrypto/password-hashes repo.
This fixes the following issues:
- Allow specifying output length and version with params (#505)
- Allow passing `&str`, `&Salt`, or `&SaltString` as salt (#529)
- Simplify error handling (#547)

password-hash: v0.2 breaking changes

---

Cargo.lock
crypto/Cargo.toml
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Allow specifying output length and version with params ([#615])
- Allow passing `&str`, `&Salt`, or `&SaltString` as salt ([#615])
- Simplify error handling ([#615])
[#615]: https://github.com/RustCrypto/traits/pull/615

password-hash v0.2.0

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml
aead/src/lib.rs

- Bump `heapless` dependency to v0.7 ([#628])
[#628]: https://github.com/RustCrypto/traits/pull/628

aead v0.4.1

---

cipher/CHANGELOG.md
crypto-mac/CHANGELOG.md

- Document `generate_key`
- Add `new_from_slice` docs to `crypto-mac` (closes #626)

cipher + crypto-mac: CHANGELOG fixups

---

.github/workflows/password-hash.yml
Cargo.lock
password-hash/Cargo.toml
password-hash/src/output.rs
password-hash/src/salt.rs
password-hash/src/value.rs

Previously a non-short-circuiting comparison was used, however the `subtle` crate provides a more robust option in this regard with the `ConstantTimeEq` trait and its associated impls on byte slices.
This commit also includes an updated rationale for why password hashes benefit from constant time comparisons, including a description of a timing attack on password hash verification.

password-hash: use `subtle` crate for comparing hash `Output`

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Use `subtle` crate for comparing hash `Output` ([#631])
[#631]: https://github.com/RustCrypto/traits/pull/631

password-hash v0.2.1

---

crypto/src/lib.rs

It previously had a hyphen (i.e. crate name, not module name)

crypto: fix `password_hash` module name in rustdoc

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `Ord` and `PartialOrd` impls on `PublicKey` ([#637])
[#637]: https://github.com/RustCrypto/traits/pull/637

elliptic-curve v0.9.12

---

.github/workflows/elliptic-curve.yml
Cargo.lock
crypto/Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/README.md
elliptic-curve/src/dev.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Bumps the `ff` and `group` crate dependencies to the latest releases.
Additionally, this commit removes the re-export of the `ff` crate, with the expectation it be accessed as `elliptic_curve::group::ff` instead.
- `ff`: https://github.com/zkcrypto/ff/blob/main/CHANGELOG.md#0100---2021-06-01
- `group`: https://github.com/zkcrypto/group/blob/main/CHANGELOG.md#0100---2021-06-01

elliptic-curve: bump `ff` and `group` to v0.10; MSRV 1.51+

---

.github/workflows/crypto.yml
Cargo.lock
Cargo.toml
crypto/README.md
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs

The `crypto_bigint::UInt` type has const-friendly initializers that can parse the curve order from e.g. hexadecimal.
This commit changes the `Order` to be represented as a `UInt` type. This also permits things like simplified (and constant time, if needed) comparisons to ensure a given value is in range.
Additionally, this commit reimplements the `dev` module's `Scalar` type for `MockCurve` to use a `crypto_bigint::U256` internally.

elliptic-curve: use `crypto-bigint` to represent `Curve::Order`

---

Cargo.lock
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs

The `crypto-bigint` library defines an associated `ArrayLength<u8>` for every `UInt` type as part of the `ArrayEncoding` trait.
This means we don't need to define both: we can now source what was previously `C::FieldSize` via `C::UInt::ByteSize`.
This commit performs that replacement, adding a `FieldSize<C>` type alias which can be used anywhere `C::FieldSize` was previously used which sources the `ArrayLength<u8>` from `C::UInt` instead.

elliptic-curve: source FieldSize from Curve::UInt type

---

elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs

Uses the `ConstantTimeLess` impl on `UInt` to ensure that a bigint parsed from the inner byte array does not overflow the curve's order.

elliptic-curve: impl ScalarBytes<C> using C::UInt

---

elliptic-curve/src/jwk.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Previously SecretKey<C> had a generic internal value, depending on whether or not the `arithmetic` feature was activated. This was mostly trying to work around the fact that there wasn't a baseline arithmetic impl available to validate secret keys.
Now there is! SecretBytes<C> uses C::UInt and its may features as a `crypto-bigint` to always validate the internal bytes.
This means we can simply use `SecretBytes<C>` as the inner value of a `SecretKey<C>`, and still provide infallible conversions to `NonZeroScalar<C>`.

elliptic-curve: make ScalarBytes<C> the SecretKey<C> internal repr

---

Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/secret_key/pkcs8.rs
elliptic-curve/tests/pkcs8.rs

Patched in via git.
This version includes the merger of `PublicKeyInfo` and `OneAsymmetricKey` into a single type.
Additionally, it bumps the `der` crate, which simplifies handling of context-sensitive fields.
It also makes encoding fallible, which eliminates a lot of previous usages of `expect`.

elliptic-curve: bump PKCS#8 to v0.7.0-pre

---

elliptic-curve/src/scalar/bytes.rs

Support for decoding scalar bytes from the bigint type for a given elliptic curve.

elliptic-curve: ScalarBytes::from_uint

---

elliptic-curve/src/dev.rs

Alias for `ScalarBytes<MockCurve>`

elliptic-curve: add dev::ScalarBytes

---

.github/workflows/elliptic-curve.yml
elliptic-curve/src/dev.rs
elliptic-curve/src/ecdh.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Add a trait with an associated scalar type which can be used to control the bounds required by this library.

elliptic-curve: add ScalarArithmetic trait

---

Cargo.lock
elliptic-curve/src/secret_key/pkcs8.rs

Simplifies checking of SPKI OIDs

elliptic-curve: use `AlgorithmIdentifier::assert_oids` helper

---

elliptic-curve/src/sec1.rs
elliptic-curve/src/weierstrass.rs

This PR contains @vihu's work from #590, rebased against the latest version of the code, and modified so as not to introduce new trait bounds on existing types, thus making support by any particular curve implementation optional.
I'm a bit hesitant to support a draft, especially one where I would like to propose changes but from an IETF process perspective it otherwise seems dead. Nevertheless the functionality it provides does seem interesting, and in that regard worth supporting.
Closes #590.

Add `PointCompaction` trait

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/sec1.rs

Sourced from git.
Incorporates this `Encoding` trait refactor: https://github.com/RustCrypto/utils/pull/488

elliptic-curve: bump `crypto-bigint` to v0.2.0-pre

---

elliptic-curve/src/lib.rs

Ideally instead of specifying a `Curve::UInt` associated type, we could instead specify a constant, and then pass that as a const generic parameter to `crypto_bigint::UInt`.
Unfortunately that requires a lot more functionality than is implemented in `min_const_generics`:
https://github.com/rust-lang/rust/issues/60551
This commit makes a note of as much in the comments, calling it out as future work.

elliptic-curve: add TODO for replacing UInt with an associated constant

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `ScalarBytes::from_uint` ([#651])
- `dev::ScalarBytes` ([#652])
- `ScalarArithmetic` trait ([#654])
- `AffineArithmetic` trait ([#658])
- `PointCompaction` trait and SEC1 tag support ([#659])
- Bump `ff` and `group` to v0.10; MSRV 1.51+ ([#643])
- Merge `Curve` and `Order` traits ([#644])
- Use `crypto-bigint` to represent `Curve::ORDER` ([#645])
- Source `FieldSize<C>` from `C::UInt` type ([#646])
- Impl `ScalarBytes<C>` using `C::UInt` ([#647])
- Make `ScalarBytes<C>` the `SecretKey<C>` internal repr ([#649])
- Bump `crypto-bigint` to v0.2 ([#662])
- Bump `pkcs8` to v0.7 ([#662])
- `util` module ([#648])
[#643]: https://github.com/RustCrypto/traits/pull/643
[#644]: https://github.com/RustCrypto/traits/pull/644
[#645]: https://github.com/RustCrypto/traits/pull/645
[#646]: …

elliptic-curve v0.10.0

---

Cargo.lock
crypto/CHANGELOG.md
crypto/Cargo.toml
crypto/src/lib.rs

- Bump `elliptic-curve` crate dependency to v0.10 ([#663])
- Bump `signature` crate dependency to v1.3.0 ([#664])
[#663]: https://github.com/RustCrypto/traits/pull/663
[#664]: https://github.com/RustCrypto/traits/pull/664

crypto v0.3.0

---

elliptic-curve/src/public_key.rs

The new trait bounds on `AffineArithmetic` ensure that `AffinePoint` is always `Copy`. So the previously imposed trait bounds prevent `Copy` impls which should be available by default.

elliptic-curve: derive `Copy` on `PublicKey`

---

elliptic-curve/src/public_key.rs

The derived `Copy` impl appears to be adding additional undesired trait bounds.
This explicit impl ensures it's always available.

elliptic-cure: add explicit `Copy` bounds on `PublicKey`

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Explicit `Copy` bounds on `PublicKey` ([#667])
[#667]: https://github.com/RustCrypto/traits/pull/667

elliptic-curve v0.10.1

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- `ConstantTimeEq` impl for `NonZeroScalar` ([#669])
[#669]: https://github.com/RustCrypto/traits/pull/669

elliptic-curve v0.10.2

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Bump `crypto-bigint` to v0.2.1 ([#673])
[#673]: https://github.com/RustCrypto/traits/pull/673

elliptic-curve v0.10.3

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

- `Result` alias ([#676])
[#676]: https://github.com/RustCrypto/traits/pull/676

signature v1.3.1

---

Cargo.lock
aead/Cargo.toml
aead/src/lib.rs

This PR implements the changes proposed in #681 to simplify access to the `rand_core` traits and `OsRng`.
`rand_core` is conditionally re-exported when the eponymous crate feature is enabled.
Additionally, the `std` crate feature enables `rand_core/std`, which permits access to `OsRng` as `aead::rand_core::OsRng`.

aead: re-export `rand_core`

---

aead/CHANGELOG.md
cipher/CHANGELOG.md
cipher/Cargo.toml
cipher/src/lib.rs
crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs
signature/CHANGELOG.md
signature/src/lib.rs

Closes #681
Also issue compilation errors if unstable functionality in the `signature` crate is enabled by toggling features introduced by optional dependencies. In theory it may break build for some people, but it would've happened eventually either way. Also I do not forward `std` to `rand_core` in this case since doing it correctly requires weak feature activation.

Re-export rand_core

---

aead/CHANGELOG.md
aead/Cargo.toml
aead/src/lib.rs

- Re-export `rand_core` ([#682])
[#682]: https://github.com/RustCrypto/traits/pull/682

aead v0.4.2

---

Cargo.lock
aead/CHANGELOG.md
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Re-export `rand_core` ([#683])
[#683]: https://github.com/RustCrypto/traits/pull/683

elliptic-curve v0.10.4

---

crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs

#690 has pinned `subtle` for `crtypto-mac` v0.10.

Pin subtle to v2.4 for crypto-mac v0.11

---

Cargo.lock
crypto-mac/CHANGELOG.md
crypto-mac/Cargo.toml
crypto-mac/src/lib.rs
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs
universal-hash/CHANGELOG.md
universal-hash/Cargo.toml
universal-hash/src/lib.rs

`crypto-mac` will be updated in a separate PR since current `master` contains the pre-release version.
Also updates Cargo.lock.

Pin zeroize dependency to v1.4 and subtle to v2.4

---

password-hash/src/errors.rs
password-hash/src/salt.rs
password-hash/src/value.rs

Without this `Salt` cannot represent the full possible length of a salt value as defined in the PHC string format spec.

password-hash: make value and salt lengths the same

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Make max lengths of `Value` and `Salt` both 64 ([#707])
[#707]: https://github.com/RustCrypto/traits/pull/707

password-hash v0.2.3

---

Cargo.lock
elliptic-curve/Cargo.toml

This release includes some new features which can be used to calculate various constants from an elliptic curve's order using `const fn`s.
Bumping the minimum release allows for elliptic curve libs to pin to a release of the `elliptic-curve` crate which includes this new version, allowing them to ensure the transitive dependency is up-to-date without explicitly pinning to it.

elliptic-curve: bump `crypto-bigint` dependency to v0.2.4

---

Cargo.lock
elliptic-curve/CHANGELOG.md
elliptic-curve/Cargo.toml
elliptic-curve/src/lib.rs

- Bump `crypto-bigint` dependency to v0.2.4 ([#710])
[#710]: https://github.com/RustCrypto/traits/pull/710

elliptic-curve v0.10.6

---

Cargo.lock
aead/CHANGELOG.md
aead/Cargo.toml
aead/src/lib.rs

- `Result` type alias ([#725])
[#725]: https://github.com/RustCrypto/traits/pull/725

aead v0.4.3

---

Cargo.lock
crypto/Cargo.toml
elliptic-curve/Cargo.toml
elliptic-curve/src/arithmetic.rs
elliptic-curve/src/dev.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/scalar/bytes.rs
elliptic-curve/src/scalar/non_zero.rs

Release notes:
- `ff`: https://github.com/zkcrypto/ff/blob/main/CHANGELOG.md#0110---2021-09-02
- `group`: https://github.com/zkcrypto/group/blob/main/CHANGELOG.md#0110---2021-09-02

elliptic-curve: bump `ff` + `group` to v0.11

---

Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/scalar/non_zero.rs

Also adds smoke tests that `NonZeroScalar` and `dev::Scalar` round trip successfully to their reprs.

elliptic-curve: bump `crypto-bigint` to v0.2.5

---

signature/CHANGELOG.md
signature/src/signer.rs

As per our discussion on the RCIG Zulip, there seems to be a need for a stateful version of the `Signer` trait. This lets us support "Key Evolving Signature Schemes" such as [XMSS](https://eprint.iacr.org/2011/484).
One thing that is unclear so far is whether we also want to do stateful versions of `DigestSigner`, `RandomizedSigner`, and `AsyncSigner`. I think the latter two won't be an issue for now, since XMSS is a deterministic scheme, and HSMs do not support XMSS.

Defined the SignerMut trait

---

elliptic-curve/src/dev.rs
elliptic-curve/src/ecdh.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/lib.rs
elliptic-curve/src/point.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Renames `weierstrass::Curve` to `PrimeCurve`, a marker trait for curves of prime order.
The `weierstrass` module is otherwise removed/renamed internally, with the traits previously contained re-exported from the toplevel.

elliptic-curve: refactor `PrimeCurve` crate

---

elliptic-curve/src/arithmetic.rs
elliptic-curve/src/dev.rs
elliptic-curve/src/ecdh.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/sec1.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Makes `DefaultIsZeroes` a mandatory bound for all `*Arithmetic` traits (i.e. scalar, affine, projective)

elliptic-curve: mandatory `DefaultIsZeroes` bounds

---

.github/workflows/crypto.yml
.github/workflows/elliptic-curve.yml
.github/workflows/workspace.yml
crypto/README.md
elliptic-curve/README.md
elliptic-curve/src/arithmetic.rs
elliptic-curve/src/lib.rs

Adds a trait for elliptic curves with a prime order curve group which bounds on the corresponding traits from `group::prime`.

elliptic-curve: add `PrimeCurveArithmetic` trait; MSRV 1.52+

---

elliptic-curve/src/arithmetic.rs
elliptic-curve/src/dev.rs

Adds more `From` and `Into` bounds:
- From<ScalarCore<C>>`
- Into<Self::UInt>
- Into<FieldBytes<C>>

elliptic-curve: additional `ScalarArithmetic::Scalar` bounds

---

Cargo.lock
Cargo.toml
elliptic-curve/src/jwk.rs
elliptic-curve/src/scalar.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs
elliptic-curve/tests/pkcs8.rs
elliptic-curve/tests/secret_key.rs

Changes the names to be consistent with the `core` methods on unsigned integer types as well as the names in the `crypto-bigint` crate.

elliptic-curve: rename `from_be_bytes`/`from_le_bytes` and `to_be_bytes`

---

elliptic-curve/src/secret_key.rs

Returns `Zeroizing<String>` instead of just `String`, ensuring that a string containing a JWK secret is zeroized on drop.

elliptic-curve: makes `SecretKey::to_jwk_string` self-zeroizing

---

elliptic-curve/src/scalar/core.rs

Adds support for decoding `ScalarCore` from a byte slice

elliptic-curve: add `ScalarCore::from_*_slice`

---

password-hash/src/lib.rs

The hash should only be added if there is a salt according to the PHC specification.
```
$<id>[$v=<version>][$<param>=<value>(,<param>=<value>)*][$<salt>[$<hash>]]
```
This shouldn't be a vulnerability as it is **not** in the parser. Even though the parser code looks the same it shouldn't be susceptible due to the use of a iterator.

fixed fmt::Display for PasswordHash

---

Cargo.lock
elliptic-curve/Cargo.toml

This includes a bugfix for modular addition which is needed for `ScalarCore::add` to be correct.

elliptic-curve: bump `crypto-bigint` to v0.2.7

---

elliptic-curve/src/dev.rs

Uses `ScalarCore` as the internal representation of the `dev::Scalar` newtype, and implements more functionality in terms of it.

elliptic-curve: `dev` module improvements

---

password-hash/Cargo.toml

password-hash: pin `base64ct` to <1.1

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- `PasswordHashString` ([#758])
- Handling of empty salts in `fmt::Display` impl for PasswordHash ([#748])
- MSRV regression from `base64ct` ([#757])
[#748]: https://github.com/RustCrypto/traits/pull/748
[#757]: https://github.com/RustCrypto/traits/pull/757
[#758]: https://github.com/RustCrypto/traits/pull/758

password-hash v0.3.1

---

password-hash/src/lib.rs
password-hash/src/traits.rs

Also adds a `warn(unused_lifetimes)` lint to prevent this going forward

password-hash: remove unused lifetimes

---

Cargo.lock
password-hash/CHANGELOG.md
password-hash/Cargo.toml
password-hash/src/lib.rs

- Remove unused lifetimes ([#760])
[#760]: https://github.com/RustCrypto/traits/pull/760

password-hash v0.3.2

---

elliptic-curve/src/sec1.rs

This was accidentally hidden during the refactoring in #762

elliptic-curve: (re)re-export `sec1::Tag`

---

Cargo.lock
elliptic-curve/Cargo.toml

These are both hard dependencies of `elliptic-curve` anyway

elliptic-curve: enable `sec1` crate's `subtle` and `zeroize` features

---

elliptic-curve/src/arithmetic.rs
elliptic-curve/src/dev.rs
elliptic-curve/src/ops.rs

Adds a trait for modular reduction, primarily intended for use cases like hashing to a field element.
The trait is generic around a `UInt` to permit overlapping impls, allowing either "narrow" or "wide" reduction, selected by the size of the input.

elliptic-curve: add `Reduce` trait

---

elliptic-curve/src/public_key.rs

This was removed in #771 but can still be supported

elliptic-curve: add back `From<PublicKey>` for `EncodedPoint` impl

---

elliptic-curve/src/arithmetic.rs

Narrow reductions are not ideal and introduce much more bias than a wide reduction. If we are going to bound on a `Reduce` impl, it should at least include a wide reduction so we don't accidentally drive people to narrow reductions instead.
While they are needed for ECDSA, narrow reductions should probably be discouraged in other non-legacy applications.

elliptic-curve: remove narrow `Reduce` bound on `Scalar`

---

elliptic-curve/src/dev.rs

This is needed for the RFC6979 tests in the `ecdsa` crate.

elliptic-curve: impl `Reduce<U256>` for `dev::Scalar`

---

elliptic-curve/src/dev.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/sec1.rs

Internally `k256`/`p256` return a `CtOption` for this method, then convert to an `Option`.
It would be helpful when implementing other traits from the `group` crate, e.g. `GroupEncoding`, if this instead returned a `CtOption`.

elliptic-curve: make `FromEncodedPoint` return a `CtOption`

---

elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

This is a needless restriction

elliptic-curve: remove `PrimeCurve` bounds on SEC1 points

---

Cargo.lock
Cargo.toml
elliptic-curve/Cargo.toml

The `elliptic-curve` crate is presently a prerelease as well.
This commit has it pull in the prerelease format parsers so we can properly integration test them for the elliptic curve use case.

elliptic-curve: use prerelease format parsers

---

Cargo.lock
signature/CHANGELOG.md
signature/Cargo.toml
signature/src/lib.rs

- Re-export `rand_core` when the `rand-preview` feature is enabled ([#683])
- `SignerMut` trait ([#734])
- Show error source in `Display` impl ([#791])
[#683]: https://github.com/RustCrypto/traits/pull/683
[#734]: https://github.com/RustCrypto/traits/pull/734
[#791]: https://github.com/RustCrypto/traits/pull/791

signature v1.4.0

---

elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/jwk.rs
elliptic-curve/src/public_key.rs
elliptic-curve/src/scalar/non_zero.rs
elliptic-curve/src/secret_key.rs
elliptic-curve/src/secret_key/pkcs8.rs

Now that we've upgraded to Rust 2021 edition, these are now available via the prelude, making explicit imports redundant.

elliptic-curve: remove `TryFrom`/`TryInto` imports

---

password-hash/src/ident.rs

At this point, we (can) know whether `too_long` is true, so don't iterate over all the `bytes`. (Both invalid chars and excessive length result in the same kind of error.) I don't think I see a constant-time/timing-independence concern — if a malicious input is too long, saying so immediately does not give the attacker any information about the `bytes` value.

Return early if `Ident` is too long

---

elliptic-curve/Cargo.lock
elliptic-curve/Cargo.toml
elliptic-curve/src/dev.rs
elliptic-curve/src/scalar/core.rs

Vetting the prerelease to make sure there aren't any showstoppers

elliptic-curve: bump `crypto-bigint` to v0.3.0-pre.1

---

password-hash/src/salt.rs

Adds impls of `Debug` and `Display` on `SaltString` similar to the ones on `Salt` (the reference type).
Previously there was no `Display` impl at all.
The `Debug` impl was previously derived, and therefore had confusing output due to the use of a fixed-sized internal buffer to support heapless platforms.
Now they both print the string value, with the `Debug` impl wrapped in `SaltString(...)`.

password-hash: better `Debug`/`Display` impls for `SaltString`

---

elliptic-curve/Cargo.lock
elliptic-curve/src/public_key.rs

Updates `elliptic-curve` to the latest version of `pkcs8`/`spki`

elliptic-curve: bump RustCrypto/formats crates
