RustCrypto/traits

elliptic-curve/src/lib.rs
It was removed upstream to allow the `Integer` trait to be blanket impl'd instead of using a macro.
=> elliptic-curve: add Encoding bound on Curve::UInt

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/dev.rs, elliptic-curve/src/error.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, elliptic-curve/tests/pkcs8.rs
The `sec1` crate provides a blanket impl of traits like `DecodeEcPrivateKey` and `EncodeEcPrivateKey` for types which impl the `pkcs8` traits.
This commit leverages them.
=> elliptic-curve: use `sec1` crate for `pkcs8` support

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
This removes all of the git-based dependencies on `RustCrypto/formats`
=> elliptic-curve: bump `spki` to v0.5 release

elliptic-curve/src/scalar/non_zero.rs
Previously they were `ProjectiveArithmetic`, ostensibly because the `ScalarArithmetic` trait didn't exist at the time.
=> elliptic-curve: use `ScalarArithmetic` as `NonZeroScalar` bounds

elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/secret_key.rs
Uses the new `doc = include_str!("...")` attribute to include README.md in the rustdoc documentation.
Additionally fills out the toplevel rustdoc with a bit more information about how the crate is intended to be used.
=> elliptic-curve: include README.md in rustdoc + expand docs

elliptic-curve/Cargo.lock, elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/core.rs
Adds a trait for determining if a given scalar is larger than the order divided by 2.
This is useful for "normalization" use cases such as low-S normalized ECDSA signatures, where a scalar is conditionally negated if "high".
=> elliptic-curve: add `scalar::IsHigh` trait

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/point.rs
Protocols like ECDH and ECDSA rely on x-coordinate access.
We've tried various ways of trying to keep affine coordinate access out of the public API, but it complicates generic implementations of these protocols.
Most recently RustCrypto/signatures#395 attempted to add a trait which encapsulated ECDSA signing, but a similar (or expanded version of the same) trait is needed for verification.
All of these problems go away, and can be expressed with simple trait bounds, if there is some way to access the x-coordinate of an `AffinePoint` as serialized `FieldBytes`.
This commit adds such a trait: `AffineXCoordinate`, which is a mandatory bound of `AffineArithmetic::AffinePoint`.
=> elliptic-curve: add `AffineXCoordinate` trait

.github/workflows/elliptic-curve.yml, elliptic-curve/Cargo.lock, elliptic-curve/src/hex.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/non_zero.rs
Adds support for serializing/deserializing the following types using serde:
- `ScalarCore`
- `NonZeroScalar`
- `PublicKey`
While this crate had `serde` support previously, it was entirely limited to the JWK implementation.
This commit expands it to support more types, and provides the underpinnings for better leveraging `serde` in all of the dependent crates.
=> elliptic-curve: `serde` support for scalar and `PublicKey` types

crypto/Cargo.lock, crypto/Cargo.toml, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- `ScalarCore<C>` type ([#732])
- `PrimeCurveArithmetic` trait ([#739])
- SEC1 private key support ([#762])
- `Reduce` trait ([#768])
- Re-export `ff` and `PrimeField` ([#796])
- `Encoding` bound on `Curve::UInt` ([#806])
- `scalar::IsHigh` trait ([#814], [#815])
- `Neg` impl for `NonZeroScalar<C>` ([#816])
- `AffineXCoordinate` trait ([#817])
- `serde` support for scalar and `PublicKey` types ([#818])
- Bump `ff` + `group` to v0.11 ([#730])
- Make `SecretKey::to_jwk_string` self-zeroizing ([#742])
- Use `sec1` crate's `EncodedPoint` ([#771])
- Make `FromEncodedPoint` return a `CtOption` ([#782])
- Rust 2021 edition upgrade; MSRV to 1.56 ([#795])
- Bump `crypto-bigint` dependency to v0.3 ([#807])
- Use `sec1` crate for `pkcs8` support ([#809])
- Bump `spki` dependency to v0.5 release …
=> elliptic-curve v0.11.0

elliptic-curve/src/scalar/non_zero.rs
Adds a `NonZeroScalar` constructor that accepts a `C::UInt` as a parameter, returning a `CtOption` if the `UInt` represents a valid non-zero element of the scalar field.
=> elliptic-curve: add `NonZeroScalar::from_unit`

crypto/Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- `NonZeroScalar::from_uint` ([#822])
[#822]: https://github.com/RustCrypto/traits/pull/822
=> elliptic-curve v0.11.1

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- Bump `pem-rfc7468` dependency to v0.3 ([#825])
[#825]: https://github.com/RustCrypto/traits/pull/825
=> elliptic-curve v0.11.2

elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/non_zero.rs
Adds a trait similar to `Reduce`, but where the output of the reduction is ensured to be non-zero.
Also impls `Reduce` and `ReduceNonZero` for `NonZeroScalar`. This means that end users need only concern themselves with `Reduce` as they can use `NonZeroScalar::<C>::from_uint_reduced` instead of the more cumbersome `Scalar::<C>::from_uint_reduced_non_zero`.
Related: RustCrypto/elliptic-curves#432
cc @fjarri
=> elliptic-curve: add `ReduceNonZero` trait

elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/nonzero.rs
In #827, a `ReduceNonZero` trait was added whose method name uses an underscored `*_non_zero`.
However, there's already one bit of precedent in the public API:
- `SecretKey::to_nonzero_scalar`
Since this is already a stable API and providing precedent, for consistency this commit changes all of the unstable/unreleased APIs and internal module naming to use `nonzero` instead of `non_zero`, as this is a non-breaking change.
=> elliptic-curve: `non_zero` => `nonzero`

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- `ReduceNonZero` trait ([#827])
[#827]: https://github.com/RustCrypto/traits/pull/827
=> elliptic-curve v0.11.3

elliptic-curve/Cargo.lock, elliptic-curve/src/point.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs
Document serde serializations provided by this crate
=> elliptic-curve: serde documentation

elliptic-curve/src/ops.rs
Adds a trait for computing `x * k + y * l`.
This allows curve implementations to provide optimized arithmetic when available (e.g. Shamir's Trick)
=> elliptic-curve: add `LinearCombination` trait

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- `LinearCombination` trait ([#832])
[#832]: https://github.com/RustCrypto/traits/pull/832
=> elliptic-curve v0.11.4

elliptic-curve/src/ecdh.rs
There's an example marked `ignore` for the `diffie_hellman` function which is no longer valid. This commit fixes it.
=> elliptic-curve: fix `ecdh` docs

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs
Changes `LinearCombination` to be impl'd on the `ProjectivePoint` type for a given curve, rather than the curve ZST.
This better fits the trait-based structure used by the `group` crate, and also makes sense as `ProjectivePoint` is the return type, so it's almost certain to be in scope (as opposed to importing a curve ZST to do the operation)
This is technically a breaking change as the `LinearCombination` trait was just released an hour ago in v0.11.4, but given that it's unlikely anyone is using it yet, so it can probably be safely yanked and the updated version included in a new release.
=> elliptic-curve: revised `LinearCombination` trait

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- Revised `LinearCombination` trait ([#835])
[#835]: https://github.com/RustCrypto/traits/pull/835
=> elliptic-curve v0.11.5

Cargo.lock, crypto-common/CHANGELOG.md, crypto-common/Cargo.toml, crypto-common/src/lib.rs, digest/CHANGELOG.md, digest/Cargo.toml, digest/src/lib.rs, digest/src/mac.rs
Properly exposes docs for random key/IV generation methods, re-exports `rand_core`, and adds `Mac::generate_key` method which wraps `KeyInit::generate_key`.
=> rand_core fixes for digest and crypto-common

elliptic-curve/src/lib.rs
Adds a chart which illustrates the various conversions possible between the various types defined by this crate to the toplevel rustdoc.
cc @daviddrysdale
=> elliptic-curve: type conversions chart

crypto/Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- Type conversions chart ([#852])
[#852]: https://github.com/RustCrypto/traits/pull/852
=> elliptic-curve v0.11.6

digest/src/lib.rs
Deletes doubled `VariableOutput`
=> digest: Fix typo in docs

kem/Cargo.lock, kem/Cargo.toml, kem/README.md
- Bump `version` down to 0.0.0 as it hasn't been released
- Add `rust-version` to Cargo.toml
- Fix MSRV badge in README.md
cc @rozbb
=> kem: minor fixups

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/hash2field.rs, elliptic-curve/src/hash2field/expand_msg.rs, elliptic-curve/src/hash2field/expand_msg_xmd.rs, elliptic-curve/src/hash2field/expand_msg_xof.rs, elliptic-curve/src/lib.rs
Upstream hash2field as described in [PR 495](https://github.com/RustCrypto/elliptic-curves/pull/495)
=> feat: add hash to field

elliptic-curve/src/scalar/nonzero.rs
It is convenient to be able to do that without unwraps in the client code. The only problem I see is that it assumes that the scalar operations are modulo a prime - is that always the case?
=> Add impl of `Mul` for `NonZeroScalar` * `NonZeroScalar`

elliptic-curve/src/scalar/nonzero.rs
- Uses a `PrimeCurve` bound to ensure curve is prime order
- Composes the owned and borrowed impls of `Mul`, implementing the former in terms of the latter
=> elliptic-curve: fixups for `Mul` impls for `NonZeroScalar`

Cargo.lock, crypto/Cargo.lock, crypto/Cargo.toml, signature/CHANGELOG.md, signature/Cargo.toml, signature/async/Cargo.toml, signature/src/lib.rs
- Bump `digest` dependency to v0.10 ([#850])
- Bump `signature-derive` dependency to v1.0.0-pre.4 ([#866])
[#850]: https://github.com/RustCrypto/traits/pull/850
[#866]: https://github.com/RustCrypto/traits/pull/866
=> signature v1.5.0

.github/workflows/elliptic-curve.yml, elliptic-curve/src/ops.rs
Adds `digest` feature-gated methods to the `Reduce` trait for reducing the output of a hash function as either a big endian or little endian integer.
=> elliptic-curve: add `Reduce::from_*e_digest_reduced`

elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2field.rs, elliptic-curve/src/hash2field/expand_msg.rs, elliptic-curve/src/hash2field/expand_msg_xmd.rs, elliptic-curve/src/hash2field/expand_msg_xof.rs
As noted on #865 there are some potential overflow problems constructing the messages used for expansion, particularly around input lengths.
This commit changes `ExpandMsg::expand_message`, and all of its transitive callers, to be fallible in order to handle these cases.
cc @mikelodder7 @daxpedda
=> elliptic-curve: make `ExpandMsg` fallible

elliptic-curve/src/hash2curve.rs, elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2curve/isogeny.rs, elliptic-curve/src/hash2curve/map2curve.rs, elliptic-curve/src/hash2curve/osswu.rs, elliptic-curve/src/hash2field.rs, elliptic-curve/src/hash2field/expand_msg.rs, elliptic-curve/src/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2field/expand_msg/xof.rs, elliptic-curve/src/lib.rs
- Moves doc comments on `mod <modname>` into toplevel module comments. These have the same effect, but also self-document the module you are looking at, and are more amenable to rich top-of-module documentation. It's also consistent with the rest of the existing rustdoc in the RustCrypto project.
- Breaks apart the rustdoc "headline" from the rest of the comments for better formatting on the HTML rendering.
- Uses backticks and [`TypeName`] syntax to linkify type names where appropriate.
=> elliptic-curve: hash2curve rustdoc improvements

.github/workflows/elliptic-curve.yml, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
Fixes RustCrypto/elliptic-curves#500.
Implementation: RustCrypto/elliptic-curves#506.
=> Introduce `VoprfParameters` trait

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- Initial hash-to-field support ([#854], [#855], [#871], [#874])
- Initial hash-to-curve support ([#865], [#876])
- Impl `Mul` for `NonZeroScalar` * `NonZeroScalar` ([#857], [#862])
- `Reduce::from_*e_digest_reduced` ([#869])
- `VoprfParameters` trait ([#878])
[#854]: https://github.com/RustCrypto/traits/pull/854
[#855]: https://github.com/RustCrypto/traits/pull/855
[#857]: https://github.com/RustCrypto/traits/pull/857
[#862]: https://github.com/RustCrypto/traits/pull/862
[#865]: https://github.com/RustCrypto/traits/pull/865
[#869]: https://github.com/RustCrypto/traits/pull/869
[#871]: https://github.com/RustCrypto/traits/pull/871
[#874]: https://github.com/RustCrypto/traits/pull/874
[#876]: https://github.com/RustCrypto/traits/pull/876
[#878]: …
=> elliptic-curve v0.11.7

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/ecdh.rs, elliptic-curve/src/jwk.rs, elliptic-curve/src/secret_key.rs
I'm assuming this is a breaking change.
=> Implement `ZeroizeOnDrop` on appropriate items

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/error.rs, elliptic-curve/src/hex.rs
Uses the new `base16ct` crate for hex decoding.
The encoder is still implemented in a non-constant-time manner. The functionality to encode to a `fmt::Formatter` needs to be upstreamed into the `base16ct` crate.
=> elliptic-curve: use the `base16ct` crate

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/hex.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs
Uses a constant time-ish implementation of a hexadecimal display formatter to replace what was previously in the `hex` module.
=> elliptic-curve: use `base16ct::HexDisplay`

crypto/Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
- Impl `ZeroizeOnDrop` on appropriate items ([#884])
- Use the `base16ct` crate for hex serialization ([#886], [#887], [#888])
[#884]: https://github.com/RustCrypto/traits/pull/884
[#886]: https://github.com/RustCrypto/traits/pull/886
[#887]: https://github.com/RustCrypto/traits/pull/887
[#888]: https://github.com/RustCrypto/traits/pull/888
=> elliptic-curve v0.11.8

digest/Cargo.toml
`generic-array` v0.14.4 uses `typenum` v1.12.0, which makes `Unsigned`(which `ArrayLength` implies) imply `Default`, which, in turn, is required for `CoreWrapper` to to implement `Digest`.
This is needed to make upstream crates which uses `Digest` implementation of `CoreWrappper` (such as `hmac`) to successfully build with `-Z minimal-versions`.
=> digest: bump `generic-array` dependency to v0.14.4

elliptic-curve/Cargo.toml
Expands the list of features that appear in rustdoc documentation published to https://docs.rs/elliptic-curve/ to include all of the newly added features which shipped in v0.11.8.
We'll need to publish a v0.11.9 in order for this to render.
=> elliptic-curve: activate `bits`, `hash2curve`, `voprf` on docs.rs

crypto/Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/LICENSE-MIT, elliptic-curve/src/lib.rs
- Activate `bits`, `hash2curve`, and `voprf` features on docs.rs ([#891])
[#891]: https://github.com/RustCrypto/traits/pull/891
=> elliptic-curve v0.11.9

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/hash2field/expand_msg.rs, elliptic-curve/src/hash2field/expand_msg/xmd.rs, elliptic-curve/src/ops.rs
=> Update to digest 0.10

crypto/Cargo.lock, crypto/Cargo.toml, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/lib.rs
Switching over to making breaking changes again now that #883 is merged.
There are a number of other pent up breaking changes that have been desired which we can now start working on.
=> elliptic-curve: bump version to 0.12 prerelease

elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/nonzero.rs
Because `NonZeroScalar` means we'll never divide by 0, it's possible to make the implementation infallible.
To accomplish this, `CtOption` is removed from the `Invert` trait's signature, and used as the result type for scalars that are potentially zero as part of the blanket impl of `Invert`.
Fixes RustCrypto/elliptic-curves#499
=> elliptic-curve: make `NonZeroScalar::invert` infallible

elliptic-curve/src/sec1.rs
This is more consistent with the `ToEncodedPoint` trait.
=> elliptic-curve: make `ToCompactEncodedPoint` return `CtOption`

.github/workflows/crypto.yml, .github/workflows/password-hash.yml, .github/workflows/workspace.yml, Cargo.lock, crypto/Cargo.lock, crypto/Cargo.toml, crypto/README.md, crypto/src/lib.rs, password-hash/Cargo.toml, password-hash/README.md, password-hash/src/ident.rs, password-hash/src/lib.rs
Leverages the newly stabilized support for panicking in const contexts to replace the hack `const_assert!` macro.
After this, it will also be trivial to bump to the 2021 edition.
=> password-hash: leverage `const_panic`; MSRV 1.57

elliptic-curve/src/ops.rs
Several of the previous bounds are unnecessary for the actual operation performed, which is just `finalize_fixed`.
This commit removes the unneeded bounds.
=> elliptic-curve: simplify `Reduce::from_*_digest_reduce` bounds

password-hash/Cargo.lock, password-hash/Cargo.toml
These were in place to prevent MSRV-related breakages.
Now that `password-hash` has been bumped to a higher MSRV than `base64ct`, it's no longer needed.
=> password-hash: remove `base64ct` version restrictions

elliptic-curve/Cargo.lock
Dependabot wasn't taking care of these since `elliptic-curve` is split out into its own workspace since older MSRV crates can't handle the 2021 edition.
=> elliptic-curve: bump dependencies in Cargo.lock

elliptic-curve/src/hash2curve/group_digest.rs
I encountered quiet the issue:
```rust
fn test<C: GroupDigest>() {
let var: ProjectivePoint<C> =
C::hash_from_bytes::<ExpandMsgXmd<sha2::Sha256>>(&[b"test"], b"test");
}
```
<details><summary>Gives the following error</summary>
```
error[E0308]: mismatched types
--> src/group/elliptic_curve.rs:34:9
|
33 |     let var: ProjectivePoint<C> =
|              ------------------ expected due to this
34 |         C::hash_from_bytes::<ExpandMsgXmd<sha2::Sha256>>(&[b"test"], b"test");
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected associated type, found enum `core::result::Result`
|
= note: expected associated type `<C as GroupDigest>::Output`
found enum `core::result::Result<<C as GroupDigest>::Output, elliptic_curve::Error>`
help: consider constraining …
```
=> Better constraint that `Output` is `ProjectivePoint`

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock
The `master` branch is already the v0.12 prerelease series, however another v0.11 release was cut in #923.
This adds a changelog entry, as well as "yanked" crate markers for releases which depend on `zeroize` v1.5, which #923 downgrades.
=> elliptic-curve: v0.11.10 changelog entry

elliptic-curve/CHANGELOG.md
It looks like the docs.rs build for v0.11.10 failed due to nightly bugs:
https://docs.rs/crate/elliptic-curve/0.11.10/builds/500473
This adds a changelog entry for a v0.11.11 release, which is unchanged from v0.11.10, but released again to trigger a new docs.rs build.
The `master` branch is already the v0.12 prerelease series, so this commit doesn't contain a full release.
=> elliptic-curve: v0.11.11 changelog entry

elliptic-curve/CHANGELOG.md
This was released in #927, and disabled the `bits` feature on docs.rs to work around a nightly breakage building the docs there.
Since `master` is already the v0.12 prerelease series, this commit merely documents the release.
=> elliptic-curve: add v0.11.12 changelog entry

.github/workflows/workspace.yml, cipher/CHANGELOG.md, cipher/Cargo.toml, cipher/src/block.rs, cipher/src/lib.rs
Closes https://github.com/RustCrypto/block-modes/issues/7
=> cipher: restore allocating padded encrypt/decrypt

Cargo.lock, cipher/CHANGELOG.md, cipher/Cargo.lock, cipher/Cargo.toml, cipher/src/lib.rs, crypto-common/CHANGELOG.md, crypto-common/Cargo.toml, crypto-common/src/lib.rs, digest/CHANGELOG.md, digest/Cargo.toml, digest/src/lib.rs, elliptic-curve/Cargo.lock, kem/Cargo.lock
Relevant to #162 
Fixing the `kem` crate would be more difficult. With min versions it even manages to pull `libc v0.1` (sic!). It looks like there are issues in its dependencies which are outside of our org.
=> Fix minimal versions build by using typenum 1.14 or higher

cipher/CHANGELOG.md, cipher/Cargo.lock, cipher/Cargo.toml, cipher/src/block.rs, cipher/src/lib.rs
It's a breaking change, but the method was introduced in today's release, so hopefully it will not affect anyone. I plan to yank `cipher v0.4.1` to prevent further confusion.
=> cipher: rename BlockDecryptMut::decrypt_padded_vec to decrypt_padded_vec_mut

cipher/CHANGELOG.md, cipher/Cargo.lock, cipher/Cargo.toml, cipher/src/lib.rs
The fact that this feature is enabled by default was an oversight.
Unfortunately, it's again a breaking change. It can affect only users of the allocating padded encrypt/decrypt methods. The `p12` crate which hit the previous breaking change [explicitly enables](https://github.com/hjiayz/p12/blob/master/Cargo.toml#L28), so this PR should not cause any issues for it.
=> cipher: do not enable the alloc feature by default

.github/workflows/aead.yml, Cargo.lock, aead/Cargo.toml, aead/src/lib.rs
Continuation of #837.
Allows using `bytes::BytesMut` as an `aead::Buffer`.
=> aead: add optional support for `BytesMut` as a `Buffer`

password-hash/src/salt.rs
Incorporates documentation from the PHC string format specification as to why the given length was chosen
=> password-hash: add docs for `Salt::RECOMMENDED_LENGTH`

password-hash/src/ident.rs, password-hash/src/params.rs, password-hash/tests/hashing.rs, password-hash/tests/password_hash.rs, password-hash/tests/test_vectors.rs
Unifies the `const fn` implementation of `Ident::new` and `TryFrom`, with the former now able to return a result thanks to const panic.
Since `Debug` isn't const-friendly yet and therefore `Result::unwrap` cannot be used in const contexts, adds a `::new_unwrap` function as a stopgap. It performs some pattern matching and uses const panic to handle the `Err` case.
=> password-hash: make `Ident::new` fallible; add `Ident::new_unwrap`

Cargo.lock, crypto/Cargo.toml, password-hash/CHANGELOG.md, password-hash/Cargo.toml, password-hash/src/lib.rs
- Leverage `const_panic`; MSRV 1.57 ([#896])
- Rust 2021 edition upgrade ([#897])
- Make `Ident::new` fallible; add `Ident::new_unwrap` ([#896], [#960])
- Better `Debug`/`Display` impls for `SaltString` ([#804])
- `base64ct` version restrictions ([#914])
[#804]: https://github.com/RustCrypto/traits/pull/804
[#896]: https://github.com/RustCrypto/traits/pull/896
[#897]: https://github.com/RustCrypto/traits/pull/897
[#897]: https://github.com/RustCrypto/traits/pull/897
[#914]: https://github.com/RustCrypto/traits/pull/914
[#960]: https://github.com/RustCrypto/traits/pull/960
=> password-hash v0.4.0

elliptic-curve/Cargo.toml, elliptic-curve/src/public_key.rs
This commit changes the `Serializer` and `Deserializer` impls on the `PublicKey` type to work more like the ones on other types in this crate and its downstream dependencies:
- Use binary DER serialization with binary formats (what it does today)
- Use an upper-case hex serialization of the DER in conjunction with "human readable" formats
Though richer formats exist for this use case (such as `JwkEcKey` which is an existing implementation of JWK), hex-serialized DER is relatively common and easy to work with, and can be decoded easily with online tools such as https://lapo.it/asn1js/
Note that the `Deserialize` impl for `PublicKey` never worked with human-readable formats as it was attempting to deserialize to `&[u8]`, which doesn't work with formats like JSON or TOML because they need an …
=> elliptic-curve: add hex `serde` (de)serializer for `PublicKey`

.github/workflows/elliptic-curve.yml, elliptic-curve/src/public_key.rs
I'm surprised this is implemented as it is, you can't actually use Serde with `PublicKey` without `alloc`. In any case, this is still necessary to make this even compile.
=> Fix compilation with `serde` without `pem`

elliptic-curve/src/ecdh.rs
The purpose of zeroization is to clear the bytes of the shared secret on drop.
However, before this commit `SharedSecret` also had a `Zeroize` impl which could be called before `Drop`.
Used incorrectly, this could potentially erase the shared secret data, which could potentially lead to bugs where that data is used to derive e.g. encryption keys after being zeroed.
This commit removes the `Zeroize` impl to prevent this. Data is still zeroed on drop and it still impls the `ZeroizeOnDrop` trait.
=> elliptic-curve: remove `Zeroize` impl from `ecdh::SharedSecret`

Cargo.lock, elliptic-curve/Cargo.toml
Release notes:
- `ff` v0.12: https://github.com/zkcrypto/ff/blob/main/CHANGELOG.md#0120---2022-05-04
- `group` v0.12: https://github.com/zkcrypto/group/blob/main/CHANGELOG.md#0120---2022-05-04
=> elliptic-curve: bump `ff` + `group` to v0.12

Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, elliptic-curve/tests/pkcs8.rs
Also bumps `pkcs8` to v0.9.0-pre.2.
This should hopefully be the last prerelease before a final release.
=> elliptic-curve: bump `der` to v0.6.0-pre.4

Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/jwk.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/core.rs
Uses the `serdect` crate, which provides constant time-ish serde serializers/deserializers, for impl'ing the `serde::{Deserialize, Serialize}` traits.
=> elliptic-curve: use `serdect` crate

Cargo.lock, elliptic-curve/Cargo.toml
Also cuts a v0.12.0-pre.4 prerelease of `elliptic-curve`
=> elliptic-curve: bump `sec1` dependency to v0.3.0-pre.4

Cargo.lock, elliptic-curve/Cargo.toml
Bumps the following to final release versions:
- `der` v0.6
- `pkcs8` v0.9
- `sec1` v0.3
=> elliptic-curve: bump `der`, `pkcs8`, and `sec1`

Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/ecdh.rs, elliptic-curve/src/secret_key.rs
Adds support for using HKDF to generate key material from an ECDH shared secret using the `hkdf` crate.
Renames the previous `as_bytes` method to `raw_secret_bytes` with a warning that the `extract` method should be preferred instead.
=> elliptic-curve: `ecdh::SharedSecret::extract` HKDF helper

Cargo.lock, crypto/Cargo.toml, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml, elliptic-curve/README.md, elliptic-curve/src/lib.rs
- `ecdh::SharedSecret::extract` HKDF helper ([#1007])
- Bump `digest` dependency to v0.10 ([#883], [#904])
- Make `NonZeroScalar::invert` infallible ([#894])
- `ToCompactEncodedPoint` now returns `CtOption` ([#895])
- Move `hash2field` into `hash2curve` module ([#903])
- Bump `ff` and `group` dependencies to v0.12 ([#994])
- Use `serdect` crate ([#996])
- Replace `AlgorithmParamters` with `AssociatedOid` ([#1001])
- Bump `crypto-bigint` dependency to v0.4 ([#1005])
- Bump `der` dependency to v0.6 ([#1006])
- Bump `pkcs8` dependency to v0.9 ([#1006])
- Bump `sec1` dependency to v0.3 ([#1006])
- `Zeroize` impl from `ecdh::SharedSecret` ([#978])
[#883]: https://github.com/RustCrypto/formats/pull/883
[#894]: https://github.com/RustCrypto/formats/pull/894
[#895]: …
=> elliptic-curve v0.12.0

Cargo.lock, kem/CHANGELOG.md, kem/Cargo.toml
- Generic `SharedSecret` type ([#982])
- `EncappedKey::EncappedKeySize` associated constant ([#982])
- Rename `EncappedKey::NSecret` => `EncappedKey::SharedSecretSize` ([#982])
- Add `EncappedKey::{from_bytes, as_bytes}` methods ([#982])
[#982]: https://github.com/RustCrypto/traits/pull/982
=> kem v0.2.0

elliptic-curve/src/lib.rs, elliptic-curve/src/weierstrass.rs
Adds a generic implementation of the complete addition formulas from [Renes-Costello-Batina 2015] adapted from @str4d's original implementation for the `p256` crate:
https://github.com/RustCrypto/elliptic-curves/pull/15
This implementation has subsequently been copied-and-pasted into the `p384` crate (see https://github.com/RustCrypto/elliptic-curves/pull/565), hence the motivation to make it generic and extract it somewhere that it can be reused.
The API exposed is fairly low-level, however it's difficult to better encapsulate it without making breaking changes to the `elliptic-curve` crate. Thus this PR opts to provide an initial low-level generic implementation with the goal of exploring removing more duplication with a higher-level API as followup work to be done at a time when …
=> elliptic-curve: generic impl of complete prime order formulas

Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml
- `impl_field_element!` macro ([#1021])
- Generic impl of complete prime order formulas ([#1022])
- Bump `crypto-bigint` to v0.4.4 ([#1018], [#1020])
[#1018]: https://github.com/RustCrypto/formats/pull/1018
[#1020]: https://github.com/RustCrypto/formats/pull/1020
[#1021]: https://github.com/RustCrypto/formats/pull/1021
[#1022]: https://github.com/RustCrypto/formats/pull/1022
=> elliptic-curve v0.12.1

crypto-common/Cargo.toml
Transitively enables `rand_core/getrandom`, making it possible to access `crypto_common::rand_core::OsRng`.
=> crypto-common: add `getrandom` feature

crypto-common/Cargo.toml, digest/Cargo.toml, password-hash/Cargo.toml
This style is consistent with other crates in this repo (and elsewhere in the project), for example `cipher`.
=> Make Cargo.toml comments on optional dependencies consistent

Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/dev.rs, elliptic-curve/src/macros.rs
=> elliptic-curve: bump `crypto-bigint` to v0.4.8

Cargo.lock, aead/Cargo.toml, aead/src/lib.rs, aead/src/stream.rs, crypto/Cargo.toml
Replaces the `NewAead` trait with the same-shaped `KeyInit` trait.
=> aead: use `crypto-common`

aead/Cargo.toml, aead/src/lib.rs
Adds a `getrandom` feature which activates `crypto-common/getrandom` and makes it simple to access `OsRng` without importing an additional dependency.
=> aead: `getrandom` eature

aead/src/dev.rs
It was referencing the now-removed `NewAead` trait
=> aead: fix `new_test!` macro

Cargo.lock, crypto-common/CHANGELOG.md, crypto-common/Cargo.toml
- Support on-label MSRV ([#1049])
[#1049]: https://github.com/RustCrypto/traits/pull/1049
=> crypto-common v0.1.5

cipher/src/lib.rs, crypto-common/src/lib.rs
Moves `ParBlocks`/`ParBlocksSizeUser` from the `cipher` crate so it can be reused in the `universal-hash` crate (see #965, #1051).
The `cipher` crate re-exports them in an API-compatible way, so this is not a breaking change.
=> crypto-common: move `ParBlocks*` from `cipher` crate

Cargo.lock, cipher/CHANGELOG.md, cipher/Cargo.toml, crypto-common/CHANGELOG.md, crypto-common/Cargo.toml
- Move `ParBlocks`/`ParBlocksSizeUser` from `cipher` crate ([#1052])
[#1052]: https://github.com/RustCrypto/traits/pull/1052
=> crypto-common v0.1.6

.github/workflows/universal-hash.yml, Cargo.lock, README.md, crypto/Cargo.toml, universal-hash/Cargo.toml, universal-hash/README.md, universal-hash/src/lib.rs
Includes changes originally introduced in #965:
> The new API uses approach of emulating rank-2 closures previously introduced in cipher v0.4.
>
> ~~Also moves `ParBlocksSizeUser` and `ParBlocks` from `cipher` to `crypto-common`.~~
This PR rebases/squashes the changes in preparation for cutting a prerelease.
~~It also includes the following releases to accommodate the move of `ParBlocks`/`ParBlocksSizeUser`:~~
- ~~`cipher` v0.4.4~~
- ~~`crypto-common` v0.1.6~~
Edit: moved the `ParBlocks`/`ParBlocksSizeUser` changes to #1052 and #1053
=> universal-hash v0.5.0-pre

universal-hash/src/lib.rs
This method was used by the `aes-gcm-siv` crate to handle a case where consuming `self` is problematic and borrowing `&mut self` is much more straightforward. It seems we've had several cases like this pop up with similar methods that were removed in other crates like `block-modes` and `digest`.
The method is provided but bounded on `Clone + Reset`, with the latter sourced from `crypto-common`.
=> universal-hash: add back `finalize_reset`

elliptic-curve/src/secret_key.rs
The `zeroize` feature flag has been removed, zeroization on drop is now done by default.
=> elliptic-curve: fix outdated doc

Cargo.lock, aead/CHANGELOG.md, aead/Cargo.toml, crypto/Cargo.toml
- Optional support for `BytesMut` as a `Buffer` ([#956])
- `getrandom` feature ([#1042])
- Replace `NewAead` trait with `KeyInit` trait from `crypto-common` ([#1033])
- Rust 2021 edition upgrade; MSRV 1.56+ ([#1044])
[#956]: https://github.com/RustCrypto/traits/pull/956
[#1033]: https://github.com/RustCrypto/traits/pull/1033
[#1042]: https://github.com/RustCrypto/traits/pull/1042
[#1044]: https://github.com/RustCrypto/traits/pull/1044
=> aead v0.5.0

universal-hash/src/lib.rs
Originally suggested by @str4d here:
https://github.com/RustCrypto/traits/pull/965#discussion_r857126434
The use case is ensuring unbuffered processing of the input AEAD message body when the AAD does not line up with the number of blocks it's processing in parallel.
This number of blocks can be input from the start of the message body to finish completely filling the buffer, ensuring all subsequent processing occurs at the start of the buffer.
=> universal-hash: add `UhfBackend::blocks_needed_to_align`

Cargo.lock, crypto/Cargo.toml, universal-hash/CHANGELOG.md, universal-hash/Cargo.toml
- `UhfBackend` trait ([#1051], [#1059])
- `UhfClosure` trait ([#1051])
- `UniversalHash::update_with_backend` method ([#1051])
- Replace `NewUniversalHash` trait with `KeyInit` from `crypto-common` ([#1051])
- Source `Block` and `Key` types from `crypto-common` ([#1051])
- `UniversalHash::update` is now provided takes a slice of blocks ([#1051])
- `UniversalHash::finalize` now returns a `Block` ([#1051])
- Rust 2021 edition; MSRV 1.56 ([#1051])
- `Ouput` replaced by `Block` ([#1051])
- `UniversalHash::reset` replaced with `Reset` trait from `crypto-common` ([#1051])
[#1051]: https://github.com/RustCrypto/traits/pull/1051
[#1059]: https://github.com/RustCrypto/traits/pull/1059
=> universal-hash v0.5.0

elliptic-curve/src/sec1.rs
Adds `GenericArray` type aliases for representing compressed/uncompressed SEC1 points, along with type aliases for calculating their sizes.
=> elliptic-curve: add aliases for SEC1 compressed/uncompressed points

Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml
- Aliases for SEC1 compressed/uncompressed points ([#1067])
- `arithmetic` + `serde` feature combo ([#1066])
[#1066]: https://github.com/RustCrypto/traits/pull/1066
[#1067]: https://github.com/RustCrypto/traits/pull/1067
=> elliptic-curve v0.12.3

Cargo.lock, aead/CHANGELOG.md, aead/Cargo.toml
- `AeadCore::generate_nonce` ([#1073])
[#1073]: https://github.com/RustCrypto/traits/pull/1073
=> aead v0.5.1

.github/workflows/crypto.yml, Cargo.lock, crypto/Cargo.toml, crypto/src/lib.rs
It's been merged into `digest`
=> crypto: remove `crypto-mac` crate dependency

Cargo.lock, crypto/CHANGELOG.md, crypto/Cargo.toml
- Re-export `crypto-common` as `common` ([#1076])
- Bump `aead` to v0.5 ([#1058])
- Bump `cipher` to 0.4 ([#951])
- Bump `digest` dependency to v0.10 ([#850])
- Bump `elliptic-curve` to v0.12 ([#1009])
- Bump `password-hash` to v0.4 ([#961])
- Bump `signature` to v1.5 ([#867])
- Bump `universal-hash` to v0.5 ([#1061])
- `mac` feature: merged into `digest` ([#1075])
[#850]: https://github.com/RustCrypto/traits/pull/850
[#867]: https://github.com/RustCrypto/traits/pull/867
[#951]: https://github.com/RustCrypto/traits/pull/951
[#961]: https://github.com/RustCrypto/traits/pull/961
[#1009]: https://github.com/RustCrypto/traits/pull/1009
[#1058]: https://github.com/RustCrypto/traits/pull/1058
[#1061]: https://github.com/RustCrypto/traits/pull/1061
[#1075]: …
=> crypto v0.4.0

.github/workflows/signature.yml, Cargo.lock, crypto/Cargo.toml, signature/Cargo.toml, signature/README.md, signature/async/Cargo.toml, signature/async/src/lib.rs, signature/derive/Cargo.toml, signature/derive/src/lib.rs, signature/src/lib.rs
Since we have PRs that demand an MSRV bump (#1080), bumps the crate's edition to the latest, which requires MSRV 1.56.
=> signature: Rust 2021 edition upgrade; MSRV 1.56

signature/src/keypair.rs, signature/src/lib.rs
Adds a trait for types which represent a combination of both a signing key and verifying key as is common in many digital signature systems.
The `Keypair` name follows Rust standard capitalization rules for the closed compound word "keypair" as commonly used in cryptography.
=> signature: add `Keypair` trait

signature/derive/CHANGELOG.md
- Rust 2021 edition upgrade; MSRV 1.56 ([#1081])
[#1081]: https://github.com/RustCrypto/traits/pull/1081
=> signature_derive v1.0.0-pre.5

Cargo.lock, crypto/Cargo.toml, signature/CHANGELOG.md, signature/Cargo.toml, signature/async/Cargo.toml
- `Keypair` trait ([#1080])
- Rust 2021 edition upgrade; MSRV 1.56 ([#1081])
- Bump `signature_derive` dependency to v1.0.0-pre.5 ([#1082])
- Bump `hex-literal` dependency to v0.3 ([#1083])
[#1080]: https://github.com/RustCrypto/traits/pull/1080
[#1081]: https://github.com/RustCrypto/traits/pull/1081
[#1082]: https://github.com/RustCrypto/traits/pull/1082
[#1083]: https://github.com/RustCrypto/traits/pull/1083
=> signature v1.6.0

Cargo.lock, signature/async/CHANGELOG.md, signature/async/Cargo.toml
- `AsyncKeypair` trait ([#1085])
- Bump minimum `signature` requirement to v1.6 ([#1084])
[#1084]: https://github.com/RustCrypto/traits/pull/1084
[#1085]: https://github.com/RustCrypto/traits/pull/1085
=> async-signature v0.2.0

kem/Cargo.toml, kem/tests/hpke.rs
HPKE tests in KEM compile again. Addresses problem noted in #1089
=> KEM: Updated HPKE deps for testing

Cargo.lock, signature/derive/Cargo.toml, signature/derive/src/lib.rs
It wasn't actually being used for anything structural, but rather for its higher-level proc macro API and testing facilities.
However, both of those aren't too hard to replace, using `syn` for testing (via `parse_quote!`)
=> signature_derive: remove `synstructure` dependency

elliptic-curve/src/public_key.rs
Add `PublicKey::to_sec1_bytes` as opposite of `PublicKey::from_sec1_bytes` (closes https://github.com/RustCrypto/traits/issues/1101)
=> elliptic-curve: add to_sec1_bytes

.github/workflows/signature.yml, signature/Cargo.toml, signature/src/hazmat.rs, signature/src/lib.rs
Adds a `hazmat` module gated under a newly added `hazmat-preview` feature which calls out the relevant functionality as subject to change with minor versions.
It adds the following traits:
- `PrehashSigner`
- `PrehashVerifier`
These APIs accept the digest to be signed/verified as a raw byte slice. This comes with potential misuses like failing to use a cryptographically secure hash function as the `prehash`, which could enable existential forgeries of signatures, hence gating it under a `hazmat-preview` feature and placing it in a `hazmat` module.
Note that we previously explored APIs like this for `DigestSigner`. They were removed in RustCrypto/signatures#17 due to the afforementioned misuse potential.
However, these APIs are occasionally needed for implementing protocols that use …
=> signature: add `hazmat-preview` feature

Cargo.lock, signature/Cargo.toml, signature/derive/CHANGELOG.md, signature/derive/Cargo.toml
- `DigestSigner`/`DigestVerifier` support ([#1103])
- `synstructure` dependency ([#1100])
[#1100]: https://github.com/RustCrypto/traits/pull/1100
[#1103]: https://github.com/RustCrypto/traits/pull/1103
=> signature_derive v1.0.0-pre.6

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml
- `hazmat-preview` feature with `PrehashSigner`/`PrehashVerifier` traits ([#1099])
- Bump `signature_derive` to v1.0.0-pre.6 ([#1104])
[#1099]: https://github.com/RustCrypto/traits/pull/1099
[#1104]: https://github.com/RustCrypto/traits/pull/1104
=> signature v1.6.1

digest/README.md
Closes #1072 
Since the `blake2` crate is currently not in the best state, the updated examples use `sha2` instead of it.
=> digest: update examples in readme

signature/async/src/lib.rs, signature/src/keypair.rs
The Keypair trait might be useful for representing relationship between
DigestSigner and DigestVerifier, RandomizedSigner and
RandomizedVerifier, etc. in addition to just Signer/Verfifier pair.
Relax type boundaries for the Keypair and AsyncKeypair traits.
Fixes #1106
=> signature: relax `Keypair` type bounds

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml
- Relax `Keypair` type bounds ([#1107])
[#1107]: https://github.com/RustCrypto/traits/pull/1107
=> signature v1.6.2

signature/async/src/lib.rs
As of #1107 this trait is shaped the same as `Keypair`, so there's no need for it to continue to exist.
It will be removed in the next breaking release.
=> async-signature: deprecate `AsyncKeypair`

Cargo.lock, signature/async/CHANGELOG.md, signature/async/Cargo.toml
- Relax `AsyncKeypair` bounds ([#1107])
- Deprecate `AsyncKeypair` ([#1112])
[#1107]: https://github.com/RustCrypto/traits/pull/1107
[#1112]: https://github.com/RustCrypto/traits/pull/1112
=> async-keypair v0.2.1

.github/workflows/signature.yml, signature/derive/src/lib.rs
The derived code in the test fixtures is incorrect.
Likewise, it seems there wasn't a proper CI job for this crate. This commit also includes fixes which ensure `signature_derive`'s tests are run in CI.
=> signature_derive: fix `Digest*` trait derivation

signature/derive/src/lib.rs
Retains the original where bounds provided in a type declaration.
Additionally this adds `__` to the names of the type parameters used by the `impl` to avoid clashes with ones that might be specified for a given type.
=> signature_derive: fix support for `where` bounds

Cargo.lock, signature/Cargo.toml, signature/derive/CHANGELOG.md, signature/derive/Cargo.toml
- Support for `where` bounds ([#1118])
[#1118]: https://github.com/RustCrypto/traits/pull/1118
=> signature_derive v1.0.0-pre.7

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml
- Bump `signature_derive` to v1.0.0-pre.7 ([#1119])
[#1119]: https://github.com/RustCrypto/traits/pull/1119
=> signature v1.6.3

.github/dependabot.yml
Add Dependabot configuration to automatically open PRs for outdated actions.
Inspired by https://github.com/RustCrypto/hashes/pull/410#issuecomment-1252658128.
=> extend Dependabot configuration to keep GitHub Actions up to date

signature/src/hazmat.rs
Expand hazmat with the RandomizedPrehashSigner trait, declaring fn sign_prehash_with_rng(). This is necessary for hazmat implementation for the RSA PSS keys.
Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@linaro.org>
=> signature: expand hazmat to cover sign-with-rng case

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml
Without this, `sec1::Error` does not implement `std::error::Error`.
=> Forward `std` feature to `sec1`

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml
- `RandomizedPrehashSigner` trait in `hazmat` module ([#1130])
[#1130]: https://github.com/RustCrypto/traits/pull/1130
=> signature v1.6.4

signature/src/encoding.rs
Unfortunately the `Default` impl on `core` array types is still problematic here:
```
error[E0277]: the trait bound `[u8; 64]: Default` is not satisfied
--> ed25519/src/lib.rs:339:17
|
339 |     type Repr = SignatureBytes;
|                 ^^^^^^^^^^^^^^ the trait `Default` is not implemented for `[u8; 64]`
```
=> signature: remove `Default` bound on `SignatureEncoding::Repr`

signature/src/encoding.rs
Without a `Default` bound (#1143) there's little purpose to having an `AsMut` bound on `Repr`, which would allow `Default` to construct an empty bytestring and `AsMut` used to write into it.
Given there isn't an obvious use case, fewer bounds are better.
=> signature: remove `AsMut` bound on `Repr`

signature/Cargo.toml, signature/src/signer.rs
`rand_core` v0.6.4 added an auto-impl'd `CryptoRngCore` marker trait for types which impl `CryptoRng + RngCore` which is slightly more convenient and less verbose.
This commit changes to using `&mut impl CryptoRngCore` as proposed in #1087. This hopefully strikes a balance between least surprise and minimal required syntax, namely &mut references are reusable and don't
require knowledge of the blanket impl of `RngCore` for `&mut R: RngCore`
=> signature: use `&mut impl CryptoRngCore` RNG arguments

signature/src/encoding.rs
Removes the `from_bytes` and `to_boxed_slice` methods, as `TryFrom` and `to_vec().into_boxed_slice()` provide equivalent functionality.
[Discussion](https://github.com/RustCrypto/traits/pull/1141#discussion_r1008941766)
=> signature: simplify encoding trait

signature/src/hazmat.rs
In #1147, other usages of a CSRNG were changed to use `&mut impl CryptoRngCore`. However, `RandomizedPrehashSigner` was not updated accordingly.
This commit updates it as well.
=> signature: update remaining use of `CryptoRng + RngCore`

elliptic-curve/src/hash2curve/osswu.rs
Apparently this was need for https://github.com/RustCrypto/elliptic-curves/pull/600. It will also be necessary for P-512. I assume this is a breaking change?
=> elliptic-curve: allow bigger `c1` constant in `OsswuMapParams`

Cargo.lock, crypto/Cargo.toml, elliptic-curve/Cargo.toml
Breaking changes were introduced in #1024, so this bumps the crate version to v0.13.0-pre to note that happened.
Note that there is no crate release associated with this version. When a crate release occurs, it will be bumped to `-pre.0`.
=> Bump `elliptic-curve` to v0.13.0-pre

signature/src/hazmat.rs, signature/src/signer.rs
As discussed in #1148, adopts a generic paramater `R` for RNGs, and also adds a `?Sized` bound which permits the use of trait objects.
=> signature: use `R: CryptoRngCore + ?Sized` for RNG params

signature/src/encoding.rs
This is helpful for "no panic" profiles.
The `Error` type is deliberately left opaque, which means that `From`/`Into` still work via blanket `TryFrom`/`TryInto` impls with `Error = Infallible`.
The `SignatureEncoding::to_bytes` method still provides infallible serialization.
=> signature: fallible encoding support

elliptic-curve/src/scalar/nonzero.rs
This implements `Serialize` and `Deserialize` for `NonZeroScalar`.
The use-case here is to prevent having to hand-write this for types containing `NonZeroScalar`, which then have to ensure checking for the zero point themselves.
=> Implement serde for `NonZeroScalar`

cipher/src/stream.rs
There's an unnecessary initializing of a `Block` when it's unused; causing an allocation and immediate de-allocation of the instance when tail is not greater than 0.
This lets us avoid quite a lot of allocations when this cipher is used a lot.
=> Don't unnecessarily initialize a block when unused

signature/src/encoding.rs
Previously it mandated the use of `signature::Error` as the associated `Error` type for `TryFrom<&'a [u8]>`.
This isn't strictly necessary though. Downstream impls should be able to use their own error type.
It's also inconsistent with the `TryInto` bounds, which allow any error type.
=> signature: remove `Error` bound on `SignatureEncoding`

elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/non_identity.rs, elliptic-curve/src/public_key.rs
It would be nice to implement math that is generic over both projective and affine points with a common prime marker trait, see https://github.com/zkcrypto/group/issues/43.
I believe in the meantime we could use `Into<ProjectivePoint<C>> where C: PrimeCurve`.
In the future I would like to implement the following math (which I believe are correct):
- Multiplication between `NonIdentity` points.
- Multiplication with `NonZeroScalar`.
- Introduce `fn add_identity(&self) -> NonIdentity`.
Additionally the `PublicKey` type has to be adjusted to return `NonIdentity` when appopriate, which is a breaking change.
On a last point I would like to suggest renaming this to `NonIdentityPoint`, which would be more in line with `NonZeroScalar`.
Fixes #1170.
=> Implement `NonIdentity`

signature/src/hazmat.rs, signature/src/signer.rs
This reverts commit b12237e540df00cdd2949cf8f3d996fb1d766a1c.
As further discussed in #1148, passing a trait object to `&mut impl CryptoRngCore` is possible by mutably borrowing it, and upstream changes to `CryptoRng` should eliminate the requirement for the `?Sized` bound.
=> Revert "signature: use `R: CryptoRngCore + ?Sized` (#1167)"

elliptic-curve/src/lib.rs, elliptic-curve/src/point.rs, elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/public_key.rs
Reflects that the type represents a non-identity curve point.
cc @daxpedda
=> elliptic-curve: move `NonIdentity` under `point`

Cargo.lock, crypto/Cargo.toml, password-hash/Cargo.toml, password-hash/src/lib.rs, password-hash/src/traits.rs, password-hash/tests/hashing.rs
Previously `PasswordHash::hash_password` and `PasswordHash::generate` took `&str` for `Salt`, however this is a bit of a confusing API because the first thing it does is attempt to convert to a `Salt` which upholds several invariants including "B64" encoding.
This change makes the `Salt` parameter explicit so it's clear what type is responsible for checking those invariants.
Closes #1029.
=> password-hash: use `Salt` type with `PasswordHasher`

.github/workflows/elliptic-curve.yml, Cargo.lock, Cargo.toml, crypto/Cargo.toml, elliptic-curve/Cargo.toml, elliptic-curve/README.md, elliptic-curve/src/dev.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/secret_key.rs
This also moves `elliptic-curve` out of the toplevel workspace since `crypto-bigint` now uses namespaced features, which are incompatible with older MSRV crates.
=> elliptic-curve: bump `crypto-bigint` to v0.5.0-pre.1; MSRV 1.61

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/secret_key.rs
From https://rust-lang.github.io/api-guidelines/naming.html
> In UpperCamelCase, acronyms and contractions of compound words count
> as one word: use Uuid rather than UUID, Usize rather than USize or
> Stdin rather than StdIn.
Based on the `Usize` example, it's pretty clear we should be using `Uint` rather than `UInt`.
This is also consistent with `crypto-bigint`:
https://github.com/RustCrypto/crypto-bigint/pull/143
=> elliptic-curve: rename `Curve::UInt` => `Curve::Uint`

elliptic-curve/Cargo.toml
Activates the `alloc` and `std` features in more dependencies, but only if they're explicitly linked otherwise
=> elliptic-curve: use weak feature activation

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/jwk.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/point.rs, elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs
Replaces manual `cfg(doc(...))` annotations with `doc_auto_cfg`, which populates them automatically
=> elliptic-curve: use `doc_auto_cfg`

elliptic-curve/Cargo.toml, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, elliptic-curve/tests/pkcs8.rs
This removes a hard dependency on the `der` crate.
With weak feature activation it now becomes possible to pull in the `der` crate transitively via the `pkcs8` and `sec1` crates.
=> elliptic-curve: remove direct `der` crate dependency

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/jwk.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/core.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/sec1.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs
Consolidates the following former three traits into a single trait:
- `AffineArithmetic`
- `ProjectiveArithmetic`
- `ScalarArithmetic`
It doesn't make sense to impl one of these traits without impl'ing them all, so this commit combines them into a single trait.
=> elliptic-curve: consolidate `CurveArithmetic` trait

elliptic-curve/src/ecdh.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/osswu.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/secret_key.rs
Adopts the following lints:
```rust
#![warn(
clippy::mod_module_files,
clippy::unwrap_used,
missing_docs,
rust_2018_idioms,
unused_lifetimes,
unused_qualifications
)]
```
=> elliptic-curve: lint improvements

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs
Adds a trait for performing scalar multiplication by the generator point, which may use optimizations (e.g. precomputed tables) when available
=> elliptic-curve: add `MulByGenerator` trait

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/point.rs
This trait is useful for generic point compression implementations which are also useful for a generic implementation of recoverable ECDSA signing, which presently isn't possible due to an inability to query this information
=> elliptic-curve: add `AffineYIsOdd` trait

elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/invert.rs
Extracted from this implementation in the `p256` crate:
https://github.com/RustCrypto/elliptic-curves/blob/1a03b8a/p256/src/arithmetic/scalar.rs#L145-L194
=> elliptic-curve: add generic implemenation of Stein's algorithm

.github/workflows/elliptic-curve.yml, elliptic-curve/src/ecdh.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/sec1.rs, elliptic-curve/src/secret_key.rs
Ensures `cargo doc` builds successfully
=> elliptic-curve: test docs in CI

elliptic-curve/src/secret_key.rs
Was formerly `SecretKey::to_pem` which is ambiguous as to what PEM serialization is used. PKCS#8 is also possible (and preferred).
=> elliptic-curve: rename `SecretKey::to_sec1_pem`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs, elliptic-curve/src/secret_key.rs
This is a slightly more descriptive name: `ScalarPrimitive` is a scalar type with primitive functionality.
=> elliptic-curve: rename `ScalarCore` to `ScalarPrimitive`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/primitive.rs
Bounds `CurveArithmetic::Scalar` on this trait and uses it to simplify conversions to/from `ScalarPrimitive`.
Also adds bounds to ensure `ScalarPrimitive` conversions are bidirectional.
=> elliptic-curve: mandate `scalar::FromUintUnchecked`

elliptic-curve/Cargo.toml, elliptic-curve/src/ecdh.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs, elliptic-curve/src/secret_key.rs
Marker trait for `CryptoRng + RngCore`; added in `rand_core` v0.6.4
=> elliptic-curve: use `CryptoRngCore` trait

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/invert.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs
Adds support for variable-time inversions of `NonZeroScalar`, which allows the inversion to be infallible.
An example use case is ECDSA verification, where the `s` component of the signature needs to be inverted.
=> elliptic-curve: add `NonZeroScalar::invert_vartime`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/blinded.rs, elliptic-curve/src/scalar/invert.rs, elliptic-curve/src/scalar/nonzero.rs
Adds a scalar type with random blinding.
It implements `Invert` using Stein's algorithm which runs in variable time, but masks the value first with multiplication.
This is useful for embedded devices where it can save the full cost of an inversion.
https://link.springer.com/article/10.1007/s13389-016-0135-4
=> elliptic-curve: add `BlindedScalar`

.github/workflows/signature.yml, signature/README.md, signature/async/src/lib.rs, signature/src/encoding.rs, signature/src/error.rs, signature/src/hazmat.rs, signature/src/lib.rs, signature/src/prehash_signature.rs, signature/src/signer.rs, signature/src/verifier.rs
Replaces manual (redundant) feature annotations with automatic feature documentation.
This will hopefully be stable soon as `#[doc(auto_cfg)]`
=> signature: use `doc_auto_cfg`

Cargo.lock, crypto/Cargo.toml, signature/CHANGELOG.md, signature/Cargo.toml, signature/LICENSE-MIT, signature/async/Cargo.toml, signature/derive/CHANGELOG.md, signature/derive/Cargo.toml, signature/src/lib.rs
- `SignatureEncoding` trait as a replacement for `Signature` trait and the now removed `AsRef<[u8]>` bound on signatures ([#1141])
- New `Keypair` trait which returns owned keys instead of borrowed ([#1141])
- `derive-preview` has been renamed to `derive` and stabilized ([#1141])
- `digest-preview` renamed to `digest`, still unstable ([#1210])
- `hazmat-preview` feature stabilized and removed, always on ([#1141])
- `rand-preview` renamed to `rand_core`, still unstable ([#1210])
- `std` feature is no longer enabled by default ([#1141])
- Old `Keypair` trait renamed to `KeypairRef` ([#1141])
- Signature generic parameter removed from `Keypair`/`KeypairRef` ([#1141])
- Use `&mut impl CryptoRngCore` RNG arguments ([#1147])
- `Signature` trait - replaced by `SignatureEncoding` ([#1141])
- …
=> signature v2.0.0

Cargo.lock, signature/async/CHANGELOG.md, signature/async/Cargo.toml
- Bump `signature` to v2 ([#1141], [#1211])
- `AsyncKeypair` is no longer needed due to `signature` v2 bounds changes ([#1141])
[#1141]: https://github.com/RustCrypto/traits/pull/1141
[#1211]: https://github.com/RustCrypto/traits/pull/1211
=> async-signature v0.3.0

signature/async/Cargo.toml
It uses the `digest` feature, which means version updates need to be coordinates around minor versions.
=> async-signature: fix `signature` version requirement

kem/README.md
This seems to have originally come from the `signature` crate
=> kem: remove copypasta from README.md

elliptic-curve/src/lib.rs, elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/public_key.rs
Follow-up to #1176.
IANAC, as far as I understand multiplying a non-zero-scalar with a non-identity-point can never yield the identity-point.
Also realized that I forgot to make the type public :sweat_smile:.
=> Expand `NonIdentity` usage

elliptic-curve/src/point.rs
This is useful for supporting multiple potential `Double` implementations in generic code.
See RustCrypto/elliptic-curves#728 for an example.
=> elliptic-curve: add `point::Double`

elliptic-curve/src/dev.rs, elliptic-curve/src/field.rs, elliptic-curve/src/jwk.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/point.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs, elliptic-curve/src/sec1.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, elliptic-curve/src/voprf.rs, elliptic-curve/tests/pkcs8.rs, elliptic-curve/tests/secret_key.rs
Previously `FieldBytes` was defined in terms of `C::Uint::ByteSize`, which lead to it being improperly sized for curves with unusual modulus sizes like P-224 and P-521 (which aren't multiples of 64).
This commit adds an associated `C::FieldBytesSize` which makes it possible to specifically define the size of a serialized field element. The previous `FieldSize<C>` type alias is retained as `FieldBytesSize`, which handles specifying that the associated type should be accessed using `Curve::FieldBytesSize`.
To handle potential discrepancies between `C::Uint::ByteSize` and `C::FieldBytesSize`, provided `Curve::decode_field_bytes` and `Curve::encode_field_bytes` methods have been added for handling decoding/encoding serialized field elements to/from `C::Uint`.
The methods use a default big …
=> elliptic-curve: refactor field element decoding/encoding

elliptic-curve/src/jwk.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs
Uses the newly added support for interpolating variables in format strings instead of passing them as arguments.
=> elliptic-curve: interpolate variables in format strings

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/invert.rs, elliptic-curve/src/scalar/primitive.rs
Eliminates a bespoke point solution trait with a standard core trait.
Since `C::Uint` already bounds on `ShrAssign<usize>` this should be fairly trivial to support, even in generic code.
=> elliptic-curve: replace `Shr1` with `ShrAssign`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs
Gets rid of re-exports at the toplevel for modules that are newly `pub` to avoid polluting the namespace.
Only the `AffinePoint`, `ProjectivePoint`, and `Scalar` re-exports are retained.
=> elliptic-curve: fewer toplevel re-exports

Cargo.lock, aead/Cargo.toml, aead/src/lib.rs
[`arrayvec`](https://crates.io/crates/arrayvec) is a popular alternative to the `heapless` crate; it has over 65 million all-time downloads and is used in several high-profile crates.
I've added an `arrayvec` feature to `aead`. When enabled, the `aead::Buffer` trait is implemented for [`ArrayVec<u8, N>`](https://docs.rs/arrayvec/0.7.2/arrayvec/struct.ArrayVec.html).
This usage is modeled off of the [`heapless` example](https://github.com/RustCrypto/AEADs/blob/master/aes-gcm-siv/src/lib.rs#L55-L78) from the `aes-gcm-siv` crate documentation.
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
use aes_gcm_siv::{
aead::{AeadInPlace, KeyInit, OsRng, arrayvec::ArrayVec},
Aes256GcmSiv, Nonce, // Or `Aes128GcmSiv`
};
let key = Aes256GcmSiv::generate_key(&mut OsRng);
let cipher = …
```
=> Add support for `arrayvec` in `aead`

elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/scalar/nonzero.rs
Removes all methods from `Reduce` except the newly renamed `Reduce::reduce` (formerly `from_uint_reduced`).
This follows #1220 which changed APIs to handle discrepancies between the serialized size of the big integer type used to represent field elements and the on-the-wire serialization which respects the size of the curve's field modulus and order.
=> elliptic-curve: remove `Reduce` methods

elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/secret_key.rs
Formerly `::as_scalar_core`. Follows the renaming of `ScalarCore` => `ScalarPrimitive`.
=> elliptic-curve: rename `SecretKey::as_scalar_primitive`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs
As a replacement for the previous methods on `Reduce` which take bytes as input, this adds a new curve-specific method for reducing from bytes to a field element.
Bytes is defined as an associated type rather than inferred from the unsigned integer parameter. This is because the integer size may not map exactly to the size of the input, especially for wide reductions.
Bytes are interpreted according to curve-specific rules.
=> elliptic-curve: add (back) reduction from bytes

elliptic-curve/src/scalar/nonzero.rs
It was previously hardcoded to `FieldBytes<C>` which means it won't work for "wide" reductions.
This propagates it to match the `Reduce` impls on `Scalar<C>`.
=> elliptic-curve: propagate `Reduce::Bytes` for `NonZeroScalar` impls

elliptic-curve/src/voprf.rs
See https://github.com/cfrg/draft-irtf-cfrg-voprf/pull/371.
We should probably at least wait until this is merged upstream.
Cc @kevinlewi.
=> Update VOPRF identifier type

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/point.rs
See RustCrypto/elliptic-curves#50 for some historic context.
After being able to get by on `AffineXCoordinate` for generic ECDH and ECDSA, #1199 added an `AffineYIsOdd` trait which was needed to enable the generic ECDSA implementation in the `ecdsa` crate to compute the "recovery ID" for signatures (which is effectively point compression for the `R` curve point).
This commit consolidates `AffineXCoordinate` and `AffineYIsOdd` into an `AffineCoordinates` trait.
Some observations since prior discussion in
RustCrypto/elliptic-curves#50:
- Access to coordinates is through bytes, namely `FieldBytes`. This is so as to avoid exposing a crate's field element type. This approach isn't type safe (base field elements and scalar field elements share the same serialization) but does make ECDSA's weird …
=> elliptic-curve: consolidate `AffineCoordinates` trait

elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2curve/hash2field.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
After https://github.com/RustCrypto/traits/pull/1175 got merged I attempted to go ahead and update voprf and opaque-ke, but quickly hit the same problem that required https://github.com/RustCrypto/traits/pull/876.
The change to the OPRF ID now being a string instead of a byte made it impossible to generate a fixed size array to hold the DST. So I decided to apply the same solution I did in https://github.com/RustCrypto/traits/pull/876.
There are only two changes:
- All hash2curve APIs now take `&[&[u8]]` instead of `&[u8]` as the `dst` parameter.
- `ExpandMsgXmd` now requires `Default + FixedOutput + HashMarker` instead of `Digest`.
=> elliptic-curve: Allow multiple `dst`s in the hash2curve API

elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/invert.rs, elliptic-curve/src/scalar/nonzero.rs
Adds support for optimized variable-time inversions via the `Invert` trait.
By default, the implementation uses a constant-time inversion by calling `Invert::invert`.
=> elliptic-curve: add `Invert::invert_vartime`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs
Previously there was a blanket impl for types which impl `ff::Field`, however this precludes implementations being able to define their own `Invert::inert_vartime`.
=> elliptic-curve: remove blanket impl for `Invert`

elliptic-curve/Cargo.toml, elliptic-curve/src/public_key.rs
Previously the `Serialize`/`Deserialize` impls for `PublicKey` were gated on both the `pkcs8` and `serde` features being enabled, which is potentially confusing.
`PublicKey` uses `pkcs8` to serialize the public key as SPKI, which includes OIDs which identify it as an elliptic curve public key and also another OID which identifies the curve.
Now that features are namespaced, it's easy to activate `pkcs8` from the `serde` feature to make this a bit easier.
=> elliptic-curve: have `serde` feature activate `pkcs8`

password-hash/src/salt.rs
I am not 100% sure, but I think the length of provided string `s` should be lower or equal to the `MAX_LENGTH`.
When implementing some algorithm that required 64 bytes long salt I couldn't make a new `SaltString` structure due to this issue  and simple change from `<` to the `<=` operator fixed it. What is more, function `Salt::new` allows for the `s` string to be exactly 64 bytes (`MAX_LENGTH`) long. 
I did not find any opened or closed issues related to this matter, so that's why I am not sure if it is a bug or a feature.
=> password-hash: Fix invalid operator in the SaltString struct constructor

.github/workflows/elliptic-curve.yml, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/README.md, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, elliptic-curve/tests/pkcs8.rs
Bumps the following dependencies:
- `crypto-bigint` v0.5
- `pem-rfc7468` v0.7
- `pkcs8` v0.10
- `sec1` v0.7
- `serdect` v0.2
=> elliptic-curve: bump `crypto-bigint` and format crates; MSRV 1.65

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Bump `base16ct` to v0.2
- Put more dependencies behind namespaced features
=> elliptic-curve: dependency cleanups

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- `PublicKey::to_sec1_bytes` ([#1102])
- Forward `std` feature to `sec1` dependency ([#1131])
- `NonIdentity` wrapper type ([#1176])
- Impl `serde` traits for `NonZeroScalar` ([#1178])
- `MulByGenerator` trait ([#1198])
- `NonZeroScalar::invert_vartime` ([#1207])
- `BlindedScalar` type ([#1208])
- `point::Double` trait ([#1218])
- `FieldBytesEncoding` trait ([#1235])
- `Invert::invert_vartime` ([#1239])
- Allow bigger `c1` constant in `OsswuMapParams` ([#1024])
- Rename `Curve::UInt` => `Curve::Uint` ([#1191])
- Use weak feature activation ([#1192], [#1194])
- Consolidate `CurveArithmetic` trait ([#1196])
- Rename `SecretKey::to_pem` => `::to_sec1_pem` ([#1202])
- Rename `ScalarCore` to `ScalarPrimitive` ([#1203])
- Use `CryptoRngCore` trait ([#1206])
- Refactor field element …
=> elliptic-curve v0.13.0

elliptic-curve/src/secret_key.rs, elliptic-curve/tests/secret_key.rs
Tolerates inputs which are slightly shorter than expected (up to 4-bytes) to handle inputs from formats which strip leading zeroes from serialized scalars.
Closes https://github.com/RustCrypto/elliptic-curves/issues/769
=> elliptic-curve: `SecretKey::from_slice` short input support

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- `SecretKey::from_slice` short input support ([#1256])
[#1256]: https://github.com/RustCrypto/traits/pull/1256
=> elliptic-curve v0.13.1

elliptic-curve/Cargo.toml
Activates the `std` feature of `pkcs8` when it's otherwise depended upon
Closes #1262
=> elliptic-curve: weakly activate `pkcs8?/std`

password-hash/src/errors.rs
There's not much in the way of description here, I hope the change is self-explanatory.
=> password-hash: provide std::error::Error::source() for Error

digest/Cargo.toml, universal-hash/Cargo.toml
Relaxes the version requirement from `=2.4` to `^2.4`, which allows usage of the newly published `subtle` v2.5.0 release.
=> digest+universal-hash: loosen `subtle` version requirement

password-hash/Cargo.toml, password-hash/src/salt.rs, password-hash/tests/encoding.rs, password-hash/tests/hashing.rs, password-hash/tests/password_hash.rs
The `Salt` and `SaltString` types are wrappers for B64-encoded salt strings as used by the PHC string format.
These API changes make it clearer that the input string needs to be B64-encoded.
The old API is preserved but with deprecations to ease upgrades.
The following methods were renamed:
- `Salt::new` => `Salt::from_b64`
- `Salt::b64_decode` => `Salt::decode_b64` (for consistency)
- `SaltString::new` => `SaltString::from_b64`
- `SaltString::b64_decode` => `SaltString::decode_b64`
- `SaltString::b64_encode` => `SaltString::encode_b64`
The `Salt::as_bytes` and `SaltString::as_bytes` methods were removed, as they return the B64-encoded string as bytes, rather than decoding B64 to bytes, which is what a user might be expecting.
=> password-hash: clarity improvements for `Salt*` APIs

Cargo.lock, crypto/Cargo.toml, password-hash/CHANGELOG.md, password-hash/Cargo.toml, password-hash/LICENSE-MIT
- `Error::OutputSize` ([#1026])
- `std::error::Error::source` for `Error` ([#1264])
- `getrandom` feature ([#1267])
- Use `Salt` type with `PasswordHasher` ([#1187])
- Rename `Salt::new` => `Salt::from_b64` ([#1266])
- Rename `Salt::b64_decode` => `Salt::decode_b64` ([#1266])
- Rename `SaltString::new` => `SaltString::from_b64` ([#1266])
- Rename `SaltString::b64_decode` => `SaltString::decode_b64` ([#1266])
- Rename `SaltString::b64_encode` => `SaltString::encode_b64` ([#1266])
- Allow `Salt` to be exactly the same amount as `MAX_LENGTH` value ([#1246])
[#1026]: https://github.com/RustCrypto/traits/pull/1026
[#1187]: https://github.com/RustCrypto/traits/pull/1187
[#1246]: https://github.com/RustCrypto/traits/pull/1246
[#1264]: https://github.com/RustCrypto/traits/pull/1264
[#1266]: …
=> password-hash v0.5.0

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Weakly activate `pkcs8?/std` ([#1263])
- More `PublicKey` <-> SEC1 conversions ([#1272])
[#1263]: https://github.com/RustCrypto/traits/pull/1263
[#1272]: https://github.com/RustCrypto/traits/pull/1272
=> elliptic-curve v0.13.2

elliptic-curve/src/public_key.rs
Remove explicit bounds which are already ensured via supertrait bounds.
=> elliptic-curve: remove redundant bounds

elliptic-curve/src/hash2curve/osswu.rs
I found some code I had lying around that I never got to upstream because it has some error in it.
When we were working on hash2curve, I was always confused by the algorithm @mikelodder7 was using for OSSWU, because it wasn't the one used in the specification, later when I finally started digging I found that he was using the "original one" from the paper.
Considering we are not implementing the paper but the specification, I would have liked to update it to the specification, which should basically be the same but definitely yield the exact same results: https://www.ietf.org/archive/id/draft-irtf-cfrg-hash-to-curve-16.html#straightline-sswu.
This would also have the advantage of removing the limitation to q = 3 mod 4 curves in the future, as the spec defines a subroutine that works for …
=> OSSWU update

.github/workflows/aead.yml, .github/workflows/async-signature.yml, .github/workflows/cipher.yml, .github/workflows/crypto-common.yml, .github/workflows/crypto.yml, .github/workflows/digest.yml, .github/workflows/elliptic-curve.yml, .github/workflows/kem.yml, .github/workflows/password-hash.yml, .github/workflows/signature.yml, .github/workflows/universal-hash.yml, .github/workflows/workspace.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/traits/actions/runs/4369716863:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, actions-rs/cargo@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of `actions-rs/cargo` are replaced by direct …
=> Replace unmaintained actions-rs/* actions in CI workflows

signature/src/encoding.rs
Adds a new provided method to the `SignatureEncoding` trait for computing the length of the signature when it's serialized.
=> signature: add `SignatureEncoding::encoded_len`

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml, signature/async/Cargo.toml
- `SignatureEncoding::encoded_len` ([#1283])
[#1283]: https://github.com/RustCrypto/traits/pull/1283
=> signature v2.1.0

elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key/pkcs8.rs
Adds impls for `SecretKey` and `PublicKey`
=> elliptic-curve: impl `AssociatedAlgorithmIdentifier`

elliptic-curve/src/field.rs
This should fix methods like SecretKey::from_slice for curves where the number of bytes in their internal representation is larger than it's modulus (e.g. NIST P224)
=> elliptic-curve: fix FieldBytesEncoding ranges

elliptic-curve/src/dev.rs, elliptic-curve/src/field.rs, elliptic-curve/src/hash2curve/hash2field.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/isogeny.rs, elliptic-curve/src/lib.rs
Adds the following clippy lints and fixes violations thereof:
- clippy::cast_lossless
- clippy::cast_possible_truncation
- clippy::cast_possible_wrap
- clippy::cast_precision_loss
- clippy::cast_sign_loss
- clippy::checked_conversions
- clippy::implicit_saturating_sub
- clippy::integer_arithmetic
- clippy::panic
- clippy::panic_in_result_fn
=> elliptic-curve: expand clippy lints

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Impl `AssociatedAlgorithmIdentifier` for `SecretKey` and `PublicKey` ([#1286])
- Update OSSWU code ([#1157])
- Bump `pkcs8` to v0.10.2 ([#1291])
- `FieldBytesEncoding` provided impl ([#1287])
[#1157]: https://github.com/RustCrypto/traits/pull/1157
[#1286]: https://github.com/RustCrypto/traits/pull/1286
[#1287]: https://github.com/RustCrypto/traits/pull/1287
[#1291]: https://github.com/RustCrypto/traits/pull/1291
=> elliptic-curve v0.13.3

elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs
Fixes the two remaining usages of `C::Uint::BYTES` to use `C::FieldBytesSize::USIZE` instead.
These usages were:
- `NonZeroScalar::from_slice`
- `ScalarPrimitive::from_slice`
=> elliptic-curve: fix remaining `FieldBytesSize` handling

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Bump `hex-literal` to v0.4 ([#1295])
- `NonZeroScalar::from_slice` ([#1296])
- `ScalarPrimitive::from_slice` ([#1296])
[#1295]: https://github.com/RustCrypto/traits/pull/1295
[#1296]: https://github.com/RustCrypto/traits/pull/1296
=> elliptic-curve v0.13.4

signature/derive/CHANGELOG.md, signature/derive/Cargo.toml
- Bump `syn` to v2 ([#1299])
[#1299]: https://github.com/RustCrypto/traits/pull/1299
=> signature_derive v2.0.1

.github/workflows/elliptic-curve.yml, Cargo.lock, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key.rs
The combination of `alloc`+`arithmetic` would previously cause compile errors because some `sec1`-related code was not properly gated.
This fixes the feature gating.
=> elliptic-curve: fix/test alloc+arithmetic features w/o sec1

crypto/CHANGELOG.md, crypto/Cargo.lock, crypto/Cargo.toml, crypto/README.md, crypto/src/lib.rs
- Bump `signature` to v2 ([#1211])
- Bump `password-hash` to v0.5 ([#1271])
- Bump `elliptic-curve` to v0.13; MSRV 1.65 ([#1302])
[#1211]: https://github.com/RustCrypto/traits/pull/1211
[#1271]: https://github.com/RustCrypto/traits/pull/1271
[#1302]: https://github.com/RustCrypto/traits/pull/1302
=> crypto v0.5.0

elliptic-curve/src/public_key.rs
Checks if the SEC1 point is using the identity encoding directly, rather than round tripping through `ProjectivePoint`.
=> elliptic-curve: faster `PublicKey::from_encoded_point`

Cargo.lock, universal-hash/CHANGELOG.md, universal-hash/Cargo.toml
- Loosen `subtle` version requirement to `^2.4` ([#1260])
[#1260]: https://github.com/RustCrypto/traits/pull/1260
=> universal-hash v0.5.1

Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Faster `PublicKey::from_encoded_point` ([#1310])
- `alloc`+`arithmetic` features w/o `sec1` feature ([#1301])
[#1301]: https://github.com/RustCrypto/traits/pull/1301
[#1310]: https://github.com/RustCrypto/traits/pull/1310
=> elliptic-curve v0.13.5

.github/workflows/elliptic-curve.yml, elliptic-curve/Cargo.toml
...when resolving with `-Z minimal-versions`
This appears to be due to earlier versions of `serde_json` itself misspecifying its required `serde` version.
=> elliptic-curve: minimum supported `serde_json` is v1.0.47

elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.lock, elliptic-curve/Cargo.toml
- Minimum supported `hkdf` version is v0.12.1 ([#1353])
- Minimum supported `serde_json` version for `jwk` feature is v1.0.47 ([#1354])
- Minimum supported `tap` version for `bits` feature is v1.0.1 ([#1355])
[#1353]: https://github.com/RustCrypto/traits/pull/1353
[#1354]: https://github.com/RustCrypto/traits/pull/1354
[#1355]: https://github.com/RustCrypto/traits/pull/1355
=> elliptic-curve v0.13.6

aead/src/lib.rs
The documentation originally described TagSize as "the maximum length of the nonce" when it is, in fact, the maximum length of the tag.
=> Fix minor documentation error in AeadCore::TagSize

.github/workflows/cipher.yml
I suspect a nightly regression is responsible for this build failure:
https://github.com/RustCrypto/traits/actions/runs/6648272740/job/18065054230?pr=1319
=> cipher: test `minimal-versions` on stable in CI

.github/workflows/cipher.yml, .github/workflows/digest.yml, Cargo.lock, Cargo.toml, cipher/Cargo.toml, cipher/README.md, cipher/src/block.rs, cipher/src/dev/block.rs, cipher/src/dev/stream.rs, cipher/src/lib.rs, cipher/src/stream_core.rs, digest/Cargo.toml, digest/README.md, digest/src/core_api/ct_variable.rs, digest/src/digest.rs, digest/src/lib.rs
Continuation of #1319.    
Replaces `generic-array` with `hybrid-array`, which is built on a combination of `typenum` and const generics, providing a degree of interoperability between the two systems.
`hybrid-array` is designed to be a largely drop-in replacement, and the number of changes required to switch are relatively minimal aside from some idiosyncrasies.
=> cipher+digest: migrate to hybrid array; MSRV 1.65

cipher/src/block.rs, cipher/src/lib.rs
One of the lifetimes is unused, but we couldn't remove it before because it would be a breaking change.
Closes #1336
=> cipher: remove needless lifetimes

aead/src/dev.rs, aead/src/lib.rs, aead/src/stream.rs, cipher/src/block.rs, cipher/src/dev/block.rs, cipher/src/dev/stream.rs, cipher/src/errors.rs, cipher/src/lib.rs, crypto-common/src/lib.rs, digest/src/core_api/ct_variable.rs, digest/src/core_api/rt_variable.rs, digest/src/core_api/wrapper.rs, digest/src/core_api/xof_reader.rs, digest/src/dev.rs, digest/src/dev/mac.rs, digest/src/digest.rs, digest/src/lib.rs, digest/src/mac.rs, kem/src/lib.rs, universal-hash/src/lib.rs
Migrates the `aead`, `cipher`, `crypto-common`, `digest`, and `universal-hash` crates to use the `doc_auto_cfg` feature which automatically generates documentation for `cfg`-gated code, which in our uses is almost exclusively gated on crate features.
This allows the previous manual `doc_cfg` annotations to be removed, which is nice as they otherwise duplicate work whenever `cfg`-gated code is used.
=> Migrate to `doc_auto_cfg`

crypto-common/src/lib.rs
This commit splits the existing `generate_*` functions into two different variants:
- `fn generate_*`: accepts no parameters and uses `OsRng` automatically. Gated on the `getrandom` feature.
- `fn generate_*_with_rng`: accepts a `&mut impl CryptoRngCore` parameter. Gated on the `rand_core`.
Previously all of the `generate_*` methods were parameterized on a `CryptoRngCore`.
Splitting them up like this makes it very easy for users to do the right thing, which is use `getrandom`/`OsRng`, but without the need to document how to import `OsRng` into their code everywhere.
Retaining the parameterized versions as `*_with_rng` allows users to pass a custom RNG where it makes sense, for example `rand::thread_rng`, or potentially an embedded peripheral/entropy pool.
=> crypto-common: change `generate_*` to support getrandom

crypto-common/src/lib.rs
Adds a fallible `try_*` variant to each `generate_*_with_rng` function, changing usages of `fill_bytes` to `try_fill_bytes`, and returning a `Result` with `rand_core::Error` in the event an RNG error has occurred.
=> crypto-common: add fallible `try_generate_*_with_rng` functions

Cargo.lock, crypto-common/Cargo.toml, crypto-common/src/lib.rs
When both `getrandom` and `rand_core` are enabled, activates the `rand_core/getrandom` feature, which makes `OsRng` available as `crypto_common::rand_core::OsRng`.
=> crypto-common: weakly activate `rand_core/getrandom`

signature/async/src/lib.rs
See: https://github.com/RustCrypto/traits/issues/1373
I've confirmed that with these changes I'm able to produce signatures from non-extractable keys in a browser, using an implementation of `AsyncSigner<S>` that calls out to the `SubtleCrypto` APIs.
I have not tested the `AsyncDigestSigner` traits in a wasm project, however I have confirmed that I'm able to build the project with the `digest` feature enabled.
=> async-signature: remove mandatory Send + Sync bounds

async-signature/src/lib.rs
=> async-signature: re-add 'static bound

cipher/src/stream.rs, cipher/src/stream_core.rs, cipher/src/stream_wrapper.rs
`StreamCipherCoreWrapper` now uses the first byte of inner buffer to store position. This PR also removes a bunch of no longer necessary bounds.
Based on #1174
=> cipher: stream cipher improvements

Cargo.lock, async-signature/CHANGELOG.md, async-signature/Cargo.toml
- MSRV 1.60 ([#1387])
- Mandatory `Send` + `Sync` bounds ([#1375])
[#1375]: https://github.com/RustCrypto/traits/pull/1375
[#1387]: https://github.com/RustCrypto/traits/pull/1387
=> async-signature v0.4.0

Cargo.lock, signature_derive/CHANGELOG.md, signature_derive/Cargo.toml
- MSRV 1.60 ([#1387])
[#1387]: https://github.com/RustCrypto/traits/pull/1387
=> signature_derive v2.1.0

Cargo.lock, signature/CHANGELOG.md, signature/Cargo.toml
- MSRV 1.60 ([#1387])
- No longer vendoring async/derive crates unintentionally ([#1391]) 
[#1387]: https://github.com/RustCrypto/traits/pull/1387
[#1391]: https://github.com/RustCrypto/traits/pull/1391
=> signature v2.2.0

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/ops.rs
Previously the traits were generic around a reference type. The problem with that is reference types have lifetimes, which requires notating them in generic code, in this case requiring an HRTB per generic parameter.
HRTBs work because the output has no lifetime dependencies on the input, but if that's the case we can just explicitly borrow in the function signature in trait, which means no HRTB is needed in generic code, which makes notating the trait bounds significantly simpler.
=> elliptic-curve: remove references from batch generic params

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/point.rs
Since it's functionality related to elliptic curve points, put it under the corresponding module.
=> elliptic-curve: move `BatchNormalize` trait under `point`

elliptic-curve/src/ops.rs
...as the `PointsAndScalars` generic parameter, so we can accept slices
=> elliptic-curve: have `LinearCombinationExt` allow `?Sized`

async-signature/src/lib.rs, cipher/src/lib.rs, crypto-common/src/lib.rs, crypto/src/lib.rs, digest/src/core_api/ct_variable.rs, digest/src/lib.rs, digest/src/mac.rs, kem/src/kem.rs, kem/src/lib.rs, password-hash/src/lib.rs, password-hash/src/params.rs, signature/src/lib.rs, signature_derive/src/lib.rs, universal-hash/src/lib.rs
=> Fix `missing_debug_implementations` for some crates

Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml
- `BatchInvert` and `BatchNormalize` traits ([#1376])
- `LinearCombinationExt` trait ([#1405])
[#1376]: https://github.com/RustCrypto/traits/pull/1376
[#1405]: https://github.com/RustCrypto/traits/pull/1405
=> elliptic-curve v0.13.7

aead/src/lib.rs, aead/src/stream.rs
The `Payload` fields may be considered secret, but they are public in the first place. Plus, usually it's used as a temporary value, so risk of unintentionally exposing sensitive data through it is quite low. IIUC nonce and position fields in the stream constructions are not considered secret, so we can expose them in `Debug`, while AEAD internals will be protected by its own `Debug` impl (if it exists).
Relevant issue: #1389
=> aead: enable `missing_debug_implementations` lint and add `Debug` impls

elliptic-curve/src/secret_key.rs, elliptic-curve/tests/secret_key.rs
To address the concerns in #1330, sets a global minimum elliptic curve key size of 24-bytes (192-bits), which provides the equivalent of 96-bit symmetric security.
=> elliptic-curve: `SecretKey::from_slice` allows >=24-bytes

crypto-common/src/lib.rs, crypto-common/src/serializable_state.rs, digest/src/core_api/ct_variable.rs, digest/src/core_api/rt_variable.rs, digest/src/core_api/wrapper.rs, digest/src/dev.rs
Trait for saving the internal state of the object and restoring it later.
Original PRs: https://github.com/RustCrypto/traits/pull/1078 https://github.com/RustCrypto/traits/pull/1361
Original issue: https://github.com/RustCrypto/hashes/issues/310
=> crypto-common: add SerializableState trait

Cargo.lock, elliptic-curve/CHANGELOG.md, elliptic-curve/Cargo.toml
- `SecretKey::from_slice` now allows >=24-bytes ([#1412])
[#1412]: https://github.com/RustCrypto/traits/pull/1412
=> elliptic-curve v0.13.8

.github/workflows/kem.yml, Cargo.lock, kem/Cargo.toml, kem/README.md
Upgrades the following dependencies:
```
$ cargo update
Updating git repository `https://github.com/RustCrypto/utils.git`
708aa72..cc77203             -> origin/HEAD
Updating crates.io index
Updating async-trait v0.1.74 -> v0.1.75
Updating block-buffer v0.11.0-pre (https://github.com/RustCrypto/utils.git#708aa72b) -> #cc772039
Updating block-padding v0.4.0-pre (https://github.com/RustCrypto/utils.git#708aa72b) -> #cc772039
Updating byteorder v1.4.3 -> v1.5.0
Downgrading cc v1.0.84 -> v1.0.83
Updating hybrid-array v0.2.0-pre.5 (https://github.com/RustCrypto/utils.git#708aa72b) -> #cc772039
Updating inout v0.2.0-pre (https://github.com/RustCrypto/utils.git#708aa72b) -> #cc772039
Updating itoa v1.0.9 -> v1.0.10
Adding jobserver v0.1.27
Updating libc v0.2.150 -> v0.2.151
Updating proc-macro2 …
```
=> Cargo.lock: bump dependencies

.github/workflows/async-signature.yml, .github/workflows/workspace.yml, Cargo.lock, async-signature/Cargo.toml, async-signature/README.md, async-signature/src/lib.rs
=> async-signature: move to AFIT; MSRV 1.75

Cargo.lock, async-signature/Cargo.toml
NOTE: this is not a release, but just to denote that the current `master` contains breaking changes, which were introduced in #1428
=> async-signature: bump version to v0.5.0-pre

async-signature/src/lib.rs
As discussed in #1375. These bounds don't add value: it requires notating them even when unnecessary, and when necessary they still need to be notated anyway.
cc @QuinnWilton
=> async-signature: remove `'static` bounds

Cargo.lock, Cargo.toml, cipher/Cargo.toml, digest/Cargo.toml
Switches to the following prereleases:
- `block-buffer` v0.11.0-pre.1
- `inout` v0.4.0-pre.1
=> Use util crate prereleases

Cargo.lock, Cargo.toml, cipher/Cargo.toml, digest/Cargo.toml
Bumps the following crate dependencies:
- `block-buffer` v0.11.0-pre.2
- `inout` v0.2.0-pre.2
=> Bump RustCrypto/utils crate dependencies

Cargo.lock, async-signature/CHANGELOG.md, async-signature/Cargo.toml
- Debug impls ([#1407])
- Move to AFIT; MSRV 1.75 ([#1428])
- `'static` bounds ([#1430])
[#1407]: https://github.com/RustCrypto/traits/pull/1407
[#1428]: https://github.com/RustCrypto/traits/pull/1428
[#1430]: https://github.com/RustCrypto/traits/pull/1430
=> async-signature v0.5.0

cipher/src/stream_wrapper.rs
When `StreamCipherCoreWrapper` is instantiated via `KeyIvInit::new` or `KeyInit::new`, the first byte of the buffer remains zero. This makes the initial call to `StreamCipherCoreWrapper::get_pos` result in undefined behaviour in release builds.
Additionally, the wrong length is used to index into the buffer when XORing with the tail end of the stream after blocks are processed.
I am performing this commit on a mobile device using the web interface, so I might have missed things. These two issues immediately jumped at me while casually browsing the code.
I see no open issue regarding this and no other PRs attempting to fix this, so I'm just doing this hasty fix. If there is a more fundamental issue at play here that I am not seeing, feel free to suggest/open a fix that supersedes this. …
=> Fix regressions introduced in #1388

signature/CHANGELOG.md, signature/src/signer.rs
Extends #734 with a randomized version. This is useful for [LMS / LM-OTS](https://datatracker.ietf.org/doc/html/rfc8554) signatures, which are stateful and randomized.
=> signature: define a `RandomizedSignerMut` trait

digest/src/dev.rs
These were leftover from the migration to `doc_auto_cfg` in #1370.
They're breaking the doc build.
=> digest: remove lingering `docsrs` attrs

Cargo.lock, crypto/Cargo.toml, password-hash/Cargo.toml
This is not-for-release, but to signal that we are about to begin making breaking changes.
Notably it would be nice to finally land #1352, which adds `ShaCrypt` support and makes the `Encoding` enum `non_exhaustive` so we could potentially add additional encodings in the future without it being a breaking change.
=> Bump `password-hash` to v0.6.0-pre

.github/workflows/elliptic-curve.yml, Cargo.lock, crypto/Cargo.toml, elliptic-curve/Cargo.toml, elliptic-curve/README.md, elliptic-curve/src/dev.rs, elliptic-curve/src/field.rs, elliptic-curve/src/hash2curve/hash2field.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs, elliptic-curve/src/hash2curve/isogeny.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/primitive.rs, elliptic-curve/src/sec1.rs, elliptic-curve/src/secret_key.rs
Migrates from `generic-array` to the `hybrid-array` crate, which provides an `Array` newtype for a public inner core array type, and significantly less unsafe code.
Also bumps `digest` and the encoding format crates (`pem-rfc7468`, `pkcs8`, `sec1`), which have also received similar `hybrid-array` upgrades.
=> elliptic-curve: migrate to hybrid-array; MSRV 1.71

.github/workflows/elliptic-curve.yml, Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/README.md, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/primitive.rs
The latest prerelease of `crypto-bigint` includes changes necessary to also support heap-backed integers (not that we're planning on using them), but also includes expanded modular arithmetic support including an implementation of the Bernstein-Yang modular inversion algorithm.
It also includes a migration to `hybrid-array` which will be necessary for everything to work together correctly.
=> elliptic-curve: bump `crypto-bigint` to v0.6.0-pre.8; MSRV 1.73

Cargo.lock, Cargo.toml, aead/Cargo.toml, aead/src/lib.rs, cipher/Cargo.toml, digest/Cargo.toml, universal-hash/Cargo.toml
Bumps the following dependencies:
- `block-buffer` => v0.11.0-pre.4
- `block-padding` => v0.4.0-pre.4
- `crypto-common` => v0.2.0-pre.4
- `hybrid-array` => v0.2.0-rc.0
- `inout` => v0.2.0-pre.4
Also prepares the following releases:
- `cipher` v0.5.0-pre.2
- `digest` v0.11.0-pre.4
=> Bump `crypto-common` and `hybrid-array`

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml, elliptic-curve/src/secret_key.rs, signature/Cargo.toml
Also cuts v0.14.0-pre.1 and v2.3.0-pre.1 releases respectively
=> elliptic-curve,signature: bump deps; add back to workspace

Cargo.lock, elliptic-curve/Cargo.toml
Also cuts a v0.14.0-pre.2 release of `elliptic-curve`
=> elliptic-curve: bump `crypto-bigint` to v0.6.0-pre.10

Cargo.lock, digest/Cargo.toml, digest/src/mac.rs
Bumps `digest` to 0.11.0-pre.6.
=> digest: return `CtOutput::into_bytes` method

Cargo.lock, elliptic-curve/Cargo.toml, signature/tests/derive.rs
Notably this also includes a bump to `hybrid-array` v0.2.0-rc.1
=> elliptic-curve: bump `crypto-bigint` to v0.6.0-pre.12

.github/workflows/signature.yml, Cargo.lock, elliptic-curve/Cargo.toml, signature/Cargo.toml, signature/README.md
These crates have some circular dependencies on other repos which consume `digest` and needed to be updated first (e.g. `hkdf`, `sha2`).
This also cuts the following prereleases:
- `elliptic-curve` v0.14.0-pre.3
- `signature` v2.3.0-pre.2
=> elliptic-curve+signature: bump `digest` to v0.11.0-pre.7

Cargo.lock, Cargo.toml, async-signature/Cargo.toml
This would be required for https://github.com/RustCrypto/formats/pull/1280/ as I'm pulling both `signature` and `async-signature`.
=> async-signature: bump `signature` to v2.3.0-pre.2

elliptic-curve/src/secret_key.rs
Adds a note to the documentation that `SecretKey::from_slice` is variable-time with respect to the input size.
=> elliptic-curve: `SecretKey::from_slice` timing note

cipher/src/block.rs, cipher/src/stream.rs
Renames the following traits:
- `BlockEncrypt` => `BlockCipherEncrypt`
- `BlockDecrypt` => `BlockCipherDecrypt`
- `BlockEncryptMut` => `BlockModeEncrypt`
- `BlockDecryptMut` => `BlockModeDecrypt`
As originally suggested in this comment:
https://github.com/RustCrypto/block-modes/pull/14#issuecomment-1073304690
This better reflects how these traits are actually used, i.e. `BlockCipher*` is used by ciphers, and `BlockMode*` is used by their modes of operation.
=> cipher: rename `BlockCipher*`/`BlockMode*`

cipher/src/block.rs, cipher/src/dev/block.rs
The branch was never tested against the block ciphers repo located at https://github.com/rustcrypto/block-ciphers
There were various errors and missed changes in macros which were required to get everything to compile.
This includes fixes and has been tested against the downstream repo.
=> cipher: followups to #1482

Cargo.lock
Mostly to spot regressions. Seems like this should be compatible.
=> Bump `hybrid-array` to v0.2.0-rc.2

Cargo.lock, Cargo.toml, aead/Cargo.toml, cipher/Cargo.toml, crypto-common/Cargo.toml, digest/Cargo.toml, universal-hash/Cargo.toml
These sorts of releases are a bit tricky due to the circular dependency of `block-buffer` on `crypto-common`
=> crypto-common v0.2.0-pre.5

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs
Replaces the old, significantly less flexible `LinearCombination` trait with the newer `LinearCombinationExt` trait, removing the old trait completely and renaming the new one.
The bounds for `CurveArithmetic::ProjectivePoint` have also been updated accordingly.
=> elliptic-curve: `LinearCombinationExt` => `LinearCombination`

cipher/src/dev/block.rs
Those were throwing errors in subcrates consuming the macros.
I believe that was forgotten in #1482
=> cipher: fixup macro `block_mode_{dec,enc}_test`

cipher/src/dev/block.rs
Those benchmark macros are reused for both `block-ciphers` and `block-modes`. We need to import both `BlockMode` and `BlockCipher` for them to work.
=> cipher: fixup `block_{encryptor,decryptor}_bench`

elliptic-curve/src/dev.rs, elliptic-curve/src/error.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key/pkcs8.rs, password-hash/src/output.rs, password-hash/src/params.rs
Recent nightlies warn for items which are imported redundantly, of which there were a few in the `elliptic-curve` and `password-hash` crates
=> Remove redundant imports

aead/src/dev.rs
This macro is pulled from `AEADs.git` crates.
=> aead: fixup `hybrid-array` migration

digest/src/dev.rs
This fixes #1487 which moed the `SerialiationState` to `hazmat` submodule
=> digest: fixup imports for `hash_serialization_test` macro

async-signature/CHANGELOG.md
It contains a backport of #1544.
Tagged as https://github.com/RustCrypto/traits/tree/async-signature-v0.5.1
=> async-signature: add CHANGELOG.md entry for v0.5.1

digest/src/core_api/wrapper.rs, digest/src/lib.rs
Add a explicit lifetime for `CustomizedExtArg`. It seems to be needed. See https://github.com/RustCrypto/hashes/pull/573.
=> Add lifetime to CustomizedExtArg

digest/src/core_api/wrapper.rs, digest/src/lib.rs
As discussed in https://github.com/RustCrypto/traits/pull/1561, it is more generic to have only an interface with simple byte slice customization only.
=> Remove CustomizedExtArg

digest/src/hashreader.rs, digest/src/hashwriter.rs, digest/src/lib.rs
Not sure if this is the right place for this, but we've found frequently needing to `read` or `write` data while simultaneously hashing the data. Based on the implementation in the `phase2` crate, gated by the "std" feature.
While creating this PR I noticed this previous [PR](https://github.com/RustCrypto/hashes/issues/22) which is somewhat related, but I think a little different, and I also note the documentation describes that hashers can implement `io::Write`, which I think is also slightly different.
=> Add HashWriter and HashReader structs

digest/src/hashreader.rs, digest/src/hashwriter.rs
CI on master branch is currently broken because of a missing `Debug` implementation.
fixup #1159
=> digest: fixup clippy, add missing `Debug` impl

async-signature/src/lib.rs, async-signature/tests/mock_impl.rs
This introduces a basic check to make sure our blanket implementation would not block manual implementation of the traits in this crate.
Before this commit `AsyncDigestSigner` was causing a conflict:
```
--> async-signature/tests/mock_impl.rs:14:1
|
14 | / impl<D> async_signature::AsyncDigestSigner<D, Signature> for MockSigner
15 | | where
16 | |     D: async_signature::Digest,
| |_______________________________^
|
= note: conflicting implementation in crate `async_signature`:
- impl<D, S, T> AsyncDigestSigner<D, S> for T
where D: Digest, T: DigestSigner<D, S>;
= note: downstream crates may implement trait `async_signature::signature::DigestSigner<_, Signature>` for type `MockSigner`
```
=> async-signature: remove `AsyncDigestSigner` blanket implementation

async-signature/Cargo.toml
`std` gates the From<std::error::Error> implementation from signature.
This allows to enable the feature without importing signature directly.
=> async-signature: forward `std` feature

cipher/src/block.rs
=> cipher: fix documentation for decrypt traits

elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
This tweaks the import of `core::mem::size_of` in order to fix a build failure due to `unused_qualifications` lint, as the function has now been moved to Rust prelude (in 1.80.0 nightly).
Ref: https://github.com/rust-lang/rust/pull/123168
=> elliptic-curve: fix build failure on nightly

Cargo.lock, aead/src/lib.rs, digest/src/core_api/ct_variable.rs, digest/src/core_api/rt_variable.rs, digest/src/core_api/wrapper.rs, elliptic-curve/src/public_key.rs, elliptic-curve/src/secret_key.rs, signature/tests/derive.rs
Also fixes the deprecation warnings
=> Bump `hybrid-array` to v0.2.0-rc.9

Cargo.lock, digest/Cargo.toml, elliptic-curve/Cargo.toml
Bumps the following dependencies:
- `const-oid` v0.10.0-rc.0
- `der` v0.8.0-rc.0
- `pem-rfc7468` v1.0.0-rc.0
- `pkcs8` v0.11.0-rc.0
- `sec1` v0.8.0-rc.0
- `spki` v0.8.0-rc.0
This also relaxes the version requirements to remove the `=*` pinning to specific versions, now that these crates are closer to completion.
=> digest,elliptic-curve: bump format crate prereleases

Cargo.lock, cipher/Cargo.toml
Note: leaving this as a `.pre` instead of an `.rc` so we can experiment with newtypes first before doing an `.rc`
=> cipher v0.5.0-pre.5

Cargo.lock, Cargo.toml, digest/Cargo.toml, signature/Cargo.toml, signature/tests/derive.rs
Due to circular dependencies, it was necessary to temporarily split `elliptic-curve` out of the workspace. It also can't currently resolve a solution for `elliptic-curve`'s Cargo.lock due to `digest`. Excluding `elliptic-curve`, all of the other crates work.
The main causes of this are crates like `sha2` and `sha3` which are circular `dev-dependencies` (i.e. between traits and hashes).
This will temporarily break the `elliptic-curve` build until we can do new releases of `sha2` and `sha3` as well as crates like `hmac` and `hkdf`. Once these have been released, we can put everything back into a single workspace.
=> digest v0.11.0-pre.9

cipher/src/dev/block.rs
The `block_cipher_test!` macro was using deprecated APIs in `hybrid-array` (i.e. `clone_from_slice`)
=> cipher: fix `hybrid-array` deprecations in macros

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml, signature/Cargo.toml, signature/tests/derive.rs
Re-unifies the workspace now that the circular dev-dependencies have been updated
=> Use `digest` v0.11.0-pre.9 crate releases

password-hash/src/output.rs
Allows `Display`/`Debug` printing `Output` with a specific `Encoding` without needing to go through `encode`/`b64_encode`, if e.g. it was created using `init_with`.
Maybe a version of `init_with` that allows specifying an encoding (similar to `new_with_encoding`) would be better, I'm not sure. This is a smaller, more general change.
=> password-hash: Add `Output::with_encoding` method

.github/workflows/aead.yml, Cargo.lock, aead/Cargo.toml, aead/src/lib.rs, aead/src/stream.rs
Sibling PR: https://github.com/RustCrypto/AEADs/pull/627
Closes #1665
=> aead: extract STREAM implementation into `aead-stream`

Cargo.lock, digest/Cargo.toml
Notably this version drops the `crypto-common` dependency
=> digest: bump `block-buffer` to v0.11.0-rc.2

.github/workflows/workspace.yml
The `crypto` crate is linking old versions of the trait crates, and that's causing collisions when building the workspace rustdoc:
https://github.com/RustCrypto/traits/actions/runs/11112631698/job/30875140095
warning: output filename collision.
The lib target `aead` in package `aead v0.6.0-rc.0 (/Users/tony/src/RustCrypto/traits/aead)` has the same output filename as the lib target `aead` in package `aead v0.5.2`.
Colliding filename is: /Users/tony/src/RustCrypto/traits/target/doc/aead/index.html
The targets should have unique names.
This is a known bug where multiple crates with the same name use
the same path; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The lib target `cipher` in package `cipher v0.5.0-pre.7 …
=> CI: fix workspace doc build

signature/src/error.rs
Since errors returned by `std::error::Error::source()` are commonly printed separately, this avoids double-printing the source error message.
Fixes #1685.
=> Remove signature error source from display message

.github/workflows/cipher.yml, cipher/Cargo.toml, cipher/src/lib.rs, cipher/src/stream/errors.rs
Switches from `std::error::Error` to `core::error::Error` which was stabilized in Rust 1.81, which is already the `cipher` crate's current MSRV.
Since this was the only usage of `std`, also removes the `std` feature.
=> cipher: use `core::error`; remove `std` feature

aead/Cargo.toml, aead/src/lib.rs
Switches from `std::error::Error` to `core::error::Error` which was stabilized in Rust 1.81, which is already the `aead` crate's current MSRV.
Since this was the only usage of `std`, also removes the `std` feature.
=> aead: use `core::error`; remove `std` feature

.github/workflows/security-audit.yml
- Pin to `ubuntu-24.04` until upgrade is complete at the end of October
- Re-unify security audit since workspace has been re-unified
- Use `rustsec/audit-check@v2` since `actions-rs` is unmaintained
=> CI: security audit fixups

Cargo.lock, crypto-common/Cargo.toml, elliptic-curve/Cargo.toml
Notably in the `crypto-common` and `elliptic-curve` crates which have direct dependencies on `hybrid-array`.
=> Bump `hybrid-array` to v0.2 (final)

elliptic-curve/src/error.rs, elliptic-curve/src/lib.rs
This trait is now stable in `core`
=> elliptic-curve: leverage `core::error::Error`

elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/jwk.rs
Runs `cargo clippy --all-features --fix` using 1.83.0-beta.1
=> elliptic-curve: clippy fixes

elliptic-curve/src/scalar.rs
The comment was saying that function informs if the scalar is **"greater or equal to"** whereas the implementation informs if the scalar is **"strictly greater than"**
=> fix IsHigh trait comment

universal-hash/CHANGELOG.md
I fixed a typo in the CHANGELOG.md file, correcting the misspelling of "Ouput" to "Output".
=> minor typo CHANGELOG.md

.github/workflows/workspace.yml, .typos.toml, elliptic-curve/CHANGELOG.md
This should hopefully cut down on the number of typo-fixing PRs we receive by automatically checking for them in CI:
https://github.com/crate-ci/typos
=> CI: add `typos` job

.typos.toml
Uses a regex to detect strings that appear to be sequences of Base64-encoded characters, and re-enables the lint for the JWK implementation in `elliptic-curve`
=> CI: add `typos` config for ignoring Base64

aead/src/lib.rs
This size was intended for AEADs based on padded block cipher modes such as CBC in order to express the underlying cipher's block size and therefore the maximum amount of possible padding overhead beyond the original plaintext, which is a full block (in the case a sentinel block is added to a block-aligned plaintext input).
However, every AEAD we implement uses counter mode, i.e. a stream cipher instead of a block cipher, which has no overhead, and as such `CiphertextOverhead` is set to `U0` in every AEAD implementation we currently maintain.
Furthermore, to my knowledge there are no standard AEADs which use CBC or other padded block cipher modes of operation. The original goal was to support an expired draft specification of a CBC+HMAC AEAD.
Since it doesn't appear to be of use, this PR …
=> aead: remove `AeadCore::CiphertextOverhead`

cipher/src/lib.rs, cipher/src/tweak.rs, cipher/src/tweak/ctx.rs, cipher/src/tweak/zero.rs
The trait design generally follows the `BlockCipherEnc/Dec` traits. We currently do not have tweakable block cipher implementations which use the backend capability, but I think it's still worth to include it for API consistency and to future-proof the traits. Some of the helper methods (e.g. `encrypt_blocks`) are not translated since it's unclear how to organize passing of tweaks. Arguably, such methods should not be used with tweakable block ciphers either way.
As a bridge between tweakable and non-tweakable traits the `ZeroTweak` wrapper is introduced. It allows users to use tweakable block cipher implementations with the parts of the ecosystem which expects non-tweakble block ciphers while still being explicit in the code (e.g. `ZeroTweak<Threefish256>`).
Closes #177
=> cipher: add traits for tweakable block ciphers

aead/src/lib.rs
We currently have no implementations which require these traits, or plans to implement any.
If we do wind up needing these, they can be easily added back.
=> aead: remove stateful AEAD traits (`AeadMut*`)

crypto-common/src/lib.rs
=> crypto-common: add methods for weak key testing

Cargo.lock, aead/Cargo.toml, aead/src/lib.rs, async-signature/src/lib.rs, async-signature/tests/mock_impl.rs, cipher/Cargo.toml, crypto-common/Cargo.toml, crypto-common/src/lib.rs, digest/Cargo.toml, password-hash/Cargo.toml, password-hash/src/output.rs, password-hash/src/salt.rs, signature/Cargo.toml, signature/src/error.rs, signature/src/hazmat.rs, signature/src/signer.rs, universal-hash/Cargo.toml
`kem` and `elliptic-curve` can not be migrated because of upstream dependencies which still use `rand_core` v0.6 and expose it in their public API.
`getrandom` crate features are renamed to `os_rng` following the similar change in `rand_core`.
Relevant issue: #1642
=> Partial migration to `rand_core` v0.9

async-signature/README.md, async-signature/src/hazmat.rs, async-signature/src/lib.rs, signature/src/hazmat.rs, signature/src/signer.rs
Fixes #1677
This merge types defined in `async-signature` back into `signature` and effectively deprecates `async-signature`
=> signature: merge types from async-signature

signature/src/hazmat.rs
This is so that a `RandomizedDigestSigner` can call into `hazmat::RandomizedPrehashSigner` directly with the provided rng.
Example use: https://github.com/RustCrypto/signatures/pull/901
=> signature: Prehash should accept a `TryCryptoRng`

elliptic-curve/src/dev.rs
`#[must_use]` annotations have no effect on trait methods.
See this CI job:
https://github.com/RustCrypto/traits/actions/runs/13452612496/job/37589720185
=> elliptic-curve: fix Nightly compiler warnings

signature/src/hazmat.rs, signature/src/signer.rs
Follow up on https://github.com/RustCrypto/traits/pull/1765
=> signature: Relax `Sized` requirements on async signer traits

Cargo.lock, digest/Cargo.toml
Release notes: https://github.com/RustCrypto/formats/pull/1672
=> digest: bump `const-oid` dependency to v0.10

aead/src/lib.rs
Factors apart the detached methods of `AeadInPlace` into a separate `AeadInPlaceDetached` trait, which itself can now more easily be further refactored (by adding e.g. `inout` support).
Also adds a `PostfixTagged` trait which is used to gate the blanket impls.
=> aead: factor apart `AeadInPlace`/`*Detached`

Cargo.lock, Cargo.toml, elliptic-curve/src/dev.rs, elliptic-curve/src/scalar/nonzero.rs
Depends:
- https://github.com/zkcrypto/ff/pull/126
- https://github.com/zkcrypto/ff/pull/127
This is to provide an `ecdsa::SigningKey::try_from_rng` API (https://github.com/RustCrypto/signatures/pull/915)
=> elliptic-curve: adds Scalar::try_from_rng method

elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/secret_key.rs
Follow up to https://github.com/RustCrypto/traits/pull/1774
=> elliptic-curve:: adds `try_from_rng` method to `SecretKey` and `EphemeralSecret`

Cargo.lock, aead/Cargo.toml, aead/src/lib.rs
Renames `AeadInPlaceDetached` to `AeadInOut`, and changes the type signature so the provided `buffer` is now an `InOutBuf`
=> aead: add `inout` support

.github/dependabot.yml
This change automates Cargo.lock updates.
=> ci: update all upstream dependencies with Dependabot

Cargo.lock, Cargo.toml, aead/src/lib.rs, crypto-common/src/lib.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ecdh.rs, elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/scalar/blinded.rs, elliptic-curve/src/scalar/primitive.rs, elliptic-curve/src/secret_key.rs, kem/src/lib.rs, password-hash/src/salt.rs
Depends:
- https://github.com/zkcrypto/group/pull/57
- https://github.com/zkcrypto/group/pull/59
=> relax Sized requirements on the rng

digest/CHANGELOG.md, digest/src/core_api/ct_variable.rs, digest/src/core_api/wrapper.rs, digest/src/digest.rs, digest/src/lib.rs
Together with https://github.com/RustCrypto/traits/pull/1799 users would need to implement `AssociatedOid` manually on created newtypes.
Also replaces `feature = "const-oid"` with `feature = "oid"` in some places.
=> digest: remove `AssociatedOid` blanket impls for wrappers

aead/src/lib.rs
This follows an alphabetic ordering and ordering-of-interest, which should improve documentation
=> aead: move `Aead` ahead of `AeadInOut`

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml
This removes the git dependency to ff and group.
This also removes the now-unused hmac git-patch
=> elliptic-curve: bump ff and group to pre-releases

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs
This now should use `group::Group` directly.
Followup to #1821
=> elliptic-curve: deprecate `MulByGenerator`

elliptic-curve/src/scalar/nonzero.rs
Those TODOs should have been removed in #1774
=> elliptic-curve: cleanup TODOs

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml
Switches to the v0.7.0-pre.1 release
=> elliptic-curve: use `crypto-bigint` release

elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2curve/hash2field.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
This was mainly to fix a bug in handling large DSTs for `expand_message_xof`.
- `ExpandMsg::expand_message()`s `len_in_bytes` parameter is now a `NonZero`, moving one run-time error to the type system.
- In tandem `FromOkm::Length` now requires `typenum::NonZero`.
- Added generic `K` parameter to `ExpandMsg` implementers.
- `ExpandMsgXmd` only uses it to follow constraints set by the specification more closely. See https://www.rfc-editor.org/rfc/rfc9380.html#section-5.3.1-2.1.
- More importantly, `ExpandMsgXof`, requires `K` to calculate the size for the computed DST if the given DST is larger than 255 bytes. This was previously not implemented correctly in that it always used a 32-byte long computed DST.
- Added `type K` to the `GroupDigest` trait. This allows blanket implementations to …
=> Various fixes and improvements to hash2curve

elliptic-curve/src/point/non_identity.rs
This PR implements `Zeroize` for `NonIdentity` setting it to G to prevent breaking any invariants.
I just realized that `elliptic-curve` accepts G as a valid `PublicKey`, which seems a bit dangerous to me. I guess 1 is also a valid `SecretKey`. I have no idea if other libraries take these cases into account.
=> Implement `Zeroize` for `NonIdentity`

elliptic-curve/src/point/non_identity.rs
This PR adds `NonIdentity::mul_by_generator()`, which is similar to the `MulByGenerator` trait, but returns a `NonIdentity` instead of a `ProjectivePoint`. This is quite useful for getting the public key from a `NonZeroScalar` without having to go through the whole conversion dance.
=> Add `NonIdentity::mul_by_generator()`

Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/ops.rs
Replaces `elliptic_curve::ops::Invert` which has an identical shape
=> elliptic-curve: use `crypto_bigint::Invert` trait

elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/scalar/nonzero.rs
This is done by the fact that the underlying types implement these traits already.
=> Implement `PartialEq + Eq` for `NonIdentity` and `NonZeroScalar`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs
Equivalent of #1847 for `Projective/AffinePoint`.
Companion PR to https://github.com/RustCrypto/elliptic-curves/pull/1190.
=> Require `From<NonIdentity>` for `Projective/AffinePoint`

crypto-common/src/lib.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
Bounds like `IsLess` aren't actually enforced unless the `IsLess::Output` is checked. This was done by adding `Le<...>: NonZero`. This PR simplifies this check by adding `IsLess<..., Output = True>`.
These checks were entirely missing in the hash2curve implementation, so I added the improved check here as well.
=> Use `Output = True` instead of `NonZero`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs
This adds a new requirement to `CurveArithmetic::Scalar`: `From<NonZeroScalar<C>>`.
Its currently a bit cumbersome to go through `Deref` or `AsRef` every time and then `Copy`. `Into` seems much more straightforward to me.
Companion PR: https://github.com/RustCrypto/elliptic-curves/pull/1188.
=> Require `From<NonZeroScalar<C>>` for `Scalar<C>`

elliptic-curve/Cargo.toml, elliptic-curve/src/voprf.rs
Main motivation was that `decaf448` (https://github.com/RustCrypto/elliptic-curves/pull/1121) requires `ExpandMsgXof` instead of `ExpandMsgXmd`.
I was briefly tempted to add a `type Hash` to the `ExpandMsg` trait to be able to write `type ExpandMsg = ExpandMsg<Hash = Self::Hash>`. Otherwise it is possible to add a different hash in the `ExpandMsg` type:
```rust
impl VoprfParamters for Fun128 {
type Hash = Sha512;
type ExpandMsg = ExpandMsgXmd<Sha256>;
...
}
```
But I thought its a bit much. Let me know if you want me to add that.
=> Add `type ExpandMsg` to `VoprfParameters`

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs
Adds bounds on `CurveArithmetic::Scalar` that it has a `Mul<P>` impl for both `AffinePoint` and `ProjectivePoint`
=> elliptic-curve: scalar `Mul` bounds

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs
This PR adds the following requirements:
- `CurveArithmetic::Scalar`: `TryInto<NonZeroScalar>`
- `CurveArithmetic::ProjectivePoint`: `TryInto<NonIdentity<ProjectivePoint>>`
- `CurveArithmetic::AffinePoint`: `TryInto<NonIdentity<AffinePoint>>` 
Companion PR to https://github.com/RustCrypto/elliptic-curves/pull/1193.
=> Require `TryInto<Non/Identity/ZeroScalar>`

elliptic-curve/src/public_key.rs
Potentially use pre-computation tables for calculating the `PublicKey` from a `SecretKey`. Though AFAICS currently only `k256` uses pre-computation tables.
=> Use pre-computation tables for `PublicKey::from_secret_scalar()`

digest/CHANGELOG.md, digest/src/core_api/ct_variable.rs, digest/src/core_api/wrapper.rs, digest/src/digest.rs, digest/src/lib.rs
This reverts commit c48ea2a4f76127bd3febce8240095b893e6edb1c (#1810)
This bring back `master` in a state that can be consumed with a `[patch.crates-io]` (see https://github.com/RustCrypto/traits/pull/1799#issuecomment-2885545411)
=> Revert "digest: remove `AssociatedOid` blanket impls for wrappers

digest/src/lib.rs
=> digest: alias core_api with a depreciation notice

elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2curve/map2curve.rs
Fixes #1146
This update implements `MapToCurve` for the curve itself rather than for the field element, and removes the dependency on `CofactorGroup`.
The implementation in p256 would be updated as follows:
```
impl GroupDigest for NistP256 {
type K = U16;
}
impl MapToCurve for NistP256 {
type CurvePoint = ProjectivePoint;
type FieldElement = FieldElement;
fn map_to_curve(element: Self::FieldElement) -> Self::CurvePoint {
let (qx, qy) = element.osswu();
// TODO(tarcieri): assert that `qy` is correct? less circuitous conversion?
AffinePoint::decompress(&qx.to_bytes(), qy.is_odd())
.unwrap()
.into()
}
fn map_to_subgroup(point: Self::CurvePoint) -> ProjectivePoint {
point
}
}
```
@daxpedda
=> elliptic-curve: update `MapToCurve` to avoid `CofactorGroup` dependency

aead/src/lib.rs
- ~~There's no reason for these tests to be gated on `alloc`~~ (aah, we need it, but can go finer-grained)
- Fixes comment on object safety / dyn compatibility test for `Aead`
- Adds dyn compatibility test for `AeadInOut`
=> aead: test fixups

aead/src/lib.rs
`AeadInPlace` was removed in #1798, however in migrating some older code I thought it would be really helpful to have backwards compatibility and deprecations in place to help people migrate to the new names, especially as the "in place" -> "inout" migrations aren't entirely intuitive.
=> aead: deprecated `AeadInPlace` trait

kem/Cargo.toml
=> kem: use Cargo Book ordering for Cargo.toml

elliptic-curve/src/ops.rs
This caused [panics in the `BatchNormalize` implementation of `primeorder`](https://github.com/RustCrypto/elliptic-curves/blob/0c503ceb5a3ccb9dfe5acdfc8efceba8683dddcf/primeorder/src/projective.rs#L384-L385). I don't know why we would disallow zero elements here.
Alternatively I could add a check for zero elements in `BatchNormalize`, but again: I wouldn't know why we would disallow zero elements.
=> Allow `BatchInvert` with zero elements

elliptic-curve/src/dev.rs, elliptic-curve/src/point.rs
In the past we've deliberately avoided exposing the y-coordinate to prevent the possibility of things like invalid curve attacks, although with time we have exposed more and more to support things like alternative point compression formats. See #1237 for some history.
We're now trying to use these traits with Edwards curves like Curve25519 (in `curve25519-dalek`) and Ed448-Goldilocks, which use compressed Edwards y-coordinates as their compressed point format. That requires y-coordinate access.
As such, this changes the previous `y_is_odd` method, which was used to implement SEC1-like compressed points, to a full `fn y` which returns a serialized field element for the y-coordinate.
Closes #1019
=> elliptic-curve: expose `AffineCoordinates::y`

elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/nonzero.rs
This implements `BatchInvert` for `NonZeroScalar`.
To accomplish this, I did the following notable things:
- Remove all trait bounds on `BatchInvert` itself.
- Remove `CtOption` from `BatchInvert::batch_invert`s return type.
- Expose `invert_batch_internal()` internally, which now takes an `invert` function instead of requiring `trait Invert`.
- Implement `MulAssign` for `NonZeroScalar`.
Things that could still be added:
- Mirror all `BatchInvert` implementations on `Scalar`, I left the ones taking a reference to a slice out.
- Implement `MulAssign` for `NonZeroScalar` on more combinations.
It might be a tiny bit simpler if I implemented `Default` on `NonZeroScalar`, but that seemed like a footgun to me.
=> elliptic-curve: impl `BatchInvert` for `NonZeroScalar`

elliptic-curve/src/lib.rs, elliptic-curve/src/macros.rs
Extracts macros for writing `From` and `Mul` impls for scalar types.
It would be nice to use these with `ed448-goldilocks` which isn't a prime order curve, and really these macros work for any elliptic curve, not just prime order curves (`primeorder` was previously just a convenient place to put them).
cc @baloo
=> elliptic-curve: extract scalar macros from `primeorder`

elliptic-curve/src/hash2curve/group_digest.rs, elliptic-curve/src/hash2curve/hash2field.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xmd.rs, elliptic-curve/src/hash2curve/hash2field/expand_msg/xof.rs
This PR introduces two changes:
- Remove requirements that were only relevant for oversized `DST`s. Now these requirements are checked on runtime. While this is unfortunate, the currently limitations simply was that usage with regular sized `DST`s incurred limitations that were not necessary.
- Change `len_in_bytes` from `NonZero<usize>` to `NonZero<u16>`. This isn't a big improvement because the error is just moved from `expand_msg()` to the various `GroupDigest` methods.
Companion PR: https://github.com/RustCrypto/elliptic-curves/pull/1256.
---
I know I have been refactoring this API over and over again, but I actually think this is the last of it (apart from https://github.com/RustCrypto/traits/pull/872 with `generic_const_exprs`).
But for completions sake I want to mention the …
=> hash2curve: move oversized DST requirements to runtime errors

elliptic-curve/src/lib.rs, elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/scalar/nonzero.rs
These methods encapsulate safely casting references for arrays and slices of `NonIdentity<P>` to array/slice references to the inner `P` type, and the same for `NonZeroScalar` and its inner `Scalar<C>` type.
Note the choice of method names follows from similar ones in `hybrid-array`: https://docs.rs/hybrid-array/latest/hybrid_array/struct.Array.html#method.cast_slice_to_core
cc @daxpedda
=> elliptic-curve: extract `NonIdentity`/`NonZeroScalar` casting methods

elliptic-curve/src/point/non_identity.rs, elliptic-curve/src/public_key.rs
Where these missed in https://github.com/RustCrypto/traits/pull/1902?
If not feel free to close.
=> Use `elliptic_curve::CurveGroup`

cipher/src/stream.rs, cipher/src/stream/wrapper.rs
=> cipher: add methods for writing keystream

elliptic-curve/src/ecdh.rs
Replaced the outdated SIGMA protocol reference link in the ECDH module documentation with the official IACR archive PDF. The new link points to the full text of "SIGMA: the 'SIGn-and-MAc' Approach to Authenticated Diffie-Hellman and its Use in the IKE Protocols" by Hugo Krawczyk (CRYPTO 2003), ensuring long-term accessibility and citation accuracy.
=> elliptic-curve: update SIGMA protocol reference link

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml
- pkcs8 v0.11.0-rc.5
- sec1 v0.8.0-rc.6
=> elliptic-curve: bump `pkcs8` and `sec1`

signature/CHANGELOG.md, signature/src/signer.rs
=> signature: Remove blanket `SignerMut` impl (breaking change)

elliptic-curve/src/macros.rs
Currently the doc comment looks like this:
I used `elliptic_curve` instead of `$crate` because `stringify!($crate)` doesn't work.
Now it looks like this:
=> elliptic-curve: fix doc comment in `TryFrom<Scalar>` for `NonZeroScalar`

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml, elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs
Companion PR to RustCrypto/formats#1927 which properly composes the PKCS#8 impl in terms of the SEC1 impl
=> Remove PKCS#8 blanket impls for SEC1 private key traits

elliptic-curve/src/secret_key.rs, elliptic-curve/src/secret_key/pkcs8.rs
It wasn't including the curve OID as `EcParameters`. Previously the logic for populating this field lived in the `sec1` crate.
Since SEC1 needs a slightly different serialization than PKCS#8 (notably the latter hoists the curve OID onto `AlgorithmParameters` and omits it from the SEC1 `EcPrivateKey` this more or less reverts the PKCS#8 serialization logic to what it was before.
=> elliptic-curve: fix SEC1 serialization

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/ops.rs, elliptic-curve/src/scalar/nonzero.rs
Introduced in RustCrypto/crypto-bigint#887
=> elliptic-curve: use `crypto_bigint::Reduce` trait

digest/CHANGELOG.md, digest/src/dev.rs, digest/src/dev/mac.rs, digest/src/dev/rng.rs
Names of test functions and names of associated KAT file usually match, so it's worth to simplify the macro to reduce amount of duplication at call sites.
=> digest: simplify test macros using `stringify!`

Cargo.lock, Cargo.toml, cipher/Cargo.toml, cipher/src/dev/stream.rs, cipher/src/lib.rs, cipher/src/stream.rs, cipher/src/stream/wrapper.rs, digest/src/buffer_macros/xof.rs
This simplifies the wrapper code and allows to mark the `cipher` crate with `#![forbid(unsafe_code)]`.
Depends on https://github.com/RustCrypto/utils/pull/1201
=> cipher: use `block_buffer::ReadBuffer` in `StreamCipherCoreWrapper`

Cargo.lock, Cargo.toml
I forgot to remove the `branch` field in #1959.
=> Fix `block-buffer` patch

Cargo.lock
v0.4.0 was the last thing depending on `base16ct` v0.2
=> Bump `serdect` to v0.4.1

Cargo.lock, aead/Cargo.toml, cipher/Cargo.toml, crypto-common/Cargo.toml, crypto/Cargo.toml, digest/Cargo.toml, universal-hash/Cargo.toml
Notably includes `hybrid-array` v0.4 support
=> crypto-common v0.2.0-rc.4

Cargo.lock, Cargo.toml, elliptic-curve/Cargo.toml
Notably this includes `hybrid-array` v0.4 support
=> elliptic-curve: bump `sec1` to v0.8.0-rc.9

.github/workflows/aead.yml, Cargo.lock, aead/CHANGELOG.md, aead/Cargo.toml, aead/src/lib.rs, aead/tests/dummy.rs
`heapless` v0.9 has MSRV 1.87 while we would like to keep MSRV 1.85 for the initial aead v0.6.0 release. We plan to add support in v0.6.1 immediately after v0.6.0 release.
=> aead: remove `heapless` support

elliptic-curve/src/arithmetic.rs, elliptic-curve/src/dev.rs, elliptic-curve/src/lib.rs, elliptic-curve/src/macros.rs, elliptic-curve/src/scalar.rs, elliptic-curve/src/scalar/nonzero.rs, elliptic-curve/src/scalar/value.rs, elliptic-curve/src/secret_key.rs
Denotes the type reperents an integer value in range of the scalar modulus.
Ideally we could get rid of this type if there were a suitable replacement type somewhere else, e.g. RustCrypto/elliptic-curves#1192
=> elliptic-curve: rename `ScalarPrimitive` => `ScalarValue`

signature/src/signer.rs, signature/src/verifier.rs
I honestly tried to find the right words for the documentation, but it all sounds rather off to me.
My suspicion is that we will actually need `FnMut` here if users intend to use some `Reader` API inside.
Companion PR: https://github.com/RustCrypto/signatures/pull/1064.
Resolves #2003.
=> signature: use `Fn(&mut D)` for `*DigestSigner`/`*DigestVerifier`

.github/workflows/elliptic-curve.yml, Cargo.lock, elliptic-curve/Cargo.toml, elliptic-curve/src/point.rs, elliptic-curve/src/point/basepoint_table.rs, elliptic-curve/src/point/lookup_table.rs, elliptic-curve/src/point/non_identity.rs
Implementation is originally from the `k256` crate, but written to be generic over a `Point` type which is bound by the `Group` trait.
Adds a `LookupTable` type which supports precomputed lookup tables for a given curve point which can be selected from in constant time.
Also adds a feature-gated `BasepointTable` type with a `const fn` constructor which builds a table for precomputed fixed-base scalar multiplication using the `Group::generator` as the base point.
The `const fn` support for `BasepointTable` is achieved via a `LazyLock`-style pattern which computes the table lazily upon first use in a synchronized fashion. It supports using either `std::sync::LazyLock`, or for `no_std` targets it also supports using the `critical-section` feature of the `once_cell` crate.
=> elliptic-curve: add `point::LookupTable` and `BasepointTable`

Cargo.lock, digest/src/mac.rs, elliptic-curve/Cargo.toml
This notably enables the `subtle` feature of `hybrid-array`. This apparently broke `digest` where previously the unsized coercion was working until an explicit impl was available. So this PR also includes a small fix to `digest`.
=> elliptic-curve: bump crypto-bigint to v0.7.0-rc.8
